variables:
  CONFIG_ARGS: ""  # Variable for additional arguments for configure.sh

stages:
  - build
  - warnconv
  - test
  - memleaks

.exemptfiles_template: &exemptfiles_definition  # Hidden key that defines an anchor named 'exemptfiles_definition'
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*

.build_template: &build_definition
  stage: build
  <<: *exemptfiles_definition
  script:
    - apt-get update && apt install -y python curl libghc-zlib-dev g++
    - . configure.sh GNU serial $CONFIG_ARGS
    - gfortran -v
    - make all

.build_template_pgi: &build_definition_pgi
  stage: build
  <<: *exemptfiles_definition
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev
    - pgfortran --version
    - . configure.sh PGI serial $CONFIG_ARGS
    - make all

.warnconv_template: &warnconv_definition
  stage: warnconv
  <<: *exemptfiles_definition
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - . configure.sh GNU Devel serial $CONFIG_ARGS
    - gfortran -v
    - make all

.test_template: &test_definition
  stage: test
  <<: *exemptfiles_definition
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - . configure.sh GNU Devel serial $CONFIG_ARGS
    - gfortran -v
    - make lib
    - make ana
    - make program
    - cd testsuite
    - cmake -E make_directory tests
    - cd tests
    - cmake ..
    - cmake --build . --target all --config Release
    - ctest -VV -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

# GQMCT_Jessie:
#   image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:jessie-gfortran-blas-lapack
#   <<: *build_definition

GQMCT_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5
  <<: *build_definition

GQMCT_Buster:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *build_definition

GQMCT_Bullseye:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *build_definition


#GQMCT_Jessie_OpenBlas:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:jessie-gfortran-openblas-lapack
  #<<: *build_definition

GQMCT_Bullseye_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-openblas-lapack
  <<: *build_definition

#GQMCT_CentOS:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  #<<: *build_definition

#GQMCT_OpenSuse-13.2:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  #<<: *build_definition

#GQMCT_OpenSuse-42.1:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  #<<: *build_definition

GQMCT_PGI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  <<: *build_definition_pgi

#GQMCT_Ubuntu_Trusty:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:trusty-tahr-gfortran-lapack
  #<<: *build_definition

#GQMCT_Ubuntu_Xenial:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:xenial-gfortran-lapack
  #<<: *build_definition

GQMCT_Ubuntu_Bionic:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
  <<: *build_definition

GQMCT_Stretch_MPI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: build
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - gfortran -v
    - . configure.sh GNU Devel Tempering $CONFIG_ARGS
    - export ALF_FC="mpif90"
    - make all

GQMCT_Intel-21:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-intel-oneapi-ifort-python3
  stage: build
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
  script:
    - apt-get update && apt install -y curl libghc-zlib-dev
    - . /opt/intel/oneapi/setvars.sh
    - . configure.sh INTEL serial $CONFIG_ARGS
    - make all

#GQMCT_Jessie_conv:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:jessie-gfortran-blas-lapack
  #<<: *warnconv_definition

GQMCT_Stretch_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5
  <<: *warnconv_definition

GQMCT_Buster_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *warnconv_definition

GQMCT_Bullseye_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *warnconv_definition

GQMCT_Bullseye_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-openblas-lapack
  <<: *warnconv_definition

#GQMCT_CentOS_conv:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  #<<: *warnconv_definition

#GQMCT_OpenSuse-13.2_conv:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  #<<: *warnconv_definition

#GQMCT_OpenSuse-42.1_conv:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  #<<: *warnconv_definition

GQMCT_PGI_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  stage: warnconv
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev
    - pgfortran --version
    - . configure.sh PGI serial $CONFIG_ARGS
    - make all

#GQMCT_Jessie_tests:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:jessie-gfortran-blas-lapack
  #<<: *test_definition

GQMCT_Stretch_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5
  <<: *test_definition

GQMCT_Buster_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *test_definition

GQMCT_Bullseye_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack-fftw-hdf5-scipy3
  <<: *test_definition

GQMCT_Stretch_OpenBlas_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-openblas-lapack
  <<: *test_definition

#GQMCT_CentOS_tests:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  #<<: *test_definition

#GQMCT_OpenSuse-13.2_tests:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  #<<: *test_definition

#GQMCT_OpenSuse-42.1_tests:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  #<<: *test_definition

#GQMCT_Ubuntu-trusty_tests:
  #image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:trusty-tahr-gfortran-lapack
  #<<: *test_definition

GQMCT_Ubuntu-bionic_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
  <<: *test_definition

GQMCT_PGI_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  stage: test
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev
    - pgfortran --version
    - . configure.sh PGI serial $CONFIG_ARGS
    - make lib
    - make ana
    - make program
    - cd testsuite
    - cmake -E make_directory tests
    - cd tests
    - cmake ..
    - cmake --build . --target all --config Release
    - ctest -VV -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

GQMCT_Stretch_valgrind:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5-valgrind
  stage: memleaks
  only:
    changes:
      - Prog/*.(f|F)90
      - Libraries/Modules/*.(f|F)90
  script:
      - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
      - export ALF_FLAGS_EXT="-g"
      - . configure.sh GNU serial $CONFIG_ARGS
      - gfortran -v
      - make lib
      - make program
      - cp Prog/ALF.out Scripts_and_Parameters_files/Start
      - cd Scripts_and_Parameters_files/Start
      - valgrind --leak-check=full --log-file=vglog.txt ./ALF.out
      - cat vglog.txt
      - grep lost vglog.txt | cut -d":" -f 2 | cut -d " " -f 2 | f=$(cat); echo $(( ${f//$'\n'/+} ))

create_doc:
  image: aergus/latex
  stage: build
  artifacts:
    paths:
      - Documentation/doc.pdf
  script:
    - cd Documentation
    - latexmk -pdf doc.tex

create_doxygen:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-clang
  stage: build
  artifacts:
    expire_in: 120 days
    paths:
      - doxygen/*
      - Images/*
  script:
      - apt-get update && apt install -y doxygen graphviz
      - doxygen doxygen/Doxyfile
