variables:
  CONFIG_ARGS: ""  # Variable for additional arguments for configure.sh
  ALF_FLAGS_EXT: "-DPIPELINE"

stages:
  - build
  - warnconv
  - test
  - memleaks

.build_template: &build_definition
  stage: build
  needs: []
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - . configure.sh GNU serial $CONFIG_ARGS
    - gfortran -v
    - make all

.build_template_pgi: &build_definition_pgi
  stage: build
  needs: []
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev
    - pgfortran --version
    - . configure.sh PGI serial $CONFIG_ARGS
    - make all

.warnconv_template: &warnconv_definition
  stage: warnconv
  needs: []
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - . configure.sh GNU Devel serial $CONFIG_ARGS
    - gfortran -v
    - make all

.test_template: &test_definition
  stage: test
  needs: []
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - . configure.sh GNU Devel serial $CONFIG_ARGS
    - gfortran -v
    - make lib
    - make ana
    - make program
    - cd testsuite
    - cmake -E make_directory tests
    - cd tests
    - cmake ..
    - cmake --build . --target all --config Release
    - ctest -VV -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

GQMCT_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Buster:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Bullseye:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack
  <<: *build_definition


GQMCT_Bullseye_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_PGI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  <<: *build_definition_pgi

GQMCT_Ubuntu_Bionic:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
  <<: *build_definition

GQMCT_Stretch_MPI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-fftw-hdf5-scipy3
  stage: build
  needs: []
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
    - gfortran -v
    - . configure.sh GNU Devel Tempering $CONFIG_ARGS
    - export ALF_FC="mpif90"
    - make all

GQMCT_Intel-21:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-intel-oneapi-ifort-python3
  stage: build
  needs: []
  except:
    changes:
      - .gitignore
      - CITATION
      - README.md
      - license.*
  script:
    - apt-get update && apt install -y curl libghc-zlib-dev
    - . /opt/intel/oneapi/setvars.sh
    - . configure.sh INTEL serial $CONFIG_ARGS
    - make all

GQMCT_Stretch_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Buster_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Bullseye_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Bullseye_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_PGI_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  stage: warnconv
  needs: []
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev
    - pgfortran --version
    - . configure.sh PGI devel serial $CONFIG_ARGS
    - make all

GQMCT_Stretch_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Buster_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Bullseye_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Stretch_OpenBlas_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-openblas-lapack
  <<: *test_definition

GQMCT_Ubuntu-bionic_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/ubuntu:bionic-beaver-gfortran-lapack
  <<: *test_definition

GQMCT_PGI_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:bullseye-pgi-21-03
  stage: test
  needs: []
  script:
    - apt-get update && apt install -y python3 curl libghc-zlib-dev
    - pgfortran --version
    - . configure.sh PGI devel serial $CONFIG_ARGS
    - make lib
    - make ana
    - make program
    - cd testsuite
    - cmake -E make_directory tests
    - cd tests
    - cmake ..
    - cmake --build . --target all --config Release
    - ctest -VV -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

GQMCT_Stretch_valgrind:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:stretch-gfortran-blas-lapack-valgrind
  stage: memleaks
  needs: []
  only:
    changes:
      - Prog/*.(f|F)90
      - Libraries/Modules/*.(f|F)90
  script:
      - apt-get update && apt install -y python3 curl libghc-zlib-dev g++
      - . configure.sh GNU devel serial $CONFIG_ARGS
      - gfortran -v
      - make lib
      - make program
      - cp Prog/ALF.out Scripts_and_Parameters_files/Start
      - cd Scripts_and_Parameters_files/Start
      - cat parameters
      - valgrind --leak-check=full --log-file=vglog.txt ./ALF.out
      - cat vglog.txt
      - grep lost vglog.txt | cut -d":" -f 2 | cut -d " " -f 2 | f=$(cat); echo $(( ${f//$'\n'/+} ))

create_doc:
  image: aergus/latex
  stage: build
  needs: []
  artifacts:
    paths:
      - Documentation/doc.pdf
  script:
    - cd Documentation
    - latexmk -pdf doc.tex

create_doxygen:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-clang
  stage: build
  needs: []
  artifacts:
    expire_in: 120 days
    paths:
      - doxygen/*
      - Images/*
  script:
      - apt-get update && apt install -y doxygen graphviz
      - doxygen doxygen/Doxyfile

pages:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi/debian:buster-clang
  stage: build
  script:
    - apt-get update && apt install -y doxygen graphviz
    - doxygen doxygen/Doxyfile
    - mkdir public
    - mv doxygen/html/* public
  artifacts:
    paths:
      - public

