types:
  - build
  - test

.build_template: &build_definition
  type: build
  script:
    - . configure.sh
    - cd Libraries
    - make
    - cd ..
    - cd Prog_8
    - make

GQMCT_Wheezy:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Jessie:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Wheezy_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_Jessie_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_Stretch_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-openblas-lapack
  <<: *build_definition