types:
  - build
  - test

.build_template: &build_definition
  type: build
  script:
    - . configure.sh
    - cd Libraries
    - make
    - cd ..
    - cd Prog_8
    - make

GQMCT:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *build_definition

