stages:
  - build
  - warnconv
  - test
  - memleaks

.build_template: &build_definition
  stage: build
  script:
    - . setenv.sh
    - export f90="gfortran"
    - cd Libraries
    - gfortran -v
    - make
    - cd ..
    - cd Prog
    - make
    - make Kondo_Honey

.build_template_pgi: &build_definition_pgi
  stage: build
  script:
    - . setenv.sh
    - export f90="/opt/pgi/linux86-64/2016/bin/pgfortran"
    - export FL="-O3"
    - export LIB_BLAS_LAPACK="-L/opt/pgi/linux86-64/2016/lib -llapack -lblas"
    - export F90USEFULFLAGS="-Mpreprocess"
    - cd Libraries
    - /opt/pgi/linux86-64/16.10/bin/pgfortran --version
    - make
    - cd ..
    - cd Prog
    - make
    - make Kondo_Honey

.warnconv_template: &warnconv_definition
  stage: warnconv
  script:
    - . setenv.sh
    - export f90="gfortran"
    - export FL="$FL -Wconversion -Werror"
    - cd Libraries
    - gfortran -v
    - make
    - cd ..
    - cd Prog
    - make
    - make Kondo_Honey

.test_template: &test_definition
  stage: test
  script:
    - . setenv.sh
    - export f90="gfortran"
    - cd Libraries
    - gfortran -v
    - make
    - cd ..
    - cd Prog
    - make
    - cd ..
    - cd testsuite
    - cmake -E make_directory tests
    - cd tests
    - cmake -G "Unix Makefiles" -DCMAKE_Fortran_FLAGS_RELEASE=${F90OPTFLAGS} -DCMAKE_BUILD_TYPE=RELEASE ..
    - cmake --build . --target all --config Release
    - ctest -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

GQMCT_Wheezy:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Jessie:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Wheezy_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_Jessie_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_Stretch_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_CentOS:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  <<: *build_definition

GQMCT_OpenSuse-13.2:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  <<: *build_definition

GQMCT_OpenSuse-42.1:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Wheezy-PGI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-pgi
  <<: *build_definition_pgi

GQMCT_Jessie-PGI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-pgi
  <<: *build_definition_pgi

GQMCT_Ubuntu_Trusty:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:trusty-gfortran-lapack
  <<: *build_definition

GQMCT_Ubuntu_Xenial:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:xenial-gfortran-lapack
  <<: *build_definition
  
GQMCT_Jessie_MPI:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack-fftw-scipy
  stage: build
  script:
    - gfortran -v
    - make f90='mpif90' PROGRAMCONFIGURATION='-DMPI -DTEMPERING' Hub_Ising

GQMCT_Wheezy_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Jessie_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Stretch_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Wheezy_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_Jessie_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_Stretch_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_CentOS_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_OpenSuse-13.2_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_OpenSuse-42.1_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  <<: *warnconv_definition
  
GQMCT_Wheezy-PGI_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-pgi
  stage: warnconv
  script:
    - . setenv.sh
    - export f90="/opt/pgi/linux86-64/2016/bin/pgfortran"
    - export FL="-O3 -Minform=inform"
    - export LIB_BLAS_LAPACK="-L/opt/pgi/linux86-64/2016/lib -llapack -lblas"
    - export F90USEFULFLAGS="-Mpreprocess -Minform=inform"
    - cd Libraries
    - /opt/pgi/linux86-64/16.10/bin/pgfortran --version
    - make
    - cd ..
    - cd Prog
    - make
    - make Kondo_Honey
  
GQMCT_Wheezy_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Jessie_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Stretch_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Wheezy_OpenBlas_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-openblas-lapack
  <<: *test_definition

GQMCT_Jessie_OpenBlas_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-openblas-lapack
  <<: *test_definition

GQMCT_Stretch_OpenBlas_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-openblas-lapack
  <<: *test_definition

GQMCT_CentOS_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  <<: *test_definition

GQMCT_OpenSuse-13.2_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  <<: *test_definition

GQMCT_OpenSuse-42.1_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  <<: *test_definition

GQMCT_Ubuntu-trusty_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:trusty-gfortran-lapack
  <<: *test_definition

GQMCT_Jessie-PGI_tests:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-pgi-cmake
  stage: test
  script:
    - . setenv.sh
    - export f90="/opt/pgi/linux86-64/2016/bin/pgfortran"
    - export FL="-O3"
    - export LIB_BLAS_LAPACK="-L/opt/pgi/linux86-64/2016/lib -llapack -lblas"
    - export F90USEFULFLAGS="-Mpreprocess"
    - cd Libraries
    - /opt/pgi/linux86-64/16.10/bin/pgfortran --version
    - make
    - cd ..
    - cd Prog
    - make
    - cd ..
    - cd testsuite
    - cmake -E make_directory tests
    - cd tests
    - cmake -G "Unix Makefiles" -DCMAKE_Fortran_FLAGS_RELEASE="${F90OPTFLAGS} -noswitcherror -L/opt/pgi/linux86-64/2016/lib/ -llapack -lblas" -DCMAKE_Fortran_COMPILER="/opt/pgi/linux86-64/2016/bin/pgfortran" -DCMAKE_BUILD_TYPE=RELEASE -DLAPACK_LIBRARIES="/opt/pgi/linux86-64/2016/lib/liblapack.a" -DBLAS_LIBRARIES="/opt/pgi/linux86-64/2016/lib/libblas.a" ..
    - cmake --build . --target all --config Release
    - ctest -O log.txt
    - cat log.txt | grep "tests passed" | cut -d " " -f 1

GQMCT_jessie_valgrind:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-blas-lapack-valgrind
  stage: memleaks
  script:
      - . setenv.sh
      - export f90="gfortran"
      - export FL="${FL} -g"
      - cd Libraries
      - gfortran -v
      - make
      - cd ..
      - cd Prog
      - make SPT
      - cp SPT.out ../Test_Runs/Test_SPT/Start/
      - cd ../Test_Runs/Test_SPT/Start/
      - valgrind --leak-check=full --log-file=vglog.txt ./SPT.out
      - cat vglog.txt
      - grep lost vglog.txt | cut -d":" -f 2 | cut -d " " -f 2 | f=$(cat); echo $(( ${f//$'\n'/+} ))


