stages:
  - build
  - warnconv
  - test

.build_template: &build_definition
  stage: build
  script:
    - . set_env.sh
    - cd Libraries
    - gfortran -v
    - make
    - cd ..
    - cd Prog_8
    - make
    - make Ising
    - make Kondo_Honey

.warnconv_template: &warnconv_definition
  stage: warnconv
  script:
    - . set_env.sh
    - export FL="$FL -Wconversion -Werror"
    - cd Libraries
    - gfortran -v
    - make
    - cd ..
    - cd Prog_8
    - make
    - make Ising
    - make Kondo_Honey

GQMCT_Wheezy:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Jessie:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Stretch:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Wheezy_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_Jessie_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_Stretch_OpenBlas:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-openblas-lapack
  <<: *build_definition

GQMCT_CentOS:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  <<: *build_definition

GQMCT_OpenSuse-13.2:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  <<: *build_definition

GQMCT_OpenSuse-42.1:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  <<: *build_definition

GQMCT_Wheezy_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Jessie_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Stretch_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_Wheezy_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-wheezy-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_Jessie_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-jessie-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_Stretch_OpenBlas_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:debian-stretch-gfortran-openblas-lapack
  <<: *warnconv_definition

GQMCT_CentOS_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:centos-7-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_OpenSuse-13.2_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-13.2-gfortran-blas-lapack
  <<: *warnconv_definition

GQMCT_OpenSuse-42.1_conv:
  image: git.physik.uni-wuerzburg.de:25812/z03/pdi:opensuse-42.1-gfortran-blas-lapack
  <<: *warnconv_definition
