ALF: cgr1.f90 File Reference
cgr1.f90 File Reference
Functions/Subroutines
subroutine cgr (PHASE, NVAR, GRUP, udvr, udvl)
Computes GRUP = (1 + UR*DR*VR*VL*DL*UL)^-1 and PHASE = det(1 + UR*DR*VR*VL*DL*UL) / abs(det(1 + UR*DR*VR*VL*DL*UL)) NVAR = 1 Big scales are in DL NVAR = 2 Big scales are in DR Implementation note: we calculate the Phase as: NVAR = 1 : Phase = det(URUP * ULUP)/ |det(URUP * ULUP)| * det(P) * det(R) det(Q)/ |det(R) det(Q)| NVAR = 2 : Phase = det(URUP * ULUP)/ |det(URUP * ULUP)| * det(P) * det^(R) det^(Q)/ |det(R) det(Q)| If STAB3 is selected the following tweak is applied We seperate D as D^+ * D^- where D^+ (D^-) contains the scales larger (smaller) then 1.0 Also, we use (DR^+^-1 UR^* UL^* DL^+^-1 + DR^- VR VL DL^-)^-1 = UL^* DL^+^-1 GRUP Dr^+^-1 UR^* .
subroutine cgrp (phase, GRUP, udvr, udvl)
Computes the Green's function in the projective implementation.
Function/Subroutine Documentation
cgr()
subroutine cgr (complex(kind=kind(0.d0)), intent(inout) PHASE, integer NVAR, complex(kind=kind(0.d0)), dimension(:,:), intent(inout) GRUP, class(udv_state), intent(in) udvr, class(udv_state), intent(in) udvl)
Computes GRUP = (1 + UR*DR*VR*VL*DL*UL)^-1 and PHASE = det(1 + UR*DR*VR*VL*DL*UL) / abs(det(1 + UR*DR*VR*VL*DL*UL)) NVAR = 1 Big scales are in DL NVAR = 2 Big scales are in DR Implementation note: we calculate the Phase as: NVAR = 1 : Phase = det(URUP * ULUP)/ |det(URUP * ULUP)| * det(P) * det(R) det(Q)/ |det(R) det(Q)| NVAR = 2 : Phase = det(URUP * ULUP)/ |det(URUP * ULUP)| * det(P) * det^(R) det^(Q)/ |det(R) det(Q)| If STAB3 is selected the following tweak is applied We seperate D as D^+ * D^- where D^+ (D^-) contains the scales larger (smaller) then 1.0 Also, we use (DR^+^-1 UR^* UL^* DL^+^-1 + DR^- VR VL DL^-)^-1 = UL^* DL^+^-1 GRUP Dr^+^-1 UR^* .
Parameters
[in] udvl
[in] udvr Computes GRUP = (1 + UR*DR*VR*VL*DL*UL)^-1 and PHASE = det(1 + UR*DR*VR*VL*DL*UL) / abs(det(1 + UR*DR*VR*VL*DL*UL)) NVAR = 1 Big scales are in DL NVAR = 2 Big scales are in DR Implementation note: we calculate the Phase as: NVAR = 1 : Phase = det(URUP * ULUP)/ |det(URUP * ULUP)| * det(P) * det(R) det(Q)/ |det(R) det(Q)| NVAR = 2 : Phase = det(URUP * ULUP)/ |det(URUP * ULUP)| * det(P) * det^(R) det^(Q)/ |det(R) det(Q)| If STAB3 is selected the following tweak is applied We seperate D as D^+ * D^- where D^+ (D^-) contains the scales larger (smaller) then 1.0 Also, we use (DR^+^-1 UR^* UL^* DL^+^-1 + DR^- VR VL DL^-)^-1 = UL^* DL^+^-1 GRUP Dr^+^-1 UR^* .
[in] udvl Syntax ZGETRS(TRANS, N, NRHS, A, LDA, IPIV, B, LDB, INFO) Op(A) * X = B On output B = X
[in] udvr Syntax ZGETRS(TRANS, N, NRHS, A, LDA, IPIV, B, LDB, INFO) Op(A) * X = B On output B = X
Definition at line 33 of file cgr1.f90.
References cgrp(), qdrp_mod::qdrp_decompose(), and udv_wrap_mod::udv_wrap_pivot().
Referenced by cgr2_1(), global_mod::exchange_step(), global_mod::global_updates(), and main().
 !--------------------------------------------------------------------
 !
 !
 !--------------------------------------------------------------------
         Use udv_state_mod
 #if (defined(STAB2) || defined(STAB1)) && !defined(LOG)
         Use udv_wrap_mod
         Implicit None
         !Arguments.
         CLASS(UDV_State), INTENT(IN) :: udvl, udvr
         COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(INOUT) :: GRUP
         COMPLEX(Kind=Kind(0.d0)) :: PHASE
         INTEGER         :: NVAR
         interface
           subroutine cgrp(PHASE, GRUP, udvr, udvl)
             Use udv_state_mod
             CLASS(UDV_State), INTENT(IN) :: udvl, udvr
             COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Intent(OUT) :: GRUP
             COMPLEX (Kind=Kind(0.d0)), Intent(OUT) :: PHASE
           end subroutine cgrp
         end interface
         !Local
         TYPE(UDV_State) :: udvlocal
         COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Allocatable :: TPUP, TPUP1, TPUPM1
         INTEGER, Dimension(:), Allocatable :: IPVT
         COMPLEX (Kind=Kind(0.d0)) ::  ZDUP1, ZDDO1, ZDUP2, ZDDO2, Z1, ZUP, ZDO, alpha, beta
         Integer :: I,J, N_size, NCON, info
         Real (Kind=Kind(0.D0)) :: X, Xmax, sv
         if( .not. allocated(udvl%V) ) then
           !call projector cgr
           call cgrp(phase, grup, udvr, udvl)
           return
         endif
         if(udvl%side .ne. "L" .and. udvl%side .ne. "l" ) then
           write(*,*) "calling wrong decompose"
         endif
         if(udvr%side .ne. "R" .and. udvr%side .ne. "r" ) then
           write(*,*) "calling wrong decompose"
         endif
         n_size = udvl%Ndim
         ncon = 0
         alpha = 1.d0
         beta = 0.d0
         Allocate(tpup(n_size,n_size), tpup1(n_size,n_size), tpupm1(n_size,n_size), ipvt(n_size) )
         CALL udvlocal%alloc(n_size)
         !Write(6,*) 'In CGR', N_size
         CALL mmult(udvlocal%V, udvr%V, udvl%V)
         DO j = 1,n_size
             tpup(:,j) = udvr%D(:)*udvlocal%V(:,j)*udvl%D(j)
         ENDDO
         CALL zgemm('C', 'N', n_size, n_size, n_size, alpha, udvr%U(1,1), n_size, udvl%U(1,1), n_size, alpha, tpup, n_size)
         IF (nvar.EQ.1) THEN
            !WRITE(6,*) 'UDV of U + DR * V * DL'
            CALL udv_wrap_pivot(tpup,udvlocal%U,udvlocal%D,udvlocal%V,ncon,n_size,n_size)
            !CALL UDV(TPUP,UUP,DUP,VUP,NCON)
 !            CALL MMULT(TPUP,udvlocal%V, udvl%U)
            CALL zgemm('N', 'C', n_size, n_size, n_size, alpha, udvlocal%V(1,1), n_size, udvl%U(1,1), n_size, beta, tpup, n_size)
            !Do I = 1,N_size
            !   Write(6,*) DLUP(I)
            !enddo
            CALL inv  (tpup,tpupm1,zdup1)
            CALL mmult(tpup1, udvr%U, udvlocal%U)
            CALL zgetrf(n_size, n_size, tpup1, n_size, ipvt, info)
            z1 = zdup1
            Do i = 1, n_size
               IF (ipvt(i) .ne. i) THEN
                  z1 = -z1
               endif
               z1 = z1 * tpup1(i, i)
            enddo
         ELSE
            !WRITE(6,*) 'UDV of (U + DR * V * DL)^{*}'
            tpup1 = ct(tpup)
            CALL udv_wrap_pivot(tpup1, udvlocal%U, udvlocal%D, udvlocal%V, ncon,n_size,n_size)
            !CALL UDV(TPUP1,UUP,DUP,VUP,NCON)
            CALL zgemm('N', 'N', n_size, n_size, n_size, alpha, udvl%U(1,1), n_size, udvlocal%U, n_size, beta, tpupm1, n_size)
            CALL zgemm('N', 'C', n_size, n_size, n_size, alpha, udvr%U(1,1), n_size, udvlocal%V, n_size, beta, tpup1, n_size)
            CALL zgetrf(n_size, n_size, tpup1, n_size, ipvt, info)
            zdup2 = 1.d0
            do i = 1, n_size
               zdup2 = zdup2 * tpup1(i,i)
               IF (ipvt(i) .ne. i) THEN
                  zdup2 = -zdup2
               endif
            enddo
            tpup = tpupm1
            zdup1 = det_c(tpup, n_size)! Det destroys its argument
            z1 = zdup2/zdup1
         ENDIF
         DO j = 1, n_size
            sv = dble(udvlocal%D(j))
            x = abs(sv)
            if (j == 1)  xmax = x
            if ( x  < xmax ) xmax = x
            sv = 1.d0/sv
            DO i = 1, n_size
               udvlocal%U(j, i) = tpupm1(i, j) * sv
            ENDDO
         ENDDO
         call zgetrs('T', n_size, n_size, tpup1, n_size, ipvt, udvlocal%U, n_size, info)
         grup = transpose(udvlocal%U)
         phase = z1/abs(z1)
         CALL udvlocal%dealloc
         Deallocate(tpup,tpup1,tpupm1, ipvt )
 #else
         USE mymats
         USE qdrp_mod
         Implicit None
         !Arguments.
 !         COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(IN)   ::  URUP, VRUP, ULUP, VLUP
 !         COMPLEX(Kind=Kind(0.d0)), Dimension(:),   Intent(IN)   ::  DLUP, DRUP
         CLASS(UDV_State), INTENT(IN) :: udvl, udvr
         COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(INOUT) :: GRUP
         COMPLEX(Kind=Kind(0.d0)), Intent(INOUT) :: PHASE
         INTEGER         :: NVAR
         interface
           subroutine cgrp(PHASE, GRUP, udvr, udvl)
             Use udv_state_mod
             CLASS(UDV_State), INTENT(IN) :: udvl, udvr
             COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Intent(OUT) :: GRUP
             COMPLEX (Kind=Kind(0.d0)), Intent(OUT) :: PHASE
           end subroutine cgrp
         end interface
         !Local
         COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Allocatable ::  TPUP, RHS
         COMPLEX (Kind=Kind(0.d0)), Dimension(:) , Allocatable ::  DUP
         INTEGER, Dimension(:), Allocatable :: IPVT, VISITED
         COMPLEX (Kind=Kind(0.d0)) ::  alpha, beta, Z, DLJ
         Integer :: I, J, N_size, info, LWORK, next, L
         Real (Kind=Kind(0.D0)) :: X, Xmax, sv
         COMPLEX (Kind=Kind(0.d0)), allocatable, Dimension(:) :: TAU, WORK
         LOGICAL :: FORWRD
         if(udvl%side .ne. "L" .and. udvl%side .ne. "l" ) then
           write(*,*) "calling wrong decompose"
         endif
         if(udvr%side .ne. "R" .and. udvr%side .ne. "r" ) then
           write(*,*) "calling wrong decompose"
         endif
         if( .not. allocated(udvl%V) ) then
           !call projector cgr
           call cgrp(phase, grup,udvr, udvl)
           return
         endif
         n_size = udvl%ndim
         alpha = 1.d0
         beta = 0.d0
         Allocate(tpup(n_size,n_size), rhs(n_size, n_size), ipvt(n_size), tau(n_size), dup(n_size))
         !Write(6,*) 'In CGR', N_size
         ! can be inserted again once we are sure that we may assume that UR and UL stem from householder reflectors
 !        CALL ZGEMM('C', 'C', N_size, N_size, N_size, alpha, URUP, N_size, ULUP, N_size, alpha, TPUP, N_size)
         CALL zgemm('C', 'N', n_size, n_size, n_size, alpha, udvr%U, n_size, udvl%U, n_size, beta, rhs(1, 1), n_size)
         CALL mmult(tpup, udvr%V, udvl%V)
 #if !(defined(STAB3) || defined(LOG))
         DO j = 1,n_size
             tpup(:,j) = udvr%D(:) *tpup(:,j)*udvl%D(j)
         ENDDO
         tpup = tpup + rhs
 #else
 #if ! defined(LOG)
         !missuse DUP(I) as DR(I) for temporary storage
         !scales in D are assumed to be real and positive
         DO i = 1,n_size
           If( dble(udvr%D(i))<=1.d0 ) then
             dup(i)=udvr%D(i)
           else
             dup(i)=1.d0/udvr%D(i)
           endif
         ENDDO
         DO j = 1,n_size
           If( dble(udvl%D(j))<=1.d0) then
             dlj=udvl%D(j)
             DO i = 1,n_size
               If( dble(udvr%D(i))<=1.d0 ) then
                 tpup(i,j) = rhs(i,j)+udvr%D(i)*udvl%D(j)*tpup(i,j)
               else
                 tpup(i,j) = dup(i)*rhs(i,j) + dlj*tpup(i,j)
               endif
             ENDDO
           else
             dlj=1.d0/udvl%D(j)
             DO i = 1,n_size
               If( dble(udvr%D(i))<=1.d0 ) then
                 tpup(i,j) = dlj*rhs(i,j)+dup(i)*tpup(i,j)
               else
                 tpup(i,j) = rhs(i,j)/udvr%D(i)/udvl%D(j)+tpup(i,j)
               endif
             ENDDO
           endif
         ENDDO
 #else
         !missuse DUP(I) as DR(I) for temporary storage
         DO i = 1,n_size
           If( udvr%L(i)<=0.d0 ) then
             dup(i)=cmplx(exp(udvr%L(i)),0.d0,kind(0.d0))
           else
             dup(i)=cmplx(exp(-udvr%L(i)),0.d0,kind(0.d0))
           endif
         ENDDO
         DO j = 1,n_size
           If(udvl%L(j)<=0.d0) then
             dlj=cmplx(exp(udvl%L(j)),0.d0,kind(0.d0))
             DO i = 1,n_size
               If( udvr%L(i)<=0.d0 ) then
                 tpup(i,j) = rhs(i,j)+cmplx(exp(udvr%L(i)+udvl%L(j)),0.d0,kind(0.d0))*tpup(i,j)
               else
                 tpup(i,j) = dup(i)*rhs(i,j) + dlj*tpup(i,j)
               endif
             ENDDO
           else
             dlj=cmplx(exp(-udvl%L(j)),0.d0,kind(0.d0))
             DO i = 1,n_size
               If( udvr%L(i)<=0.d0 ) then
                 tpup(i,j) = dlj*rhs(i,j)+dup(i)*tpup(i,j)
               else
                 tpup(i,j) = cmplx(exp(-udvr%L(i)-udvl%L(j)),0.d0,kind(0.d0))*rhs(i,j)+tpup(i,j)
               endif
             ENDDO
           endif
         ENDDO
 #endif
 #endif
         ! calculate determinant of UR*UL
         ! as the D's are real and positive, they do not contribute the the phase of det so they can be ignored
         phase = conjg(det_c(rhs, n_size))
         phase = phase/abs(phase)
         ipvt = 0
         IF (nvar .NE. 1) THEN
             tpup = conjg(transpose(tpup))
         ENDIF
         call qdrp_decompose(n_size, udvl%N_part, tpup, dup, ipvt, tau, work, lwork)
         ALLOCATE(visited(n_size))
         ! Calculate the sign of the permutation from the pivoting. Somehow the format used by the QR decomposition of lapack
         ! is different from that of the LU decomposition of lapack
         visited = 0
         do i = 1, n_size
             if (visited(i) .eq. 0) then
                 next = i
                 l = 0
                 do while (visited(next) .eq. 0)
                  l = l + 1
                  visited(next) = 1
                  next = ipvt(next)
                 enddo
                 if(mod(l, 2) .eq. 0) then
                     phase = -phase
                 endif
             endif
         enddo
         !calculate the determinant of the unitary matrix Q and the upper triangular matrix R
         DO i = 1, n_size
             z = tau(i)
             IF(nvar .EQ. 1) THEN
                 phase = phase * tpup(i,i)/abs(tpup(i,i))
             ELSE
                 ! the diagonal should be real, but let's be safe....
                 phase = phase * conjg(tpup(i,i))/abs(tpup(i,i))
                 z = conjg(z) ! conjugate the elementary reflector
             ENDIF
             if (z .ne. cmplx(0.d0, 0.d0, kind=kind(0.d0))) then
             ! here we calculate the determinant of a single householder reflector: det(1 - tau * v v* ) = 1 - tau * v^* v
             ! In lapack the scalar tau and the vector v are scaled such that |tau|^2 |v|^2 = 2 Re(tau)
             ! The complete determinant det(Q) is the product of all reflectors. See http://www.netlib.org/lapack/lug/node128.html
                 x = abs(z)
                 z = 1.d0 - 2.d0 * (z/x) * (dble(z)/x)
                 phase = phase * z/abs(z)
             endif
         enddo
         IF(nvar .EQ. 1) then
             ! This is supposed to solve the system
             ! URUP U D V P^dagger ULUP G = 1
             ! initialize the rhs with CT(URUP)
             rhs = ct(udvr%U)
 #if (defined(STAB3) || defined(LOG))
             !scale RHS=R_+^-1*RHS
             do j=1,n_size
 #if !defined(LOG)
               if( dble(udvr%D(j)) > 1.d0 ) call zscal(n_size,1.d0/udvr%D(j),rhs(j,1),n_size)
 #else
               if( udvr%L(j) > 0.d0 ) call zscal(n_size,cmplx(exp(-udvr%L(j)),0.d0,kind(0.d0)),rhs(j,1),n_size)
 #endif
             enddo
 #endif
             ! RHS = U^dagger * RHS
             CALL zunmqr('L', 'C', n_size, n_size, n_size, tpup(1, 1), n_size, tau(1), rhs(1,1), n_size, work(1), lwork, info)
             DEALLOCATE(tau, work)
             !apply inverse of D to RHS from the left
             DO j = 1, n_size
                 sv = dble(dup(j))
                 x = abs(sv)
                 if (j == 1)  xmax = x
                 if ( x  < xmax ) xmax = x
                 DO i = 1, n_size
                     rhs(i,j) = rhs(i, j) / dup(i)
                 ENDDO
             ENDDO
             ! We solve the equation
             !  A * G = RHS for G with A = R * P^dagger * ULUP
             ! first we solve R *y = RHS. The solution is afterwards in RHS
             CALL ztrsm('L', 'U', 'N', 'N', n_size, n_size, alpha, tpup(1,1), n_size, rhs(1,1), n_size)
             ! apply permutation matrix
             forwrd = .false.
             CALL zlapmr(forwrd, n_size, n_size, rhs(1,1), n_size, ipvt(1))
 #if (defined(STAB3) || defined(LOG))
             !scale RHS=L_+^-1*RHS
             do j=1,n_size
 #if !defined(LOG)
               if( dble(udvl%D(j)) > 1.d0 ) call zscal(n_size,1.d0/udvl%D(j),rhs(j,1),n_size)
 #else
               if( udvl%L(j) > 0.d0 ) call zscal(n_size,cmplx(exp(-udvl%L(j)),0.d0,kind(0.d0)),rhs(j,1),n_size)
 #endif
             enddo
 #endif
             ! perform multiplication with ULUP and store in GRUP
             CALL zgemm('N', 'N', n_size, n_size, n_size, alpha, udvl%U(1, 1), n_size, rhs(1,1), n_size, beta, grup(1,1), n_size)
         ELSE
             ! This solves the system G * URUP * P * R^dagger * D * U^dagger * ULUP = 1
             ! RHS = ULUP * UUP
             rhs = udvl%U !CT(udvl%U)
 #if (defined(STAB3) || defined(LOG))
             !scale RHS=RHS*L_+^-1
             do j=1,n_size
 #if !defined(LOG)
               if( dble(udvl%D(j)) > 1.d0 ) call zscal(n_size,1.d0/udvl%D(j),rhs(1,j),1)
 #else
               if( udvl%L(j) > 0.d0 ) call zscal(n_size,cmplx(exp(-udvl%L(j)),0.d0,kind(0.d0)),rhs(1,j),1)
 #endif
             enddo
 #endif
             CALL zunmqr('R', 'N', n_size, n_size, n_size, tpup(1, 1), n_size, tau(1), rhs(1, 1), n_size, work(1), lwork, info)
             DEALLOCATE(tau, work)
             ! apply D^-1 to RHS from the right
             DO j = 1, n_size
                 sv = dble(dup(j))
                 x = abs(sv)
                 if (j == 1)  xmax = x
                 if ( x  < xmax ) xmax = x
                 sv = 1.d0/sv
                 DO i = 1, n_size
                     rhs(i, j) = rhs(i, j) * sv
                 ENDDO
             ENDDO
             ! We solve the equation
             ! G * A = RHS for G with A = URUP * P * R^dagger
             ! first we solve y * R^dagger = RHS
             CALL ztrsm('R', 'U', 'C', 'N', n_size, n_size, alpha, tpup(1, 1), n_size, rhs(1, 1), n_size)
             ! apply inverse permutation matrix
             forwrd = .false.
             CALL zlapmt(forwrd, n_size, n_size, rhs(1, 1), n_size, ipvt(1))
 #if (defined(STAB3) || defined(LOG))
             ! first scale RHS=RHS*R_+^-1
             do j=1,n_size
 #if !defined(LOG)
               if( dble(udvr%D(j)) > 1.d0 ) call zscal(n_size,1.d0/udvr%D(j),rhs(1,j),1)
 #else
               if( udvr%L(j) > 0.d0 ) call zscal(n_size,cmplx(exp(-udvr%L(j)),0.d0,kind(0.d0)),rhs(1,j),1)
 #endif
             enddo
 #endif
             ! perform multiplication with URUP
             CALL zgemm('N', 'C', n_size, n_size, n_size, alpha, rhs(1, 1), n_size, udvr%U(1,1), n_size, beta, grup(1, 1), n_size)
         ENDIF
         Deallocate(tpup, dup, ipvt, visited, rhs)
 #endif
cgrp()
subroutine cgrp (complex (kind=kind(0.d0)), intent(out) phase, complex (kind=kind(0.d0)), dimension(:,:), intent(out) GRUP, class(udv_state), intent(in) udvr, class(udv_state), intent(in) udvl)
Computes the Green's function in the projective implementation.
Author
ALF-project
Parameters
[out] PHASE
[out] GRUP
[in] udvr
[in] udvl
Definition at line 459 of file cgr1.f90.
Referenced by cgr(), and tau_p_mod::tau_p().
         Use udv_state_mod
         CLASS(UDV_State), INTENT(IN) :: udvl, udvr
         COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Intent(OUT) :: GRUP
         COMPLEX (Kind=Kind(0.d0)), Intent(OUT) :: phase
         COMPLEX (Kind=Kind(0.d0)), allocatable, Dimension(:,:) :: sMat, rMat
         INTEGER, allocatable :: ipiv(:)
         COMPLEX (Kind=Kind(0.d0)) :: alpha, beta
         INTEGER :: Ndim, N_part, info, n
         if((udvl%side .ne. "L") .and. (udvl%side .ne. "l") ) then
           write(*,*) "cgrp: udvl is not of type left"
           write(*,*) "cgrp: actual side is ",udvl%side
         endif
         if((udvr%side .ne. "R") .and. (udvr%side .ne. "r") ) then
           write(*,*) "cgrp: udvr is not of type right"
           write(*,*) "cgrp: actual side is ",udvr%side
         endif
         ndim = udvl%ndim
         n_part = udvl%n_part
         Allocate(smat(n_part,n_part), ipiv(n_part), rmat(n_part, ndim))
         ! Gr = Ur (Ul Ur)^-1 Ul
         ! Phase = 1 + Ur (Ul Ur)^-1 Ul
         ! Ul = udvl%U ^dag
         alpha=1.d0
         beta=0.d0
         call zgemm('C','N',n_part,n_part,ndim,alpha,udvl%U(1,1),ndim,udvr%U(1,1),ndim,beta,smat(1,1),n_part)
         ! ZGETRF computes an LU factorization of a general M-by-N matrix A
         ! using partial pivoting with row interchanges.
         call zgetrf(n_part, n_part, smat, n_part, ipiv, info)
         phase=1.d0
         Do n=1,n_part
           if (ipiv(n).ne.n) then
             phase = -phase * smat(n,n)/abs(smat(n,n))
           else
             phase =  phase * smat(n,n)/abs(smat(n,n))
           endif
         enddo
         rmat = conjg(transpose(udvl%U))
         call zgetrs('N', n_part, ndim, smat(1,1), n_part, ipiv, rmat(1,1), n_part, info)
         alpha=-1.d0
         call zgemm('N','N',ndim,ndim,n_part,alpha,udvr%U(1,1),ndim,rmat(1,1),n_part,beta,grup(1,1),ndim)
         do n=1,ndim
           grup(n,n)=grup(n,n)+cmplx(1.d0, 0.d0, kind(0.d0))
         enddo
         Deallocate(smat, rmat, ipiv)