ALF: cgr2_1.f90 File Reference
cgr2_1.f90 File Reference
Functions/Subroutines
subroutine scalematrix (M, D, c, LQ)
This function scales every Row of M with an entry from the vector D.
subroutine cgr2_1 (GRT0, GR00, GRTT, GR0T, U2, D2, V2, U1, D1, V1, LQ, NVAR)
Function/Subroutine Documentation
cgr2_1()
subroutine cgr2_1 (complex (kind=kind(0.d0)), dimension(lq,lq), intent(inout) GRT0, complex (kind=kind(0.d0)), dimension(lq,lq), intent(inout) GR00, complex (kind=kind(0.d0)), dimension(lq,lq), intent(inout) GRTT, complex (kind=kind(0.d0)), dimension(lq,lq), intent(inout) GR0T, complex (kind=kind(0.d0)), dimension(lq,lq), intent(in) U2, complex (kind=kind(0.d0)), dimension(lq), intent(in) D2, complex (kind=kind(0.d0)), dimension(lq,lq), intent(in) V2, complex (kind=kind(0.d0)), dimension(lq,lq), intent(in) U1, complex (kind=kind(0.d0)), dimension(lq), intent(in) D1, complex (kind=kind(0.d0)), dimension(lq,lq), intent(in) V1, integer, intent(in) LQ, integer, intent(in) NVAR)
Definition at line 35 of file cgr2_1.f90.
References cgr(), scalematrix(), and udv_wrap_mod::udv_wrap().
         !       B2 = U2*D2*V2 is right (i.e. from time slice 0 to tau) propagation to time tau
         !       B1 = V1*D1*U1 is left  (i.e. from time slice Ltrot to tau) propagation to time tau
         !Calc:      (  1   B1 )^-1       ( G00    G0T )
         !           (-B2   1  )     ==   ( GT0    GTT )
         !
         !       G00 = (1 + B1*B2)^-1   G0T = -(1 -  G00 )*B2^-1
         !       GT0  =   B2 * G00      GTT =  (1 + B2*B1)^-1
         !  Here you want to compute  G00, G0T, GT0 and GTT just by involving LQ x LQ matrix operations.
         !  If NVAR == 1  then the  large scales are in D1
         !  If NVAR == 2  then the  large scales are in D2
         Use mymats
         USe udv_wrap_mod
         Implicit none
         interface
            SUBROUTINE cgr(Z,NVAR, GRUP, URUP,DRUP,VRUP, ULUP,DLUP,VLUP)
              COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(In) ::  URUP, VRUP, ULUP, VLUP
              COMPLEX(Kind=Kind(0.d0)), Dimension(:), Intent(In)   ::  DLUP, DRUP
              COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(INOUT) :: GRUP
              COMPLEX(Kind=Kind(0.d0)) :: Z
            END SUBROUTINE CGR
         end Interface
         !  Arguments
         Integer,  intent(in) :: LQ, NVAR
         Complex (Kind=Kind(0.d0)), intent(in)    :: U1(LQ,LQ), V1(LQ,LQ), U2(LQ,LQ), V2(LQ,LQ)
         Complex (Kind=Kind(0.d0)), intent(in)    :: D2(LQ), D1(LQ)
         Complex (Kind=Kind(0.d0)), intent(inout) :: GRT0(LQ,LQ), GR0T(LQ,LQ), GR00(LQ,LQ), GRTT(LQ,LQ)
         ! Local::
         Complex  (Kind=Kind(0.d0)) :: HLP1(LQ,LQ), HLP2(LQ,LQ), U(LQ,LQ), D(LQ), V(LQ,LQ)
         Complex  (Kind=Kind(0.d0)) :: Z, Z1, Z2
         Real     (Kind=Kind(0.d0)) :: Xmax, Xmin, Xmax1, Xmax2, Xmean
         Integer                :: I, J, NCON, NVAR1
         Complex  (Kind=Kind(0.d0)) :: V2inv(LQ,LQ), V1inv(LQ,LQ), alpha, beta
         ncon = 0
         Call inv( v2, v2inv, z2)
         CALL inv( v1, v1inv, z1)
         alpha = 1.d0
         beta = 0.d0
         CALL zgemm('C', 'N', lq, lq, lq, alpha, u1, lq, u1, lq, beta, hlp2, lq)
         CALL zlaset('A', lq, lq, alpha, beta, hlp1, lq)
         xmax = 0.d0
         CALL compare(hlp1, hlp2, xmax, xmean)
         CALL zgemm('C', 'N', lq, lq, lq, alpha, u2, lq, u2, lq, beta, hlp2, lq)
         CALL zlaset('A', lq, lq, alpha, beta, hlp1, lq)
         xmax1 = 0.d0
         CALL compare(hlp1, hlp2, xmax1, xmean)
         Write(77,*) "Cgr2_1  V1inv V2inv : ", xmax, xmax1
 !!$        Xmax = 0.d0
 !!$        do  I = 1,LQ
 !!$           do j = 1,LQ
 !!$              X = sqrt(dble(V1(i,j)*conjg(V1(i,j))))
 !!$              if (X > Xmax) Xmax = X
 !!$           enddo
 !!$        enddo
 !!$        Write(77,*) 'In cgr2_1 Xmax V1: ', Xmax, Z2
 !!$        do  I = 1,LQ
 !!$           do j = 1,LQ
 !!$              X = sqrt(dble(V2(i,j)*conjg(V2(i,j))))
 !!$              if (X > Xmax) Xmax = X
 !!$           enddo
 !!$        enddo
 !!$        Write(77,*) 'In cgr2_1 Xmax V2: ', Xmax, Z1
         ! Compute G00
         ! G00 = (1 + B1*B2)^-1 = (1 + V1 D1 U1 U2 D2 V2 )^-1 =
         !                      = ( V1  (   V1^-1 V2^-1 +  D1 U1 U2 D2 ) V2 )^-1 =
         !                      = V2^-1 ( (V2 V1)^-1 + D1 U1 U2 D2     )^-1 V1^-1
         Call mmult(hlp1,v1inv,v2inv)
         Call mmult(hlp2,u1,u2)
         DO j = 1,lq
             hlp2(:,j) = d1(:) * hlp2(:, j) * d2(j) + hlp1(:,j)
         ENDDO
         xmax1 = maxval(dble(d1))
         xmax2 = maxval(dble(d2))
         nvar1 = 1
         If ( xmax2 > xmax1) nvar1 = 2
         If (nvar1 == 1) then
            !  V2^-1 (UDV  )^-1 V1^-1 =  V2^-1 V^-1 D^-1 U^-1 V1^-1
            Call udv_wrap(hlp2, u, d, v, ncon)
            CALL inv  (v,hlp2 ,z   )
            CALL mmult(hlp1,v2inv,hlp2)
            CALL zgemm('C', 'N', lq, lq, lq, alpha, u, lq, v1inv, lq, beta, hlp2, lq)
         else
            !  V2^-1 (UDV  )^(-1,*) V1^-1 =  V2^-1 U  D^-1 V^(-1,*) V1^-1
            hlp1 = ct(hlp2)
            Call udv_wrap(hlp1, u, d, v, ncon)
            CALL inv (v, hlp1, z)
            CALL zgemm('C', 'N', lq, lq, lq, alpha, hlp1, lq, v1inv, lq, beta, hlp2, lq)
            Call mmult(hlp1, v2inv, u)
         endif
         Call scalematrix(hlp1, d, .false., lq)
         CALL mmult(gr00,hlp1,hlp2)
         ! Compute G0T
         ! G00 = (1 + B1*B2)^-1   G0T = -(1 -  (1 + B1*B2)^-1 )*B2^-1              =
         !                            = -( 1 +  B1*B2 - 1)  (1 + B1*B2)^-1 * B2^-1 =
         !                            = - B1 * B2 (1 + B1*B2)^-1 * B2^-1           =
         !                            = -( B2 ( 1+ B1*B2) * B2^-1 B1^-1)^-1        =
         !                            = -( B2 ( 1+ B1*B2) * (B1 B2)^-1)^-1         =
         !                            = -( B2 ( (B1 B2)^-1  + 1 ) )^-1             =
         !                            = -( B1^-1   +   B2)^-1                      =
         !                       -G0T*=  ( B1*^-1  +  B2*)^-1                      =
         !                            =  ( V1*^-1 D1*^-1 U1  + V2* D2* U2*)^-1     =
         !                            =  ( V1*^-1 (  D1*^-1 U1 U2 + V1* V2* D2* ) U2* )^-1 =
         !                            =  U2 ( D1*^-1 (U1 U2) + ( V2 V1)* D2* )^-1 V1*
         !                            =  U2 ( D1*^-1 (U1 U2) + ( V2 V1)* D2* )^-1 V1*
         !       B2 = U2*D2*V2
         !       B1 = V1*D1*U1
         xmax2 = maxval(dble(1.d0/d1))
         xmax1 = maxval(dble(d2))
         nvar1 = 1
         If (xmax2  > xmax1)  nvar1 = 2
         Call  mmult(hlp1,u1,u2)
 !TODO: Consider benchmarking wether it is beneficial to interchange loops. Here it is saving divisions vs. proper mem access
         DO j = 1,lq
            hlp1(:, j) =  hlp1(:,j)/conjg(d1(:))
         ENDDO
         CALL zgemm('C', 'C', lq, lq, lq, alpha, v1, lq, v2, lq, beta, hlp2, lq)
         DO j = 1,lq
             hlp2(:, j) = hlp1(:,j) + hlp2(:,j) * conjg(d2(j))
         ENDDO
         ncon = 0
         IF ( nvar1 == 1 ) then
            !  UDV of HLP2
            !  -G0T*= U2 V^-1 D^-1 U* V1*
            CALL udv_wrap(hlp2,u,d,v,ncon)
            CALL inv(v,hlp2,z)
            CALL mmult (v, v1, u) ! V = V1 * U, reuse of the variable V as temporary storage
            Call mmult(hlp1,u2,hlp2)
         else
            !  UDV of HLP2*
            !  -G0T*= U2 (U D V)*^-1 V1* =  U2 U D*^-1 V*^-1 V1*
            hlp1 = ct(hlp2)
            CALL udv_wrap(hlp1,u,d,v,ncon)
            CALL inv(v,hlp2,z)
            Call mmult(v,v1,hlp2)
            CALL mmult (hlp1, u2, u)
         ENDIF
         CALL scalematrix(hlp1, (-d), .false., lq)
         CALL zgemm('N', 'C', lq, lq, lq, alpha, v, lq, hlp1, lq, beta, gr0t, lq)
         ! Compute GT0
         ! GT0  =   B2 * G00   =   (  (   1   + B1* B2) * B2^-1  )^-1  =   ( B2^-1   + B1)^-1 =
         !                     =   (V2^-1 D2^-1 U2^-1  + V1 D1 U1)^-1 =
         !                     =   ( (V2^-1 D2^-1 U2^-1 U1^-1  + V1 D1 ) U1  )^-1 =
         !                     =   U1^-1 (  ( D2^-1 (U1 U2)^-1  + V2*V1 D1 )   )^-1 V2
         xmax2 = maxval(dble(1.d0/d2))
         xmax1 = maxval(dble(d1))
         nvar1 = 1
         If (xmax2 > xmax1 ) nvar1 = 2
         !Write(6,*) "CGR2_1: NVAR,NVAR1 ", NVAR, NVAR1
         CALL zgemm('C', 'C', lq, lq, lq, alpha, u2, lq, u1, lq, beta, hlp1, lq)
 !TODO: Consider benchmarking wether it is beneficial to interchange loops. Here it is saving divisions vs. proper mem access
         DO j = 1,lq
            hlp1(:, j) =  hlp1(:,j)/d2(:)
         ENDDO
         Call mmult(hlp2,v2,v1)
         DO j = 1,lq
             hlp2(:, j) = hlp1(:,j) + hlp2(:,j) * d1(j)
         ENDDO
         ncon = 0
         IF ( nvar1 == 1 ) then
            !  UDV of HLP2
            CALL udv_wrap(hlp2,u,d,v,ncon)
            CALL mmult (hlp1, v, u1)
            CALL inv(hlp1,hlp2,z)
            CALL zgemm('C', 'N', lq, lq, lq, alpha, u, lq, v2, lq, beta, v, lq)
         else
            !UDV of HLP2^*
            hlp1 = ct(hlp2)
            CALL udv_wrap(hlp1,u,d,v,ncon)
            CALL zgemm('C', 'N', lq, lq, lq, alpha, u1, lq, u, lq, beta, hlp2, lq)
            CALL inv(v,hlp1,z)
            CALL zgemm('C', 'N', lq, lq, lq, alpha, hlp1, lq, v2, lq, beta, v, lq)
         ENDIF
         CALL scalematrix(hlp2, d, nvar .ne. 1, lq)
         xmin = minval(abs(dble(d)))
         Call mmult (grt0, hlp2, v)
         Write(6,*) 'Cgr2_1 T0, Xmin: ', xmin
         !Compute GRTT
         z  = cmplx(1.d0,0.d0,kind=kind(0.d0))
         z1 = cmplx(1.d0,0.d0,kind=kind(0.d0))
         CALL cgr(z,nvar,grtt, u2,d2,v2, u1,d1,v1)
scalematrix()
subroutine scalematrix (complex (kind = kind(0.d0)), dimension(lq,lq), intent(inout) M, complex (kind = kind(0.d0)), dimension(lq), intent(in) D, logical, intent(in) c, integer, intent(in) LQ)
This function scales every Row of M with an entry from the vector D.
Author
Florian Goth
Note
GCC does not by itself pull out the division by D from the inner loop in every other expression that I tried, therefore this explicit loop construct is necessary.
Parameters
[in,out] M The matrix whose rows we scale
[in] D A vector with the scaling factors
[in] A boolean variable wether we do a ccomplex conjugate on D
[in] LQ The length of the vectors and the dimension of M
Definition at line 19 of file cgr2_1.f90.
Referenced by cgr2_1().
         Integer, Intent(In) :: LQ
         Integer :: J
         Complex (Kind = Kind(0.D0)), Intent(Inout) :: M(LQ,LQ)
         Complex (Kind = Kind(0.D0)), Intent(In) :: D(LQ)
         Complex (Kind = Kind(0.D0)) :: Z
         Logical, Intent(In) :: c
         DO j = 1,lq
             z = 1.d0/d(j)
             If (c) z = conjg(z)
             m(:,j) = m(:,j)*z
         ENDDO