ALF: main.f90 File Reference
main.f90 File Reference
Functions/Subroutines
program main
Reads in the VAR_QMC namelist fro the file parameters, calls Ham_set and carries out the sweeps.
Function/Subroutine Documentation
main()
program main ()
Reads in the VAR_QMC namelist fro the file parameters, calls Ham_set and carries out the sweeps.
Author
ALF-project If the program is compiled with the Tempering flag on, then the VAR_TEMP namelist will also be read in.
  The parameters in the VAR_QMC namelist read
Parameters
Nwrap Integer
  Number of time slices between stabilization (QR)
  Has to be specified.
Nsweep Integer
  Number of sweeps per bin
  Has to be specified.
Nbin Integer
  Number of bins
  Has to be specified.
Ltau Integer
  If Ltau=1 time displaced correlations will be measured.
  Has to be specified.
LOBS_ST LOBS_EN Integer
  Time slice interval for measurements
  Default values:  LOBS_ST = Thtrot +1,  LOBS_ST = Ltrot - Thtrot
  Note that Thtrot corresponds to the projection time in units of
  the time step  and is equal to zero for the finite temperature code.
CPU_MAX Real
  Available Wallclock time. The program will carry as many bins as
  possible during this time
  If not specified the program will stop after NBIN bins are calculated
Propose_S0 Logical
  If true, spin flips are proposed with probability exp(-S_0(C')). See documentation.
  Default:  Propose_S0=.false.
Global_moves Logical
  If true, global moves will be carried out.
  Default: Global_moves=.false.
N_Global Integer
  Number of global moves per  sequential sweep.
  Default: N_Global=0
Global_tau_moves Logical
  If true, global moves on a given time slice will be carried out
  Default: Global_tau_moves=.false.
N_Global_tau Integer
  Number of global_tau moves that will be carried out per time-slice.
  Default: N_Global_tau=0
Nt_sequential_start Integer
Nt_sequential_end Integer
 Interval over which one will carry out sequential updating on a single time slice.
 Default: Nt_sequential_start = 1  Nt_sequential_end=size(OP_V,1)). This default is
 automatically if Global_tau_moves=.false.
Definition at line 113 of file main.f90.
References hamiltonian::alloc_obs(), cgr(), control::control_init(), control::control_precisiong(), control::control_precisionp(), control::control_print(), global_mod::exchange_step(), fields_mod::fields_init(), global_mod::global_tempering_init_obs(), global_mod::global_tempering_pr(), global_mod::global_tempering_setup(), global_mod::global_updates(), hamiltonian::group_comm, hamiltonian::ham_set(), hamiltonian::hamiltonian_set_nsigma(), hop_mod::hop_mod_init(), hop_mod::hop_mod_symm(), hamiltonian::init_obs(), hamiltonian::ltrot, control::make_truncation(), hamiltonian::n_fl, hamiltonian::n_sun, hamiltonian::ndim, hamiltonian::nsigma, hamiltonian::obser(), operator_mod::op_phase(), hamiltonian::op_v, hamiltonian::pr_obs(), hamiltonian::projector, hamiltonian::symm, tau_m_mod::tau_m(), tau_p_mod::tau_p(), hamiltonian::thtrot, hamiltonian::wf_l, hamiltonian::wf_r, wrapgr_mod::wrapgr_alloc(), wrapgr_mod::wrapgr_dealloc(), wrapgr_mod::wrapgrdo(), wrapgr_mod::wrapgrup(), wrapul(), wrapur(), and hop_mod::zero.