ALF: observables Module Reference
observables Module Reference
This module defines the Obser_Vec and Obser_Latt types and provides
routine to initialize them and to print out the bins.
Data Types
type obser_latt
type obser_vec
Functions/Subroutines
subroutine obser_latt_make (Obs, Ns, Nt, No, Filename)
subroutine obser_latt_init (Obs)
subroutine obser_vec_make (Obs, N, Filename)
subroutine obser_vec_init (Obs)
subroutine print_bin_latt (Obs, Latt, dtau, Group_Comm)
subroutine print_bin_vec (Obs, Group_Comm)
Detailed Description
This module defines the Obser_Vec and Obser_Latt types and provides
routine to initialize them and to print out the bins.
Author
ALF-project
Function/Subroutine Documentation
obser_latt_init()
subroutine observables::obser_latt_init (type (obser_latt), intent(inout) Obs)
Definition at line 86 of file observables_mod.f90.
Referenced by hamiltonian::init_obs().
            Implicit none
            type(obser_latt), intent(INOUT) :: obs
            obs%Obs_Latt  = cmplx(0.d0,0.d0,kind(0.d0))
            obs%Obs_Latt0 = cmplx(0.d0,0.d0,kind(0.d0))
            obs%N         = 0
            obs%Ave_Sign  = 0.d0
obser_latt_make()
subroutine observables::obser_latt_make (type (obser_latt), intent(inout) Obs, integer, intent(in) Ns, integer, intent(in) Nt, integer, intent(in) No, character (len=64), intent(in) Filename)
Definition at line 75 of file observables_mod.f90.
Referenced by hamiltonian::alloc_obs().
            Implicit none
            type(obser_latt), intent(INOUT) :: obs
            Integer, Intent(IN)             :: Ns,Nt,No
            Character (len=64), Intent(IN)  :: Filename
            Allocate (obs%Obs_Latt (ns,nt,no,no))
            Allocate (obs%Obs_Latt0(no)         )
            obs%File_Latt = filename
obser_vec_init()
subroutine observables::obser_vec_init (type (obser_vec), intent(inout) Obs)
Definition at line 107 of file observables_mod.f90.
Referenced by global_mod::global_tempering_init_obs(), and hamiltonian::init_obs().
            Implicit none
            type(obser_vec), intent(INOUT) :: obs
            obs%Obs_vec = cmplx(0.d0,0.d0,kind(0.d0))
            obs%N       = 0
            obs%Ave_Sign= 0.d0
obser_vec_make()
subroutine observables::obser_vec_make (type (obser_vec), intent(inout) Obs, integer, intent(in) N, character (len=64), intent(in) Filename)
Definition at line 97 of file observables_mod.f90.
Referenced by hamiltonian::alloc_obs(), and global_mod::global_tempering_setup().
            Implicit none
            type(obser_vec), intent(INOUT) :: obs
            Integer, Intent(IN)             :: N
            Character (len=64), Intent(IN)  :: Filename
            Allocate (obs%Obs_vec(n))
            obs%File_Vec = filename
print_bin_latt()
subroutine observables::print_bin_latt (type (obser_latt), intent(inout) Obs, type (lattice), intent(in) Latt, real (kind=kind(0.d0)), intent(in) dtau, integer, intent(in) Group_Comm)
Definition at line 117 of file observables_mod.f90.
Referenced by hamiltonian::pr_obs().
            Use lattices_v3
 #ifdef MPI
            Use mpi
 #endif
            Implicit none
            type(obser_latt),        Intent(Inout)   :: obs
            type(lattice),           Intent(In)      :: latt
            Real (Kind=Kind(0.d0)),   Intent(In)      :: dtau
            Integer,                  Intent(In)      :: Group_Comm
            ! Local
            Integer :: Ns,Nt, Norb, no, no1, I , Ntau
            Complex (Kind=Kind(0.d0)), allocatable :: Tmp(:,:,:,:)
            Real    (Kind=Kind(0.d0))              :: x_p(2)
            Complex (Kind=Kind(0.d0))              :: Sign_bin
            Character (len=64)            :: File_pr,  File_suff
 #ifdef MPI
            Complex (Kind=Kind(0.D0)), allocatable :: Tmp1(:)
            Complex (Kind=Kind(0.d0)) :: Z
            Real    (Kind=Kind(0.d0)) :: X
            Integer         :: Ierr, Isize, Irank
            INTEGER         :: irank_g, isize_g, igroup
            CALL mpi_comm_size(mpi_comm_world,isize,ierr)
            CALL mpi_comm_rank(mpi_comm_world,irank,ierr)
            call mpi_comm_rank(group_comm, irank_g, ierr)
            call mpi_comm_size(group_comm, isize_g, ierr)
            igroup           = irank/isize_g
 #endif
            ns    = Size(obs%Obs_Latt,1)
            ntau  = Size(obs%Obs_Latt,2)
            norb  = Size(obs%Obs_Latt,3)
            if ( .not. (latt%N  == ns ) ) then
               Write(6,*) 'Error in Print_bin'
               stop
            endif
            If (ntau == 1) then
               file_suff ="_eq"
            else
               file_suff  ="_tau"
            endif
            file_pr  = file_add(obs%File_Latt,file_suff )
            Allocate (tmp(ns,ntau,norb,norb))
            obs%Obs_Latt  =   obs%Obs_Latt /dble(obs%N   )
            obs%Obs_Latt0 =   obs%Obs_Latt0/dble(obs%N*ns*ntau)
            obs%Ave_sign  =   obs%Ave_Sign /dble(obs%N   )
 #if defined(MPI)
            i = ns*ntau*norb*norb
            tmp = cmplx(0.d0, 0.d0, kind(0.d0))
            CALL mpi_reduce(obs%Obs_Latt,tmp,i,mpi_complex16,mpi_sum, 0,group_comm,ierr)
            obs%Obs_Latt = tmp/dble(isize_g)
            i = 1
            x = 0.d0
            CALL mpi_reduce(obs%Ave_sign,x,i,mpi_real8,mpi_sum, 0,group_comm,ierr)
            obs%Ave_sign = x/dble(isize_g)
            i = norb
            Allocate(tmp1(norb))
            tmp1 = cmplx(0.d0,0.d0,kind(0.d0))
            CALL mpi_reduce(obs%Obs_Latt0,tmp1,i,mpi_complex16,mpi_sum, 0,group_comm,ierr)
            obs%Obs_Latt0 = tmp1/dble(isize_g)
            Deallocate(tmp1)
            If (irank_g == 0 ) then
 #endif
 #if defined(TEMPERING)
               write(file_pr ,'(A,I0,A,A,A)') "Temp_",igroup,"/",trim(obs%File_Latt),trim(file_suff )
 #endif
               do nt = 1,ntau
                  do no = 1,norb
                     do no1 = 1,norb
                        Call  fourier_r_to_k(obs%Obs_Latt(:,nt,no,no1), tmp(:,nt,no,no1), latt)
                     enddo
                  enddo
               enddo
               Open (unit=10,file=file_pr, status="unknown",  position="append")
               If ( ntau == 1 ) then
                  Write(10,*) obs%Ave_sign,norb,latt%N
               else
                  Write(10,*) obs%Ave_sign,norb,latt%N, ntau, dtau
               endif
               Do no = 1,norb
                  Write(10,*)  obs%Obs_Latt0(no)
               enddo
               do i = 1,latt%N
                  x_p = dble(latt%listk(i,1))*latt%b1_p + dble(latt%listk(i,2))*latt%b2_p
                  Write(10,*) x_p(1), x_p(2)
                  Do nt = 1,ntau
                     do no = 1,norb
                        do no1 = 1,norb
                           Write(10,*) tmp(i,nt,no,no1)
                        enddo
                     enddo
                  enddo
               enddo
               close(10)
 #if defined(MPI)
            Endif
 #endif
            deallocate (tmp)
print_bin_vec()
subroutine observables::print_bin_vec (type (obser_vec), intent(inout) Obs, integer, intent(in) Group_Comm)
Definition at line 229 of file observables_mod.f90.
Referenced by global_mod::global_tempering_pr(), and hamiltonian::pr_obs().
 #ifdef MPI
            Use mpi
 #endif
            Implicit none
            type(obser_vec), intent(Inout) :: obs
            Integer, INTENT(IN)  :: Group_Comm
            ! Local
            Integer :: I
            Character (len=64)             :: File_pr, File_suff
 #ifdef MPI
            Integer        :: Ierr, Isize, Irank, No
            INTEGER        :: irank_g, isize_g, igroup
            Complex  (Kind=Kind(0.d0)), allocatable :: Tmp(:)
            Real     (Kind=Kind(0.d0)) :: X
            CALL mpi_comm_size(mpi_comm_world,isize,ierr)
            CALL mpi_comm_rank(mpi_comm_world,irank,ierr)
            call mpi_comm_rank(group_comm, irank_g, ierr)
            call mpi_comm_size(group_comm, isize_g, ierr)
            igroup           = irank/isize_g
 #endif
            obs%Obs_vec  = obs%Obs_vec /dble(obs%N)
            obs%Ave_sign = obs%Ave_sign/dble(obs%N)
            file_suff ="_scal"
            file_pr = file_add(obs%File_Vec,file_suff)
 #if defined(MPI)
            no = size(obs%Obs_vec, 1)
            Allocate (tmp(no) )
            tmp = cmplx(0.d0,0.d0,kind(0.d0))
            CALL mpi_reduce(obs%Obs_vec,tmp,no,mpi_complex16,mpi_sum, 0,group_comm,ierr)
            obs%Obs_vec = tmp/dble(isize_g)
            deallocate (tmp )
            i = 1
            x = 0.d0
            CALL mpi_reduce(obs%Ave_sign,x,i,mpi_real8,mpi_sum, 0,group_comm,ierr)
            obs%Ave_sign = x/dble(isize_g)
            if (irank_g == 0 ) then
 #endif
 #if defined(TEMPERING)
               write(file_pr,'(A,I0,A,A,A)') "Temp_",igroup,"/",trim(obs%File_Vec),trim(file_suff)
 #endif
               Open (unit=10,file=file_pr, status="unknown",  position="append")
               WRITE(10,*) size(obs%Obs_vec,1)+1, (obs%Obs_vec(i), i=1,size(obs%Obs_vec,1)), obs%Ave_sign
               close(10)
 #if defined(MPI)
            endif
 #endif