ALF: operator_mod Module Reference
operator_mod Module Reference
Defines the Operator type, and provides a number of operations on this type.
Data Types
type operator
Functions/Subroutines
subroutine op_phase (Phase, OP_V, Nsigma, N_SUN)
calculate the phase of a given set of operators and HS fields.
pure subroutine op_make (Op, N)
Set up some data of the operator.
pure subroutine op_clear (Op, N)
subroutine op_set (Op)
pure subroutine op_exp (g, Op, Mat)
This calculates the exponentiated operator and returns a full matrix.
subroutine op_mmultl (Mat, Op, spin, Ndim, cop)
Out Mat = Mat*exp(spin*Op)
subroutine op_mmultr (Mat, Op, spin, Ndim, cop)
Out Mat = exp(spin*Op)*Mat.
subroutine op_wrapup (Mat, Op, spin, Ndim, N_Type)
subroutine op_wrapdo (Mat, Op, spin, Ndim, N_Type)
Detailed Description
Defines the Operator type, and provides a number of operations on this type.
Author
ALF-project
Function/Subroutine Documentation
op_clear()
pure subroutine operator_mod::op_clear (type (operator), intent(inout) Op, integer, intent(in) N)
Definition at line 198 of file Operator.f90.
Referenced by predefined_structures::predefined_trialwavefunction().
     Implicit none
     type(operator), intent(INOUT) :: op
     Integer, Intent(IN) :: N
     Deallocate (op%O, op%U, op%E, op%P )
     If ( op%type == 1 .or. op%type == 2 ) deallocate (  op%M_exp, op%E_exp)
op_exp()
pure subroutine operator_mod::op_exp (complex (kind=kind(0.d0)), intent(in) g, type (operator), intent(in) Op, complex (kind=kind(0.d0)), dimension(:,:), intent(out) Mat)
This calculates the exponentiated operator and returns a full matrix.
Author
The ALF Project contributors
Parameters
[in] g
[in] Op
[out] Mat The full matrix of the exponentiated operator.
Definition at line 340 of file Operator.f90.
Referenced by op_set().
     Implicit none
     type(operator), Intent(IN)  :: op
     Complex (Kind=Kind(0.d0)), Dimension(:,:), INTENT(OUT) :: Mat
     Complex (Kind=Kind(0.d0)), INTENT(IN) :: g
     Complex (Kind=Kind(0.d0)) :: Z, Z1, y, t
     Complex (Kind=Kind(0.d0)), allocatable, dimension(:,:) :: c
     Integer :: n, j, I, iters
     iters = op%N
     mat = cmplx(0.d0, 0.d0, kind(0.d0))
     if (op%diag) then
       Do n = 1, iters
         mat(n,n)=exp(g*op%E(n))
       enddo
     else
       Allocate (c(iters, iters))
       c = 0.d0
       Do n = 1, iters
         z = exp(g*op%E(n))
         do j = 1, iters
             z1 = z*conjg(op%U(j,n))
             do i = 1, iters
                ! This performs Kahan summation so as to improve precision.
                y = z1 * op%U(i, n) - c(i, j)
                t = mat(i, j) + y
                c(i, j) = (t - mat(i,j)) - y
                mat(i, j) = t
                !  Mat(I, J) = Mat(I, J) + Z1 * Op%U(I, n)
             enddo
             ! Mat(1:iters, J) = Mat(1:iters, J) + Z1 * Op%U(1:iters, n)
          enddo
       enddo
       Deallocate(c)
     endif
op_make()
pure subroutine operator_mod::op_make (type (operator), intent(inout) Op, integer, intent(in) N)
Set up some data of the operator.
Author
Parameters
[in,out] Op
[in] N
Definition at line 177 of file Operator.f90.
Referenced by hamiltonian::ham_v(), and predefined_structures::predefined_hopping().
     Implicit none
     type(operator), intent(INOUT) :: op
     Integer, Intent(IN) :: N
     Allocate (op%O(n,n), op%U(n,n), op%E(n), op%P(n) )
     ! F.F.A  Op%M_exp and Op%E_exp are allocated  in Op_set once the type is available.
     op%O = cmplx(0.d0, 0.d0, kind(0.d0))
     op%U = cmplx(0.d0, 0.d0, kind(0.d0))
     op%E = 0.d0
     op%P = 0
     op%N = n
     op%N_non_zero = n
     op%g     = cmplx(0.d0,0.d0, kind(0.d0))
     op%alpha = cmplx(0.d0,0.d0, kind(0.d0))
     op%diag  = .false.
     op%type = 0
op_mmultl()
subroutine operator_mod::op_mmultl (complex (kind=kind(0.d0)), dimension (:,:), intent(inout) Mat, type (operator), intent(in) Op, integer, intent(in) spin, integer Ndim, character, intent(in) cop)
Out Mat = Mat*exp(spin*Op)
Author
Parameters
[in,out] Mat
[in] Op The Operator that we exponentiate
[in] spin The spin direction that we consider
[in] Ndim The dimension of the matrix Mat
Definition at line 390 of file Operator.f90.
Referenced by tau_m_mod::proprm1().
     Implicit none
     Integer :: Ndim
     type(operator) , INTENT(IN)   :: op
     Complex (Kind=Kind(0.d0)), INTENT(INOUT) :: Mat (:,:)
     Integer, INTENT(IN)   :: spin
     Character, Intent(IN) :: cop
     ! Local
     Integer :: I, N1, N2
     n1=size(mat,1)
     n2=size(mat,2)
     ! In  Mat
     ! Out Mat = Mat*exp(spin*Op)
     ! quick return if possible
     if ( abs(op%g) < 1.d-12 ) return
     if ( op%diag ) then
       do i=1,op%N
         if ( cop == 'c' .or. cop =='C' ) then
           call zscal(n1,conjg(op%E_exp(i,spin)),mat(1,op%P(i)),1)
         else
           call zscal(n1,op%E_exp(i,spin),mat(1,op%P(i)),1)
         endif
       enddo
     else
       call zslgemm('r',cop,op%N,n1,n2,op%M_exp(:,:,spin),op%P,mat)
     endif
op_mmultr()
subroutine operator_mod::op_mmultr (complex (kind=kind(0.d0)), dimension (:,:), intent(inout) Mat, type (operator), intent(in) Op, integer, intent(in) spin, integer Ndim, character, intent(in) cop)
Out Mat = exp(spin*Op)*Mat.
Author
Parameters
[in,out] Mat
[in] Op The Operator that we exponentiate
[in] spin The spin direction that we consider
[in] Ndim The dimension of the matrix Mat
Definition at line 435 of file Operator.f90.
Referenced by tau_m_mod::propr().
     Implicit none
     Integer :: Ndim
     type(operator) , INTENT(IN )   :: op
     Complex (Kind=Kind(0.d0)), INTENT(INOUT) :: Mat (:,:)
     Integer, INTENT(IN )   :: spin
     Character, Intent(IN) :: cop
     ! Local
     Integer :: I, N1, N2
     n1=size(mat,1)
     n2=size(mat,2)
     ! In  Mat
     ! Out Mat = exp(spin*Op)*Mat
     ! quick return if possible
     if ( abs(op%g) < 1.d-12 ) return
     if ( op%diag ) then
       do i=1,op%N
         if ( cop == 'c' .or. cop =='C' ) then
           call zscal(n2,conjg(op%E_exp(i,spin)),mat(op%P(i),1),n1)
         else
           call zscal(n2,op%E_exp(i,spin),mat(op%P(i),1),n1)
         endif
       enddo
     else
       call zslgemm('L',cop,op%N,n1,n2,op%M_exp(:,:,spin),op%P,mat)
     endif
op_phase()
subroutine operator_mod::op_phase (complex (kind=kind(0.d0)), intent(inout) Phase, type (operator), dimension(:,:), intent(in) OP_V, class (fields), intent(in) Nsigma, integer, intent(in) N_SUN)
calculate the phase of a given set of operators and HS fields.
Author
Parameters
[in,out] Phase
[in] Op_V An array of Operators
[in] Nsigma
[in] N_SUN
Definition at line 144 of file Operator.f90.
Referenced by global_mod::exchange_step(), global_mod::global_updates(), and main().
     Implicit none
     Complex  (Kind=Kind(0.d0)), Intent(Inout) :: Phase
     Integer,           Intent(IN)    :: N_SUN
     class(fields),    Intent(In)    :: nsigma
     type(operator),   dimension(:,:), Intent(In) :: op_v
     Real  (Kind=Kind(0.d0))                       :: angle
     Integer :: n, nf, nt
     do nf = 1,Size(op_v,2)
        do n = 1,size(op_v,1)
           do nt = 1,size(nsigma%f,2)
              angle = aimag( op_v(n,nf)%g * op_v(n,nf)%alpha ) * nsigma%Phi(n,nt)
              phase = phase*cmplx(cos(angle),sin(angle), kind(0.d0))
           enddo
        enddo
     enddo
     phase = phase**n_sun
op_set()
subroutine operator_mod::op_set (type (operator), intent(inout) Op)
Definition at line 208 of file Operator.f90.
References op_exp().
Referenced by hamiltonian::ham_v(), and predefined_structures::predefined_hopping().
     Implicit none
     type(operator), intent(INOUT) :: op
     Complex (Kind=Kind(0.d0)), allocatable :: U(:,:), TMP(:, :)
     Real    (Kind=Kind(0.d0)), allocatable :: E(:)
     Real    (Kind=Kind(0.d0)) :: Zero = 1.d-9 !, Phi(-2:2)
     Integer :: N, I, J, np,nz
     Complex (Kind=Kind(0.d0)) :: Z
     class(fields), allocatable :: nsigma_single
     Allocate (nsigma_single)
     Call nsigma_single%make(1,1)
     !Phi = 0.d0
     !Phi(-2) = - SQRT(2.D0 * ( 3.D0 + SQRT(6.D0) ) )
     !Phi(-1) = - SQRT(2.D0 * ( 3.D0 - SQRT(6.D0) ) )
     !Phi( 1) =   SQRT(2.D0 * ( 3.D0 - SQRT(6.D0) ) )
     !Phi( 2) =   SQRT(2.D0 * ( 3.D0 + SQRT(6.D0) ) )
     If (op%N > 1) then
        n = op%N
        op%diag = .true.
        do i=1,n
           do j=i+1,n
              ! Binary comparison is OK here as Op%O was initialized to zero during Op_make.
              if (op%O(i,j) .ne. cmplx(0.d0,0.d0, kind(0.d0)) .or. op%O(j,i) .ne. cmplx(0.d0,0.d0, kind(0.d0))) op%diag=.false.
           enddo
        enddo
        if (op%diag) then
           do i=1,n
              op%E(i)=dble(op%O(i,i))
              op%U(i,i)=cmplx(1.d0,0.d0, kind(0.d0))
           enddo
           op%N_non_zero = n
           ! FFA Why do we assume that Op%N_non_zero = N for a diagonal operator?
        else
           Allocate (u(n,n), e(n), tmp(n, n))
           Call diag(op%O,u, e)
           np = 0
           nz = 0
           do i = 1,n
               if ( abs(e(i)) > zero ) then
                 np = np + 1
                 op%U(:, np) = u(:, i)
                 op%E(np)   = e(i)
               else
                 op%U(:, n-nz) = u(:, i)
                 op%E(n-nz)   = e(i)
                 nz = nz + 1
               endif
           enddo
           op%N_non_zero = np
           ! Write(6,*) "Op_set", np,N
           tmp = op%U ! that way we have the changes to the determinant due to the permutation
           z = det_c(tmp, n)
           ! Scale Op%U to be in SU(N)
           DO i = 1, n
              op%U(i,1) = op%U(i, 1)/z
           ENDDO
           deallocate (u, e, tmp)
           ! Op%U,Op%E)
           ! Write(6,*) 'Calling diag 1'
        endif
     else
        op%E(1)   = REAL(Op%O(1,1), kind(0.D0))
        op%U(1,1) = cmplx(1.d0, 0.d0 , kind(0.d0))
        op%N_non_zero = 1
        op%diag = .true.
     endif
     select case(op%type)
     case(1)
        Allocate(op%E_exp(op%N, -op%type : op%type), op%M_exp(op%N, op%N, -op%type : op%type))
        nsigma_single%t(1) = 1
        Do i=1,op%type
           nsigma_single%f(1,1) = real(I,kind=kind(0.d0))
           do n = 1, op%N
              op%E_exp(n,i) = cmplx(1.d0, 0.d0, kind(0.d0))
              op%E_exp(n,-i) = cmplx(1.d0, 0.d0, kind(0.d0))
              if ( n <= op%N_non_Zero) then
                 !Op%E_exp(n,I) = exp(Op%g*Op%E(n)*Phi_st(I,1))
                 op%E_exp(n,i) = exp(op%g*op%E(n)*nsigma_single%Phi(1,1))
                 op%E_exp(n,-i) = 1.d0/op%E_exp(n,i)
              endif
           enddo
           !call Op_exp(Op%g*Phi_st( I,1),Op,Op%M_exp(:,:,I))
           !call Op_exp(Op%g*Phi_st(-I,1),Op,Op%M_exp(:,:,-I))
           call op_exp( op%g*nsigma_single%Phi(1,1),op,op%M_exp(:,:,i))
           call op_exp(-op%g*nsigma_single%Phi(1,1),op,op%M_exp(:,:,-i))
        enddo
     case(2)
        Allocate(op%E_exp(op%N, -op%type : op%type), op%M_exp(op%N, op%N, -op%type : op%type))
        nsigma_single%t(1) = 2
        Do i=1,op%type
           nsigma_single%f(1,1) = real(I,kind=kind(0.d0))
           do n = 1, op%N
              op%E_exp(n,i) = cmplx(1.d0, 0.d0, kind(0.d0))
              op%E_exp(n,-i) = cmplx(1.d0, 0.d0, kind(0.d0))
              if ( n <= op%N_non_Zero) then
                 !Op%E_exp(n,I)  = exp(Op%g*Op%E(n)*Phi_st(I,2))
                 op%E_exp(n,i) = exp(op%g*op%E(n)*nsigma_single%Phi(1,1))
                 op%E_exp(n,-i) = 1.d0/op%E_exp(n,i)
              endif
           enddo
           call op_exp( op%g*nsigma_single%Phi(1,1),op,op%M_exp(:,:,i))
           call op_exp(-op%g*nsigma_single%Phi(1,1),op,op%M_exp(:,:,-i))
           !call Op_exp(Op%g*Phi_st( I,2),Op,Op%M_exp(:,:,I))
           !call Op_exp(Op%g*Phi_st(-I,2),Op,Op%M_exp(:,:,-I))
        enddo
     case default
     end select
     Call nsigma_single%clear()
     Deallocate (nsigma_single)
op_wrapdo()
subroutine operator_mod::op_wrapdo (complex (kind = kind(0.d0)), dimension (ndim,ndim), intent(inout) Mat, type (operator), intent(in) Op, integer, intent(in) spin, integer Ndim, integer, intent(in) N_Type)
Definition at line 517 of file Operator.f90.
Referenced by wrapgr_mod::wrapgr_placegr(), and wrapgr_mod::wrapgrdo().
     Implicit none
     Integer :: Ndim
     type(operator) , INTENT(IN )   :: op
     Complex (Kind = Kind(0.D0)), INTENT(INOUT) :: Mat (Ndim,Ndim)
     Integer, INTENT(IN )   :: spin
     Integer, INTENT(IN) :: N_Type
     ! Local
     Integer :: n, i
     Complex (Kind = Kind(0.D0)) :: VH1(Op%N,OP%N)
     !!!!! N_Type == 1
     !    Op%U*exp(-Op%g*spin*Op%E)*Mat*exp(Op%g*spin*Op%E)*(Op%U^{dagger})
     !
     !!!!!
     !!!!! N_Type == 2
     !    (Op%U^{dagger}) * Mat * Op%U
     !!!!!
     If (n_type == 1) then
       if(op%diag) then
         do i=1,op%N
           call zscal(ndim,op%E_Exp(i,-spin),mat(op%P(i),1),ndim)
         enddo
         do i=1,op%N
           call zscal(ndim,op%E_Exp(i, spin),mat(1,op%P(i)),1)
         enddo
       else
         Do n = 1,op%N
           vh1(:,n)=op%U(:,n)*op%E_Exp(n,-spin)
         Enddo
         call zslgemm('l','n',op%n,ndim,ndim,vh1,op%P,mat)
         Do n = 1,op%N
           vh1(:,n)=op%E_Exp(n, spin)*conjg(op%U(:,n))
         Enddo
         call zslgemm('r','T',op%n,ndim,ndim,vh1,op%P,mat)
       endif
     elseif (n_type == 2 .and. .not. op%diag) then
       call zslgemm('r','n',op%n,ndim,ndim,op%U,op%P,mat)
       call zslgemm('l','c',op%n,ndim,ndim,op%U,op%P,mat)
     endif
op_wrapup()
subroutine operator_mod::op_wrapup (complex (kind=kind(0.d0)), dimension (ndim,ndim), intent(inout) Mat, type (operator), intent(in) Op, integer, intent(in) spin, integer Ndim, integer, intent(in) N_Type)
Definition at line 470 of file Operator.f90.
Referenced by wrapgr_mod::wrapgr_placegr(), wrapgr_mod::wrapgr_random_update(), and wrapgr_mod::wrapgrup().
     Implicit none
     Integer :: Ndim
     type(operator) , INTENT(IN )   :: op
     Complex (Kind=Kind(0.d0)), INTENT(INOUT) :: Mat (Ndim,Ndim)
     Integer, INTENT(IN )   :: spin
     Integer, INTENT(IN)    :: N_Type
     ! Local
     Complex (Kind=Kind(0.d0)) :: VH1(Op%N,Op%N)
     Integer :: I
     !!!!! N_Type ==1
     !    exp(Op%g*spin*Op%E)*(Op%U^{dagger})*Mat*Op%U*exp(-Op%g*spin*Op%E)
     !
     !!!!!
     !!!!! N_Type == 2
     !    Op%U * Mat * (Op%U^{dagger})
     !!!!!
     If (n_type == 1) then
       if(op%diag) then
         do i=1,op%N
           call zscal(ndim,op%E_Exp(i,spin),mat(op%P(i),1),ndim)
         enddo
         do i=1,op%N
           call zscal(ndim,op%E_Exp(i,-spin),mat(1,op%P(i)),1)
         enddo
       else
         Do i = 1,op%N
           vh1(:,i)=op%U(:,i)*op%E_Exp(i,-spin)
         Enddo
         call zslgemm('r','n',op%n,ndim,ndim,vh1,op%P,mat)
         Do i = 1,op%N
           vh1(:,i)=op%E_Exp(i, spin)*conjg(op%U(:,i))
         Enddo
         call zslgemm('l','T',op%n,ndim,ndim,vh1,op%P,mat)
       endif
     elseif (n_type == 2 .and. .not. op%diag) then
         call zslgemm('l','n',op%n,ndim,ndim,op%U,op%P,mat)
         call zslgemm('r','c',op%n,ndim,ndim,op%U,op%P,mat)
     endif