ALF: global_mod Module Reference
global_mod Module Reference
Handles global updates and parallel tempering.
Functions/Subroutines
subroutine exchange_step (Phase, GR, udvr, udvl, Stab_nt, udvst, N_exchange_steps, Tempering_calc_det)
Handles parrallel tempering This subroutine is called only if the tempering flag is switched on.
subroutine global_updates (Phase, GR, udvr, udvl, Stab_nt, udvst, N_Global)
Carries out N_global global updates as defeined in the Global_move routine of the Hamiltonian module.
complex(kind=kind(0.d0)) function compute_ratio_global (Phase_Det_old, Phase_Det_new, Det_vec_old, Det_vec_new, nsigma_old, T0_Proposal_ratio, Ratio)
This fucntion computes ratio of weights for global moves.
subroutine compute_fermion_det (Phase_det, Det_Vec, udvl, udvst, Stab_nt, storage)
Computes the fermion determinant from scratch or from the storage.
integer function npbc_tempering (n, Isize)
Periodic boundary conditions required to defined master and slave for the
tempering.
subroutine global_tempering_setup
The following routine monitors the acceptance of tempering moves.
subroutine global_tempering_init_obs
subroutine global_tempering_obser (toggle)
subroutine global_tempering_pr
Variables
type(obser_vec), private tempering_acceptance
Detailed Description
Handles global updates and parallel tempering.
Author
ALF-project
Function/Subroutine Documentation
compute_fermion_det()
subroutine global_mod::compute_fermion_det (complex (kind=kind(0.d0)), dimension(:), intent(out) Phase_det, real (kind=kind(0.d0)), dimension(:,:), intent(out) Det_Vec, class(udv_state), dimension(:), intent(inout), allocatable udvl, class(udv_state), dimension(:,:), intent(inout), allocatable udvst, integer, dimension(:), intent(in), allocatable Stab_nt, character (len=64), intent(in) storage)
Computes the fermion determinant from scratch or from the storage.
Author
 Finite temperature: If the storage is full then computes  det( 1 +  VL*DL*UL^{dag} )= Phase_det*e^{ \sum_{n=1}^{ndim} Det_vec(n) }
                     Note that  Udvl%U = UL, Udvl%D = DL and  Udvl%V = VL^{dag}
                     If storage is empty one first computes  Udvl and in doing so fills up the storage.
 Zero temperature:   If storage is full then computes  det \Psi_L U(\theta_tot,0) \Psi_R  =  Phase_det*e^{ \sum_{n=1}^{N_part} Det_vec(n) }
                     For the projective code the required scales which one can throw away for the Green function are in udvst.
                     If the storage is not full, then things will be computed from scratch and intermediate results will be stored in udvst.
Parameters
[in,out] udvl,udvr Class(UDV_State)
  If storage=Full  : On entry and exit udvl contains the last udv decomposition such that G=(1 + VL*DL*UL^{dag})^{-1}
  If storage=Empty : On exit udv1 will contain the last udv decomposition such that G=(1 + VL*DL*UL^{dag})^{-1}
[out] Phase_det Complex, Dimension(N_FL)
  The phase, per flavor
[out] Det_vec Real, Dimension(:,N_FL)
[in] Stab_nt Integer, Dimension(:)
  List of time slices for stabilization.
[in] Storage Character
  storage = "Full".  Compute the fermion det  with the use of the storage.
  storage = "Empty". Compute the fermion det from scratch and  in doing so, fill the storage.
Local variables
Definition at line 794 of file Global_mod.f90.
References hamiltonian::n_fl, hamiltonian::ndim, hamiltonian::projector, udv_wrap_mod::udv_wrap(), hamiltonian::wf_l, hamiltonian::wf_r, and wrapul().
Referenced by exchange_step(), and global_updates().
 !--------------------------------------------------------------------
         Use  udv_wrap_mod
         Use udv_state_mod
         Implicit none
         REAL    (Kind=Kind(0.d0)), Dimension(:,:), Intent(OUT)  ::  Det_Vec
         Complex (Kind=Kind(0.d0)), Dimension(:)  , Intent(OUT)  ::  Phase_det
         CLASS(UDV_State), DIMENSION(:)  , ALLOCATABLE,  INTENT(INOUT) :: udvl
         CLASS(UDV_State), Dimension(:,:), ALLOCATABLE,  INTENT(INOUT) :: udvst
         INTEGER,          dimension(:),   allocatable,    INTENT(IN)  :: Stab_nt
         Character (Len=64), Intent(IN) :: storage
         Integer ::  N_size, NCON, I,  J, N_part, info, NSTM, N, nf, nst, nt, nt1
         Integer, allocatable :: ipiv(:)
         COMPLEX (Kind=Kind(0.d0)) :: alpha,beta, Z, Z1
         TYPE(UDV_State) :: udvlocal
         COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Allocatable ::  TP!, U, V
         COMPLEX (Kind=Kind(0.d0)), Dimension(:), Allocatable :: D
         if(udvl(1)%side .ne. "L" .and. udvl(1)%side .ne. "l" ) then
            write(*,*) "calling wrong decompose"
            stop
         endif
         nstm = Size(udvst, 1)
         If (storage == "Empty" ) then
            DO nf = 1,n_fl
               if (projector) then
                  CALL udvl(nf)%reset('l',wf_l(nf)%P)
               else
                  CALL udvl(nf)%reset('l')
               endif
            ENDDO
            DO nst = nstm-1,1,-1
               nt1 = stab_nt(nst+1)
               nt  = stab_nt(nst  )
               !Write(6,*) NT1,NT, NST
               CALL wrapul(nt1,nt, udvl)
               Do nf = 1,n_fl
                  udvst(nst, nf) = udvl(nf)
               ENDDO
            ENDDO
            nt1 = stab_nt(1)
            CALL wrapul(nt1,0, udvl)
         Endif
         if (projector) then
            n_part=udvst(1,1)%N_part
            n_size=udvl(1)%ndim
            Allocate (tp(n_part,n_part), ipiv(n_part))
            do nf=1,n_fl
               n_part=udvst(1,nf)%N_part
               do i=1,nstm-1
                  do n=1,n_part
 #if !defined(LOG)
                     det_vec(n,nf)=det_vec(n,nf)+log(dble(udvst(i,nf)%D(n)))
 #else
                     det_vec(n,nf)=det_vec(n,nf)+udvst(i,nf)%L(n)
 #endif
                  enddo
               enddo
               do n=1,n_part
 #if !defined(LOG)
                  det_vec(n,nf)=det_vec(n,nf)+log(dble(udvl(nf)%D(n)))
 #else
                  det_vec(n,nf)=det_vec(n,nf)+udvl(nf)%L(n)
 #endif
               enddo
               alpha=1.d0
               beta=0.d0
               CALL zgemm('C','N',n_part,n_part,n_size,alpha,udvl(nf)%U(1,1),n_size,wf_r(nf)%P(1,1),n_size,beta,tp(1,1),n_part)
               ! ZGETRF computes an LU factorization of a general M-by-N matrix A
               ! using partial pivoting with row interchanges.
               call zgetrf(n_part, n_part, tp(1,1), n_part, ipiv, info)
               z=1.d0
               Do j=1,n_part
                  if (ipiv(j).ne.j) then
                     z = -z
                  endif
                  z =  z * tp(j,j)
               enddo
               phase_det(nf) = z/abs(z)
               det_vec(1,nf) = det_vec(1,nf)+log(abs(z))
            enddo
            Deallocate(tp,ipiv)
            return
         endif
         !    N_size = SIZE(DL,1)
         n_size = udvl(1)%ndim
         ncon  = 0
         alpha = cmplx(1.d0,0.d0,kind(0.d0))
         beta  = cmplx(0.d0,0.d0,kind(0.d0))
         Allocate (tp(n_size,n_size),d(n_size))
         CALL udvlocal%alloc(n_size)
         Do nf = 1,n_fl
            tp = udvl(nf)%U !udvl stores U^dag instead of U !CT(udvl%U)
 #if !defined(LOG)
 #if !defined(STAB3)
            DO j = 1,n_size
               tp(:,j) = tp(:,j) +  udvl(nf)%V(:,j)*udvl(nf)%D(j)
            ENDDO
 #else
            DO j = 1,n_size
               if ( dble(udvl(nf)%D(j)) <= 1.d0 ) then
                  tp(:,j) = tp(:,j) +  udvl(nf)%V(:,j)*udvl(nf)%D(j)
               else
                  tp(:,j) = tp(:,j)/udvl(nf)%D(j) +  udvl(nf)%V(:,j)
               endif
            ENDDO
 #endif
 #else
            DO j = 1,n_size
               if ( udvl(nf)%L(j) <= 0.d0 ) then
                  tp(:,j) = tp(:,j) +  udvl(nf)%V(:,j)*cmplx(exp(udvl(nf)%L(j)),0.d0,kind(0.d0))
               else
                  tp(:,j) = tp(:,j)*cmplx(exp(-udvl(nf)%L(j)),0.d0,kind(0.d0)) +  udvl(nf)%V(:,j)
               endif
            ENDDO
 #endif
            !Call  UDV_WRAP_Pivot(TP,udvlocal%U, D, udvlocal%V, NCON,N_size,N_Size)
            Call  udv_wrap(tp,udvlocal%U, d, udvlocal%V, ncon )
            z  = det_c(udvlocal%V, n_size) ! Det destroys its argument
            !         Call MMULT(TP, udvl%U, udvlocal%U)
            CALL zgemm('C', 'N', n_size, n_size, n_size, alpha, udvl(nf)%U(1,1), n_size, udvlocal%U(1,1), n_size, beta, tp, n_size)
            z1 = det_c(tp, n_size)
            phase_det(nf)   = z*z1/abs(z*z1)
 #if !defined(LOG)
 #if !defined(STAB3)
            det_vec(:,nf) = log(real(D(:)))
            det_vec(1,nf) = log(real(D(1))) + log(ABS(Z*Z1))
 #else
            det_vec(1,nf) = log(real(D(1))*ABS(Z*Z1))
            if (dble(udvl(nf)%D(1)) > 1.d0) det_vec(1,nf)=det_vec(1,nf)+log(dble(udvl(nf)%D(1)))
            Do j=2,ndim
               if (dble(udvl(nf)%D(j))<=1.d0) then
                  det_vec(j,nf) = log(real(D(J)))
               else
                  det_vec(j,nf) = log(real(D(J)))+log(dble(udvl(nf)%D(J)))
               endif
            enddo
 #endif
 #else
            det_vec(1,nf) = log(real(D(1))*ABS(Z*Z1))
            if (udvl(nf)%L(1) > 0.d0) det_vec(1)=det_vec(1)+udvl(nf)%L(1)
            Do j=2,ndim
               if (udvl(nf)%L(j)<=0.d0) then
                  det_vec(j,nf) = log(real(D(J)))
               else
                  det_vec(j,nf) = log(real(D(J)))+udvl(nf)%L(J)
               endif
            enddo
 #endif
         Enddo
         Deallocate (tp)
         CALL udvlocal%dealloc
compute_ratio_global()
complex (kind=kind(0.d0)) function global_mod::compute_ratio_global (complex (kind=kind(0.d0)), dimension(:), intent(in), allocatable Phase_Det_old, complex (kind=kind(0.d0)), dimension(:), intent(in), allocatable Phase_Det_new, real (kind=kind(0.d0)), dimension(:,:), intent(in), allocatable Det_vec_old, real (kind=kind(0.d0)), dimension(:,:), intent(in), allocatable Det_vec_new, class (fields), intent(in), allocatable nsigma_old, real (kind=kind(0.d0)), intent(in) T0_Proposal_ratio, complex (kind=kind(0.d0)), dimension(2), intent(out) Ratio)
This fucntion computes ratio of weights for global moves.
Author
The ALF Project contributors
  Ratio_Global = T0(nsigma--> nsigma_old) W(nsigma)/T0(nsigma_old--> nsigma) W(nsigma_old) =
                 T0_Proposal_ratio   W(nsigma)/  W(nsigma_old)
  On entry the old and new fermion determinants read: Phase_det*e^{ \sum_{n=1}^{ndim} Det_vec(n) }
  as obtained from the Compute_Fermion_det routine.
  On exit Ratio_Global = Ratio(1)*exp(Ratio(2))
Parameters
[in] Phase_det_new Complex, Dimension(N_FL)
[in] Phase_det_old Complex, Dimension(N_FL)
[in] Det_vec_new Real, Dimension(:,N_FL)
[in] Det_vec_old Real, Dimension(:,N_FL)
[in] T0_proposal_ratio Real
[in] nsigma_old Class(Fields)
  Old configuration. The new configuration is stored in nsigma. nsigma is a globale variable
  contained in the Hamiltonian module.
Definition at line 699 of file Global_mod.f90.
References hamiltonian::delta_s0_global(), hamiltonian::ltrot, hamiltonian::n_fl, hamiltonian::n_sun, hamiltonian::ndim, hamiltonian::nsigma, and hamiltonian::op_v.
Referenced by exchange_step(), and global_updates().
         Implicit none
         ! Arguments
         Complex (Kind=Kind(0.d0)), allocatable, INTENT(IN) :: Phase_Det_old(:), Phase_Det_new(:)
         REAL    (Kind=Kind(0.d0)), allocatable, INTENT(IN) :: Det_vec_old(:,:), Det_vec_new(:,:)
         Real    (Kind=Kind(0.d0)),    INTENT(IN)  :: T0_proposal_ratio
         class(fields), allocatable,  INTENT(IN)  :: nsigma_old
         Complex (Kind=Kind(0.d0)),    INTENT(out) :: Ratio(2)
         ! Local
         Integer  :: Nf, i, nt
         Complex (Kind=Kind(0.d0)) :: Z, Z1
         Real    (Kind=Kind(0.d0)) :: X, Ratio_2
         ratio = cmplx(0.d0,0.d0,kind(0.d0))
         ratio_2 = 0.d0
         !X = 1.d0
         Do nf = 1,n_fl
            DO i = 1,ndim
               !X= X*real(Det_vec_new(I,nf),kind(0.d0)) / Real(Det_vec_old(I,nf),kind(0.d0) )
               ratio_2 = ratio_2 +  det_vec_new(i,nf) - det_vec_old(i,nf)
            enddo
         enddo
         !Z = cmplx(X,0.d0,kind(0.d0))
         ratio(1) = cmplx(1.d0,0.d0,kind(0.d0))
         Do nf = 1,n_fl
            !Z = Z*Phase_Det_new(nf)/Phase_Det_old(nf)
            ratio(1) = ratio(1) *  phase_det_new(nf)/phase_det_old(nf)
         enddo
         !Z = Z**N_SUN
         ratio(1) = ratio(1)**n_sun
         ratio_2 = real(N_SUN,kind(0.d0))*Ratio_2
         Do i = 1,Size(op_v,1)
            x = 0.d0
            Do nt = 1,ltrot
               !Z = Z * cmplx( Gaml(nsigma(i,nt),2)/Gaml(nsigma_old(i,nt),2),0.d0,kind(0.d0) )
               ratio(1) = ratio(1) * cmplx( nsigma%Gama(i,nt)/nsigma_old%Gama(i,nt),0.d0,kind(0.d0) )  !  You could put this in Ratio_2
               x = x + nsigma%Phi(i,nt) - nsigma_old%Phi(i,nt)
            Enddo
            Do nf = 1,n_fl
               !Z = Z * exp(cmplx( X*Real(N_SUN,Kind(0.d0)), 0.d0,kind(0.d0)) * Op_V(i,nf)%g * Op_V(i,nf)%alpha )
               ratio(1) = ratio(1) * exp(cmplx( x*Real(N_SUN,Kind(0.d0)), 0.d0,kind(0.d0)) * Op_V(i,nf)%g * Op_V(i,nf)%alpha )
            Enddo
         Enddo
         !Z =  Z * cmplx( Delta_S0_global(Nsigma_old),0.d0,kind(0.d0) )
         !Z =  Z * cmplx( T0_Proposal_ratio, 0.d0,kind(0.d0))
         ratio_2 = ratio_2 + log(delta_s0_global(nsigma_old)) + log(t0_proposal_ratio)
         ratio(2) = ratio_2
         compute_ratio_global = ratio(1)*exp(ratio(2))
exchange_step()
subroutine global_mod::exchange_step (complex (kind=kind(0.d0)), intent(inout) Phase, complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, class(udv_state), dimension(:), intent(inout), allocatable udvr, class(udv_state), dimension(:), intent(inout), allocatable udvl, integer, dimension(:), intent(in), allocatable Stab_nt, class(udv_state), dimension(:, :), intent(inout), allocatable udvst, integer N_exchange_steps, logical Tempering_calc_det)
Handles parrallel tempering This subroutine is called only if the tempering flag is switched on.
Author
ALF-project In this case the MPI flag is also switched on.
Parameters
[in,out] phase Arguments
n_exchange_steps Local variables.
tempering_calc_det Additional variables for running without Fermion weight
Compute for each core the old weights.
Store old configuration
Set the partner rank on each core
Exchange configurations
Each node now has a new configuration nsigma
Compute ratio on weights one each rank
Acceptace/rejection decision taken on master node after receiving information from slave
Send result of acceptance/rejection decision form master to slave
Move has been accepted
Finalize
If move has been accepted, no use to recomute storage
Compute the Green functions so as to provide correct starting point for the sequential updates.
Send >>Phase, GR, udvr, udvl, udvst<< to new node
Definition at line 71 of file Global_mod.f90.
References cgr(), compute_fermion_det(), compute_ratio_global(), control::control_upgrade_temp(), hamiltonian::delta_s0_global(), global_tempering_obser(), hamiltonian::group_comm, hamiltonian::n_fl, hamiltonian::n_sun, hamiltonian::ndim, npbc_tempering(), hamiltonian::nsigma, operator_mod::op_phase(), hamiltonian::op_v, hamiltonian::projector, hamiltonian::wf_l, and wrapul().
Referenced by main().
         Use udv_state_mod
         Use mpi
         Implicit none
         Interface
            SUBROUTINE wrapul(NTAU1, NTAU, udvl)
              Use hamiltonian
              Use udv_state_mod
              Implicit none
              CLASS(UDV_State), intent(inout) :: udvl(N_FL)
              Integer :: NTAU1, NTAU
            END SUBROUTINE wrapul
            SUBROUTINE cgr(PHASE,NVAR, GRUP, udvr, udvl)
              Use udv_wrap_mod
              Use udv_state_mod
              Implicit None
              CLASS(UDV_State), INTENT(IN) :: udvl, udvr
              COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(Inout) :: GRUP
              COMPLEX(Kind=Kind(0.d0)) :: PHASE
              INTEGER         :: NVAR
            END SUBROUTINE cgr
         end Interface
         COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT)                   :: Phase
         CLASS(UDV_State), intent(inout), allocatable, Dimension(:) :: udvl, udvr
         COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:), INTENT(INOUT), allocatable :: GR
         CLASS(UDV_State), intent(inout), allocatable, Dimension(:, :) :: udvst
         INTEGER, dimension(:),     INTENT   (IN), allocatable      :: Stab_nt
         Integer :: NST, NSTM, NF, NT, NT1, NVAR,N, N1,N2, I, NC, I_Partner, n_step, N_exchange_steps, N_count, N_part
         Integer, Dimension(:,:),  allocatable :: nsigma_old
         Real    (Kind=Kind(0.d0)) :: T0_Proposal_ratio, Weight, Weight1
         Complex (Kind=Kind(0.d0)) :: Z_ONE = cmplx(1.d0, 0.d0, kind(0.d0)), z, ratiotot, ratiotot_p, phase_old, phase_new
         Real    (Kind=Kind(0.d0)), allocatable :: Det_vec_old(:,:), Det_vec_new(:,:)
         Complex (Kind=Kind(0.d0)), allocatable :: Phase_Det_new(:), Phase_Det_old(:)
         Complex (Kind=Kind(0.d0)) :: Ratio(2), Ratio_p(2)
         Logical :: TOGGLE, L_Test
         Integer, allocatable :: List_partner(:), List_masters(:)
         Logical :: Tempering_calc_det
         ! Keep track of where the configuration originally came from
         Integer        :: nsigma_irank, nsigma_old_irank, nsigma_irank_temp
         Integer        :: n_GR
         !Integer, Dimension(:,:),  allocatable :: nsigma_orig, nsigma_test
         !Integer :: I1, I2
         Integer        :: Isize, Irank, Ierr, irank_g, isize_g, igroup
         Integer        :: STATUS(MPI_STATUS_SIZE)
         CALL mpi_comm_size(mpi_comm_world,isize,ierr)
         CALL mpi_comm_rank(mpi_comm_world,irank,ierr)
         call mpi_comm_rank(group_comm, irank_g, ierr)
         call mpi_comm_size(group_comm, isize_g, ierr)
         igroup           = irank/isize_g
         nsigma_irank = irank
         n1 = size(nsigma,1)
         n2 = size(nsigma,2)
         nstm = Size(udvst, 1)
         Allocate ( nsigma_old(n1,n2) )
         if (tempering_calc_det) then
            Allocate ( det_vec_old(ndim,n_fl), det_vec_new(ndim,n_fl) )
            Allocate ( phase_det_new(n_fl), phase_det_old(n_fl) )
         endif
         Allocate ( list_partner(0:isize-1), list_masters(isize/2) )
         !         Allocate ( nsigma_orig(n1,n2) )
         !         nsigma_orig = nsigma
         l_test = .false.
         if (tempering_calc_det) then
            ! Set old weight.
            det_vec_old=0.d0
            if (projector) then
               do nf=1,n_fl
                 n_part=udvst(1,nf)%N_part
                 do i=1,nstm-1
                   do n=1,n_part
 #if !defined(LOG)
                     det_vec_old(n,nf)=det_vec_old(n,nf)+log(dble(udvst(i,nf)%D(n)))
 #else
                     det_vec_old(n,nf)=det_vec_old(n,nf)+udvst(i,nf)%L(n)
 #endif
                   enddo
                 enddo
               enddo
               Do nf = 1,n_fl
                 n_part=udvl(nf)%N_part
                 do n=1,n_part
 #if !defined(LOG)
                     det_vec_new(n,nf)=det_vec_new(n,nf)+log(dble(udvl(nf)%D(n)))
 #else
                     det_vec_new(n,nf)=det_vec_new(n,nf)+udvl(nf)%L(n)
 #endif
                 enddo
               ENDDO
            endif
            phase_old =cmplx(1.d0,0.d0,kind(0.d0))
            do nf = 1,n_fl
               Call compute_fermion_det(z,det_vec_old(:,nf), udvl(nf), nf)
               phase_det_old(nf) = z
               phase_old = phase_old*z
            Enddo
            call op_phase(phase_old,op_v,nsigma,n_sun)
         endif
         nsigma_old = nsigma
         nsigma_old_irank = nsigma_irank
         ! Setup the list of masters
         nc = 0
         Do i  = 0,isize-1,2*isize_g
            do n = 0,isize_g-1
               nc = nc + 1
               list_masters(nc)  = i + n
            enddo
         Enddo
         if (l_test) then
            if (irank == 0)  then
               Write(6,*) 'List  of masters: '
               Do nc = 1,isize/2
                  Write(6,*) nc, list_masters(nc)
               Enddo
            endif
         endif
         DO n_count = 1,n_exchange_steps
            If (irank == 0 ) then
               n_step = isize_g
               if (  ranf_wrap() > 0.5d0 ) n_step = -isize_g
               Do i = 0,isize-1,2*isize_g
                  do n = 0,isize_g-1
                     list_partner(npbc_tempering(i  + n             ,isize)) =  npbc_tempering(i +  n   + n_step,isize)
                     list_partner(npbc_tempering(i  + n  + n_step  , isize)) =  npbc_tempering(i + n            ,isize)
                  enddo
               enddo
            endif
            CALL mpi_bcast(list_partner, isize  ,mpi_integer,   0,mpi_comm_world,ierr)
            If (l_test) then
               if (irank == 0 ) then
                  Write(6,*) 'Testing global : '
                  do  i = 0,isize -1
                     Write(6,*)  i, list_partner(i) !, Phase_old, Phase
                     Write(11,*)  i, list_partner(i) !, Phase_old, Phase
                  enddo
                  Write(11,*)
               endif
            Endif
            !call MPI_Barrier(MPI_COMM_WORLD)
            !Write(6,*) '---------'
 !!$    select case (IRANK)
 !!$    case(0)
 !!$       nsigma_old(1,1) =  1;  nsigma_old(2,1) = 1
 !!$    case(1)
 !!$       nsigma_old(1,1) = -1;  nsigma_old(2,1) = 1
 !!$    case(2)
 !!$       nsigma_old(1,1) =  1;  nsigma_old(2,1) = -1
 !!$    case(3)
 !!$       nsigma_old(1,1) = -1;  nsigma_old(2,1) = -1
 !!$    case default
 !!$    end select
            n = size(nsigma_old,1)*size(nsigma_old,2)
            CALL mpi_sendrecv(nsigma_old      , n, mpi_integer, list_partner(irank), 0, &
                     &        nsigma          , n, mpi_integer, list_partner(irank), 0, mpi_comm_world,status,ierr)
            CALL mpi_sendrecv(nsigma_old_irank, 1, mpi_integer, list_partner(irank), 0, &
                     &        nsigma_irank    , 1, mpi_integer, list_partner(irank), 0, mpi_comm_world,status,ierr)
 !!$    If (L_test) then
 !!$       Write(6,*) 'Testing global : ', Irank,List_partner(IRANK), nsigma_old(1,1),  nsigma_old(2,1), nsigma(1,1),  nsigma(2,1)
 !!$    Endif
     if (tempering_calc_det) then
            DO nf = 1,n_fl
               if (projector) then
                 CALL udvl(nf)%reset('l',wf_l(nf)%P)
               else
                 CALL udvl(nf)%reset('l')
               endif
            ENDDO
               !! Compute detvec for projector
            det_vec_new=0.d0
            DO nst = nstm-1,1,-1
               nt1 = stab_nt(nst+1)
               nt  = stab_nt(nst  )
               !Write(6,*) NT1,NT, NST
               CALL wrapul(nt1,nt, udvl)
               Do nf = 1,n_fl
                  udvst(nst, nf) = udvl(nf)
                  if (projector) then
                     n_part=udvl(nf)%N_part
                     do n=1,n_part
 #if !defined(LOG)
                         det_vec_new(n,nf)=det_vec_new(n,nf)+log(dble(udvl(nf)%D(n)))
 #else
                         det_vec_new(n,nf)=det_vec_new(n,nf)+udvl(nf)%L(n)
 #endif
                     enddo
                  endif
               ENDDO
            ENDDO
            nt1 = stab_nt(1)
            CALL wrapul(nt1,0, udvl)
            if (projector) then
               Do nf = 1,n_fl
                 n_part=udvl(nf)%N_part
                 do n=1,n_part
 #if !defined(LOG)
                     det_vec_new(n,nf)=det_vec_new(n,nf)+log(dble(udvl(nf)%D(n)))
 #else
                     det_vec_new(n,nf)=det_vec_new(n,nf)+udvl(nf)%L(n)
 #endif
                 enddo
               ENDDO
            endif
            phase_new = cmplx(1.d0,0.d0,kind(0.d0))
            do nf = 1,n_fl
               Call compute_fermion_det(z,det_vec_new(:,nf), udvl(nf), nf)
               phase_det_new(nf) = z
               phase_new = phase_new*z
            Enddo
            call op_phase(phase_new,op_v,nsigma,n_sun)
            t0_proposal_ratio = 1.d0
            ratiotot = compute_ratio_global(phase_det_old, phase_det_new, &
                 &                               det_vec_old, det_vec_new, nsigma_old, t0_proposal_ratio,ratio)
            If (l_test) Write(6,*) 'Ratio_global: Irank, Partner',irank,list_partner(irank), ratiotot, ratio(1)*exp(ratio(2))
         else
            ratiotot = delta_s0_global(nsigma_old)
            ratio(1) = ratiotot
            ratio(2) = 0
         endif
            Do nc = 1,isize/2 ! Loop over masters
               i = list_masters(nc)
               If (irank == i ) Then
                  !CALL MPI_SEND(Ratiotot,1, MPI_COMPLEX16  , List_partner(I), I+512 , MPI_COMM_WORLD,IERR)
                  CALL mpi_send(ratio   ,2, mpi_complex16  , list_partner(i), i+1024, mpi_comm_world,ierr)
               else if (irank == list_partner(i) ) Then
                  !CALL MPI_RECV(Ratiotot_p , 1, MPI_COMPLEX16,  I, I+512 , MPI_COMM_WORLD,STATUS,IERR)
                  CALL mpi_recv(ratio_p    , 2, mpi_complex16,  i, i+1024, mpi_comm_world,status,ierr)
                  !Weight = abs(Ratiotot_p*Ratiotot)
                  weight= abs(ratio(1) * ratio_p(1) * exp( ratio_p(2) + ratio(2)  ) )
                  toggle = .false.
                  if ( weight > ranf_wrap() )  toggle =.true.
                  If (l_test) Write(6,*) 'Master : ', list_partner(i), i, weight, toggle
               endif
            enddo
            Do nc =  1,isize/2 ! Loop over masters
               i = list_masters(nc)
               If (irank == list_partner(i) ) Then
                  ! Write(6,*) 'Send from ', List_Partner(I), 'to, ', I, I + 512
                  CALL mpi_send(toggle, 1, mpi_logical, i, i+512, mpi_comm_world,ierr)
               else if (irank == i ) Then
                  CALL mpi_recv(toggle , 1, mpi_logical,   list_partner(i), i+512 ,mpi_comm_world,status,ierr)
                  If (l_test) Write(6,*) 'Slave : ', irank,  toggle
               endif
            enddo
            If (l_test) Write(6,*) 'Final: ',  irank, list_partner(irank), toggle
            Call global_tempering_obser(toggle)
            Call control_upgrade_temp  (toggle)
            If (toggle)  then
               if (tempering_calc_det) then
                  phase_old     = phase_new
                  phase_det_old = phase_det_new
                  det_vec_old   = det_vec_new
               endif
               nsigma_old       = nsigma
               nsigma_old_irank = nsigma_irank
            else
               nsigma       = nsigma_old
               nsigma_irank = nsigma_old_irank
            endif
         enddo
         if (tempering_calc_det) then
            If (.not.toggle) then
               DO nf = 1,n_fl
                  if (projector) then
                     CALL udvl(nf)%reset('l',wf_l(nf)%P)
                  else
                     CALL udvl(nf)%reset('l')
                  endif
               ENDDO
               DO nst = nstm-1,1,-1
                  nt1 = stab_nt(nst+1)
                  nt  = stab_nt(nst  )
                  !Write(6,*) NT1,NT, NST
                  CALL wrapul(nt1,nt, udvl)
                  Do nf = 1,n_fl
                     udvst(nst, nf) = udvl(nf)
                  ENDDO
               ENDDO
               nt1 = stab_nt(1)
               CALL wrapul(nt1,0, udvl)
            Endif
            nvar  = 1
            phase = cmplx(1.d0,0.d0,kind(0.d0))
            do nf = 1,n_fl
               CALL cgr(z, nvar, gr(:,:,nf), udvr(nf),  udvl(nf))
               phase = phase*z
            Enddo
            call op_phase(phase,op_v,nsigma,n_sun)
         else
            !  First step: Each node sends to IRANK=0 its value nsigma_irank,
            !  which is the node where its new Phase, GR, udvr, udvl, udvst is stored
            !              This node then tells each node where to send its now old Phase, GR, udvr, udvl, udvst
            !              Finally, the variables get submitted
            If (irank == 0) then
               Do i = 1,isize-1
                  CALL mpi_recv(nsigma_irank_temp , 1, mpi_integer, i, 0, mpi_comm_world,status,ierr)
                  If ( nsigma_irank_temp == 0) then
                     nsigma_old_irank = i
                  else
                     CALL mpi_send(i , 1, mpi_integer, nsigma_irank_temp, 0, mpi_comm_world,ierr)
                  endif
               enddo
               If ( nsigma_irank /= 0 ) then
                  CALL mpi_send(0 , 1, mpi_integer, nsigma_irank, 0, mpi_comm_world,ierr)
               endif
            else
               CALL mpi_send(nsigma_irank     , 1, mpi_integer, 0, 0, mpi_comm_world,ierr)
               CALL mpi_recv(nsigma_old_irank , 1, mpi_integer, 0, 0, mpi_comm_world,status,ierr)
         endif
         if ( nsigma_irank /= irank ) then
            CALL mpi_sendrecv_replace(phase, 1, mpi_complex16, nsigma_old_irank, 0, &
                     &        nsigma_irank, 0, mpi_comm_world, status, ierr)
            n_gr = size(gr,1)*size(gr,2)*size(gr,3)
            CALL mpi_sendrecv_replace(gr, n_gr, mpi_complex16, nsigma_old_irank, 0, &
                     &        nsigma_irank, 0, mpi_comm_world, status, ierr)
            do nf = 1,n_fl
               CALL udvr(nf)%MPI_Sendrecv(nsigma_old_irank, 0, nsigma_irank, 0, status, ierr)
            enddo
            do nf = 1,n_fl
               CALL udvl(nf)%MPI_Sendrecv(nsigma_old_irank, 0, nsigma_irank, 0, status, ierr)
            enddo
            do nst = 1, nstm
               do nf = 1,n_fl
                  CALL udvst(nst, nf)%MPI_Sendrecv(nsigma_old_irank, 0, nsigma_irank, 0, status, ierr)
               enddo
            enddo
         endif
     endif
         Deallocate ( nsigma_old )
     if (tempering_calc_det) then
         Deallocate ( det_vec_old, det_vec_new )
         Deallocate ( phase_det_new, phase_det_old )
     endif
         Deallocate ( list_partner, list_masters )
global_tempering_init_obs()
subroutine global_mod::global_tempering_init_obs ()
Definition at line 1000 of file Global_mod.f90.
References observables::obser_vec_init(), and tempering_acceptance.
Referenced by main().
         Call obser_vec_init( tempering_acceptance )
global_tempering_obser()
subroutine global_mod::global_tempering_obser (logical, intent(in) toggle)
Definition at line 1006 of file Global_mod.f90.
References tempering_acceptance.
Referenced by exchange_step().
         Implicit none
         Logical, intent(in) :: toggle
         tempering_acceptance%N         =  tempering_acceptance%N + 1
         tempering_acceptance%Ave_sign  =  tempering_acceptance%Ave_sign + 1.d0
         if (toggle) tempering_acceptance%Obs_vec(1) = tempering_acceptance%Obs_vec(1) +  cmplx(1.d0,0.d0,kind(0.d0))
global_tempering_pr()
subroutine global_mod::global_tempering_pr ()
Definition at line 1016 of file Global_mod.f90.
References hamiltonian::group_comm, observables::print_bin_vec(), and tempering_acceptance.
Referenced by main().
         Implicit none
         Call  print_bin_vec(tempering_acceptance,group_comm)
global_tempering_setup()
subroutine global_mod::global_tempering_setup ()
The following routine monitors the acceptance of tempering moves.
Author
Fakher Assaad
Definition at line 990 of file Global_mod.f90.
References observables::obser_vec_make(), and tempering_acceptance.
Referenced by main().
         Integer    ::   N
         Character (len=64) ::  Filename
         n = 1
         filename = "Acc_Temp"
         Call obser_vec_make(tempering_acceptance,n,filename)
global_updates()
subroutine global_mod::global_updates (complex (kind=kind(0.d0)), intent(inout) Phase, complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, class (udv_state), dimension(:), intent(inout), allocatable udvr, class (udv_state), dimension(:), intent(inout), allocatable udvl, integer, dimension(:), intent(in), allocatable Stab_nt, class(udv_state), dimension(:,:), intent(inout), allocatable udvst, integer, intent(in) N_Global)
Carries out N_global global updates as defeined in the Global_move routine of the Hamiltonian module.
Author
The ALF Project contributors
On entry and on exit the left storage is full, the Green function is on time slice 0 and the phase is set. The same holds on exit but with updated quantities.
Parameters
[in,out] Phase Complex
  Is updated upon acceptance
[in,out] udvl,udvr Class(UDV_State)
  On entry udvl contains the last udv decomposition such that G=(1 + VL*DL*UL^{dag})^{-1}
  udvr  is used as working space
[in,out] GR Complex
  Green function. Is updated upon acceptance.
[in,out] udvst Class(UDV_State)
  Storage. Is updated with left propagation upon acceptance
[in] Stab_nt Integer
  List of time slices for stabilization.
[in] N_Global Integer
  Number of global moves that will be caried out
Definition at line 494 of file Global_mod.f90.
References cgr(), compute_fermion_det(), compute_ratio_global(), control::control_precisionp_glob(), control::control_upgrade_glob(), hamiltonian::global_move(), hamiltonian::n_fl, hamiltonian::n_sun, hamiltonian::ndim, hamiltonian::nsigma, operator_mod::op_phase(), hamiltonian::op_v, hamiltonian::projector, hamiltonian::wf_l, hamiltonian::wf_r, and wrapul().
Referenced by main().
         Use udv_state_mod
         Implicit none
         Interface
            SUBROUTINE wrapul(NTAU1, NTAU, udvl)
              Use hamiltonian
              Use udv_state_mod
              Implicit none
              CLASS(UDV_State), intent(inout), allocatable, dimension(:) :: udvl
              Integer :: NTAU1, NTAU
            END SUBROUTINE wrapul
            SUBROUTINE cgr(PHASE,NVAR, GRUP, udvr, udvl)
              Use udv_wrap_mod
              Use udv_state_mod
              Implicit None
              CLASS(UDV_State), INTENT(IN) :: udvl, udvr
              COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(Inout) :: GRUP
              COMPLEX(Kind=Kind(0.d0)) :: PHASE
              INTEGER         :: NVAR
            END SUBROUTINE cgr
         end Interface
         !  Arguments
         COMPLEX (Kind=Kind(0.d0)),                                INTENT(INOUT) :: Phase
         class(udv_state), DIMENSION(:), ALLOCATABLE,           INTENT(INOUT) :: udvl, udvr
         COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:),  allocatable,INTENT(INOUT) :: GR
         CLASS(UDV_State), Dimension(:,:), ALLOCATABLE,            INTENT(INOUT) :: udvst
         INTEGER, dimension(:),   allocatable,                     INTENT(IN)    :: Stab_nt
         Integer,                                                  INTENT(IN)    :: N_Global
         !  Local variables.
         Integer :: NST, NSTM, NF, NT, NT1, NVAR,N, N1,N2, I, NC, N_part,j
         Real    (Kind=Kind(0.d0)) :: T0_Proposal_ratio, Weight
         Complex (Kind=Kind(0.d0)) :: Z_ONE = cmplx(1.d0, 0.d0, kind(0.d0)), z, ratiotot, phase_old, phase_new
         Complex (Kind=Kind(0.d0)), allocatable :: Det_vec_test(:,:), Phase_Det_new(:), Phase_Det_old(:)
         Real    (Kind=Kind(0.d0)), allocatable :: Det_vec_old(:,:), Det_vec_new(:,:)
         class(fields), allocatable :: nsigma_old
         Complex (Kind=Kind(0.d0)) :: Ratio(2)
         Logical :: TOGGLE, L_Test
         Real    (Kind=Kind(0.d0)) :: size_clust
         Real    (Kind=Kind(0.d0)) :: ratio_2_test
         Character (Len=64)  :: storage
         n1 = size(nsigma%f,1)
         n2 = size(nsigma%f,2)
         nstm = Size(udvst, 1)
         allocate(nsigma_old)
         call nsigma_old%make(n1, n2)
         Allocate ( det_vec_old(ndim,n_fl), det_vec_new(ndim,n_fl), det_vec_test(ndim,n_fl) )
         Allocate ( phase_det_new(n_fl), phase_det_old(n_fl) )
         l_test = .false.
         ! Set old weight.
         storage = "Full"
         Call compute_fermion_det(phase_det_old,det_vec_old, udvl, udvst, stab_nt, storage)
         If (l_test) then
            ! Testing
            Do nf = 1,n_fl
               if (projector) then
                  CALL udvr(nf)%reset('r',wf_r(nf)%P)
               else
                  CALL udvr(nf)%reset('r')
               endif
            Enddo
            nvar = 1
            phase = cmplx(1.d0,0.d0,kind(0.d0))
            do nf = 1,n_fl
               CALL cgr(z, nvar, gr(:,:,nf), udvr(nf), udvl(nf))
               phase = phase*z
            Enddo
            call op_phase(phase,op_v,nsigma,n_sun)
            Do nf = 1,n_fl
               Call det_c_lu(gr(:,:,nf),det_vec_test(:,nf),ndim)
               z = phase_det_old(nf)
               ratio_2_test=0.d0
               DO i = 1,ndim
                  z = z*det_vec_test(i,nf)/abs(det_vec_test(i,nf))
                  ratio_2_test=ratio_2_test+log(abs(det_vec_test(i,nf)))+det_vec_old(i,nf)
               Enddo
               z=z*cmplx(exp(ratio_2_test),0.d0,kind(0.d0))
               Write(6,*) 'Testing weight: ', z
               if(abs(ratio_2_test)>650) write(6,*) "Weight is about to reach double underflow!"
            Enddo
         Endif
         ! Store old configuration
         nsigma_old%f = nsigma%f
         nsigma_old%t = nsigma%t
         ! Phase_old, Phase_det_old and Det_vec_old  are all set.
         nc = 0
         Do n = 1,n_global
            ! Draw a new spin configuration. This is provided by the user in the Hamiltonian module
            ! Note that nsigma is a variable in the module Hamiltonian
            Call global_move(t0_proposal_ratio,nsigma_old,size_clust)
            If (t0_proposal_ratio > 1.d-24) then
               nc = nc + 1
               ! Compute the new Green function
               storage = "Empty"
               Call compute_fermion_det(phase_det_new,det_vec_new, udvl, udvst, stab_nt, storage)
               ratiotot = compute_ratio_global(phase_det_old, phase_det_new, &
                    &                          det_vec_old, det_vec_new, nsigma_old, t0_proposal_ratio, ratio)
               !Write(6,*) 'Ratio_global: ', Ratiotot
               weight = abs(  real(Phase_old * Ratiotot, kind=kind(0.d0))/real(Phase_old,kind=Kind(0.d0)) )
               z = phase_old * ratiotot/abs(ratiotot)
               Call control_precisionp_glob(z,phase_new)
               !Write(6,*) Z, Phase_new
               toggle = .false.
               if ( weight > ranf_wrap() )  Then
                  toggle = .true.
                  phase_old     = phase_new
                  phase_det_old = phase_det_new
                  nsigma_old%t    = nsigma%t
                  nsigma_old%f    = nsigma%f
                  det_vec_old     = det_vec_new
               else
                  nsigma%t = nsigma_old%t
                  nsigma%f = nsigma_old%f
               endif
               Call control_upgrade_glob(toggle,size_clust)
            endif
         Enddo
         If (nc > 0 ) then
            If (.not.toggle) then
               DO nf = 1,n_fl
                 if (projector) then
                   CALL udvl(nf)%reset('l',wf_l(nf)%P)
                 else
                   CALL udvl(nf)%reset('l')
                 endif
               ENDDO
               DO nst = nstm-1,1,-1
                  nt1 = stab_nt(nst+1)
                  nt  = stab_nt(nst  )
                  !Write(6,*) NT1,NT, NST
                  CALL wrapul(nt1,nt, udvl)
                  Do nf = 1,n_fl
                     udvst(nst, nf) = udvl(nf)
                  ENDDO
               ENDDO
               nt1 = stab_nt(1)
               CALL wrapul(nt1,0, udvl)
            Endif
            !Compute the Green functions so as to provide correct starting point for the sequential updates.
            nvar  = 1
            phase = cmplx(1.d0,0.d0,kind(0.d0))
            do nf = 1,n_fl
               CALL cgr(z, nvar, gr(:,:,nf), udvr(nf), udvl(nf))
               phase = phase*z
            Enddo
            call op_phase(phase,op_v,nsigma,n_sun)
         endif
         call nsigma_old%clear
         deallocate(nsigma_old)
         Deallocate ( det_vec_old  , det_vec_new, det_vec_test  )
         Deallocate ( phase_det_new, phase_det_old )
npbc_tempering()
integer function global_mod::npbc_tempering (integer, intent(in) n, integer, intent(in) Isize)
Periodic boundary conditions required to defined master and slave for the
tempering.
Parameters
[in] isize
Author
Fakher Assaad
Parameters
[in] n
Author
Fakher Assaad
Periodic boundary conditions required to defined master and slave for the
tempering
Definition at line 963 of file Global_mod.f90.
Referenced by exchange_step().
 !--------------------------------------------------------------------
 !--------------------------------------------------------------------
         implicit none
         Integer,  INTENT(IN)   :: Isize,n
         npbc_tempering = n
         if (  npbc_tempering < 0       ) npbc_tempering = npbc_tempering +  isize
         if (  npbc_tempering > isize -1) npbc_tempering = npbc_tempering -  isize
Variable Documentation
tempering_acceptance
type (obser_vec), private global_mod::tempering_acceptance private
Definition at line 55 of file Global_mod.f90.
Referenced by global_tempering_init_obs(), global_tempering_obser(), global_tempering_pr(), and global_tempering_setup().
       type(obser_vec ),  private  ::   tempering_acceptance