ALF: tau_p_mod Module Reference
tau_p_mod Module Reference
This module handles calculation of imagimary time displaced Green functions and
calls the routine ObserT.f90 in the Hamiltonian module, so as to compute user defined time dispalced correlations functions.
Functions/Subroutines
subroutine tau_p (udvl, udvr, udvst, GR, PHASE, NSTM, STAB_NT, NST)
Detailed Description
This module handles calculation of imagimary time displaced Green functions and
calls the routine ObserT.f90 in the Hamiltonian module, so as to compute user defined time dispalced correlations functions.
Author
ALF-project This modules is for the projector code.
Function/Subroutine Documentation
tau_p()
subroutine tau_p_mod::tau_p (class(udv_state), dimension(:), intent(in), allocatable udvl, class(udv_state), dimension(:), intent(in), allocatable udvr, class(udv_state), dimension(:,:), intent(in), allocatable udvst, complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) GR, complex (kind=kind(0.d0)), intent(in) PHASE, integer, intent(in) NSTM, integer, dimension(0:nstm), intent(in) STAB_NT, integer, intent(in) NST)
Definition at line 55 of file tau_p.f90.
References cgrp(), hop_mod::hop_mod_symm(), hamiltonian::ltrot, hamiltonian::obsert(), tau_m_mod::propr(), tau_m_mod::proprm1(), hamiltonian::symm, hamiltonian::thtrot, and wrapur().
Referenced by main().
          Implicit none
          Interface
             SUBROUTINE cgrp(PHASE, GRUP, udvr, udvl)
               Use udv_state_mod
               use mymats
               CLASS(UDV_State), INTENT(IN) :: udvl, udvr
               COMPLEX (Kind=Kind(0.d0)), Dimension(:,:), Intent(INOUT) :: GRUP
               COMPLEX (Kind=Kind(0.d0)), Intent(INOUT) :: PHASE
             End Subroutine cgrp
             SUBROUTINE wrapur(NTAU, NTAU1, UDVR)
               Use hamiltonian
               Use udv_wrap_mod
               Use udv_state_mod
               Implicit None
               CLASS(UDV_State), intent(inout) :: UDVR(N_FL)
               Integer :: NTAU1, NTAU
             END SUBROUTINE wrapur
          End Interface
         ! Storage is full with U^{<} (left)  propagations.
         Integer, Intent(In) :: NSTM, NST
         CLASS(UDV_State), Dimension(:), ALLOCATABLE, INTENT(IN) :: udvl, udvr
         CLASS(UDV_State), Dimension(:,:), ALLOCATABLE, INTENT(IN) :: udvst
         Complex (Kind=Kind(0.d0)), Intent(in) :: GR(NDIM,NDIM,N_FL),  Phase
         Integer, Intent(In) :: STAB_NT(0:NSTM)
 !       Local.
         CLASS(UDV_State), Dimension(:), ALLOCATABLE :: udvr_local
         Complex (Kind=Kind(0.d0)) :: DETZ, ZK, DET1(2)
         Complex (Kind=Kind(0.d0)), Dimension(:,:,:), Allocatable  ::  GRUPB, GRUP
         Complex (Kind=Kind(0.d0)), Dimension(:,:,:), Allocatable  ::  G00UP, G0TUP, GT0UP,  GTTUP
         Complex (Kind=Kind(0.d0)), Dimension(:,:,:), Allocatable  ::  G00UP_T, G0TUP_T, GT0UP_T,  GTTUP_T
         Complex (Kind=Kind(0.d0)), allocatable  :: TEMP(:,:), TMPUP(:,:)
         Real    (Kind=kind(0.d0))  :: XMEAN_DYN, XMAX_DYN
         Integer :: NTAUIN,  NTDM,  LFAM, NFAM, N_Part,  LQ , I, NCON, NF, NFLAG, NL, NT1, NT_ST, NT, NTAU, NTAU1,n
         Real (Kind=Kind(0.d0)):: XMEAN, XMAX
         lq = ndim
         nt_st=0
         do while(stab_nt(nt_st)<=thtrot+1)
            nt_st=nt_st+1
         enddo
         ALLOCATE (  grupb(lq,lq,n_fl), grup(lq,lq,n_fl), g00up(lq,lq,n_fl), g0tup(lq,lq,n_fl), &
              &      gt0up(lq,lq,n_fl),  gttup(lq,lq,n_fl), temp(lq,lq), udvr_local(n_fl) )
         If (symm) Then
            Allocate ( g00up_t(lq,lq,n_fl), g0tup_t(lq,lq,n_fl), gt0up_t(lq,lq,n_fl),  gttup_t(lq,lq,n_fl) )
         endif
         do nf=1,n_fl
            call udvr_local(nf)%alloc(ndim,udvr(nf)%N_part)
            udvr_local(nf)=udvr(nf)
         enddo
         Call wrapur(stab_nt(nst), stab_nt(nt_st), udvr_local)
         grup=gr
         do nt=stab_nt(nst)+1,thtrot+1
            CALL proprm1(grup,nt)
            CALL propr  (grup,nt)
         enddo
         grupb = grup
         do nf=1,n_fl
            do i=1,ndim
               grupb(i,i,nf)=grupb(i,i,nf)-1.d0
            enddo
         enddo
         g00up = grup
         gttup = grup
         gt0up = grup
         g0tup = grupb
         nt1   = 0
         If (symm) then
            Call hop_mod_symm(g00up_t,g00up)
            Call hop_mod_symm(gttup_t,gttup)
            Call hop_mod_symm(g0tup_t,g0tup)
            Call hop_mod_symm(gt0up_t,gt0up)
            CALL obsert (nt1,gt0up_t,g0tup_t,g00up_t,gttup_t,phase)
         else
            CALL obsert (nt1,gt0up,g0tup,g00up,gttup,phase)
         endif
         ! WRITE(6,*) 'Starting Dyn'
         DO nt = thtrot+1, ltrot-thtrot
            ! UR is on time slice NT
            ntau = nt - thtrot -1
            !#ifdef test
            !            WRITE(6,*) 'Ntau: ', NTAU, "on slice",NT
            !#endif
            IF ( nt.EQ.stab_nt(nt_st) .and. ntau/=0) THEN
               !               write(*,*) "stabilization at ",stab_nt(NT_st)
               do nf=1,n_fl
                  !                   write(*,*) "udvl side:",udvst(nt_st,nf)%side
                  CALL cgrp(detz, grup(:,:,nf), udvr_local(nf), udvst(nt_st,nf))
               enddo
               Call wrapur(stab_nt(nt_st), stab_nt(nt_st+1), udvr_local)
               nt_st=nt_st+1
               grupb = -grup
               do nf=1,n_fl
                  do i=1,ndim
                     grupb(i,i,nf)=grupb(i,i,nf)+1
                  enddo
               enddo
               xmax  = 0.d0
               xmean = 0.d0
               do nf=1,n_fl
                  CALL compare (gttup(:,:,nf), grup(:,:,nf), xmax,xmean)
                  IF (xmax.GT.xmax_dyn) xmax_dyn = xmax
                  xmean_dyn = xmean_dyn + xmean
               enddo
               !#ifdef test
               !                  WRITE(6,*) 'Compare up: ',XMEAN/Real(N_FL*LQ*LQ,Kind(0.d0)), XMAX
               !#endif
               gttup = grup
               do nf=1,n_fl
                  CALL mmult(temp,grup(:,:,nf),gt0up(:,:,nf))
                  gt0up(:,:,nf) = temp
                  CALL mmult(temp,g0tup(:,:,nf),grupb(:,:,nf))
                  g0tup(:,:,nf) = temp
               enddo
            ENDIF                ! Ortho.
            ! Now propagate to Ntau + 1 and call OBSERT.
            nt1 = nt + 1
            !Write(6,*) "CALL PROPR  (GT0UP,NT1)"
            CALL propr  (gt0up,nt1)
            !Write(6,*) "Ret"
            !Write(6,*) " CALL PROPRM1(G0TUP,NT1)"
            CALL proprm1(g0tup,nt1)
            !Write(6,*) "Ret"
            !Write(6,*) "CALL PROPRM1(GTTUP,NT1)"
            CALL proprm1(gttup,nt1)
            !Write(6,*) "Ret"
            !Write(6,*) "CALL PROPR  (GTTUP,NT1)"
            CALL propr  (gttup,nt1)
            !Write(6,*) "Ret"
            ntau1 = ntau + 1
            If (symm) then
               Call hop_mod_symm(g00up_t,g00up)
               Call hop_mod_symm(gttup_t,gttup)
               Call hop_mod_symm(g0tup_t,g0tup)
               Call hop_mod_symm(gt0up_t,gt0up)
               Call obsert (ntau1,gt0up_t,g0tup_t,g00up_t,gttup_t,phase)
            else
               Call obsert (ntau1,gt0up,g0tup,g00up,gttup,phase)
            endif
         ENDDO
         Do nf=1,n_fl
            call udvr_local(nf)%dealloc
         enddo
         DEALLOCATE (grupb, grup, g00up, g0tup, gt0up,  gttup, temp, udvr_local)
         If (symm) Then
            Deallocate ( g00up_t, g0tup_t, gt0up_t,  gttup_t )
         endif
         !         DEALLOCATE (TMPUP, V, D  )
         !         DEALLOCATE (ULR , ULRINV )
         !         stop
         RETURN