ALF: udv_wrap_mod Module Reference
udv_wrap_mod Module Reference
This module contains two version of the stabilization.
Functions/Subroutines
subroutine udv_wrap_pivot (A, U, D, V, NCON, N1, N2)
subroutine udv_wrap (A, U, D, V, NCON)
Detailed Description
This module contains two version of the stabilization.
Author
ALF-project To switch between the two schemes you should define STAB1 in the set_env.sh file. The defaut scheme is quick and gernerically works better.
Function/Subroutine Documentation
udv_wrap()
subroutine udv_wrap_mod::udv_wrap (complex (kind=kind(0.d0)), dimension(:,:), intent(in) A, complex (kind=kind(0.d0)), dimension(:,:), intent(inout) U, complex (kind=kind(0.d0)), dimension(:), intent(inout) D, complex (kind=kind(0.d0)), dimension(:,:), intent(inout) V, integer, intent(in) NCON)
Definition at line 213 of file UDV_WRAP.f90.
Referenced by cgr2(), cgr2_1(), and udv_wrap_pivot().
 #ifdef MPI
        USE mpi
 #endif
        Implicit None
        COMPLEX (Kind=Kind(0.d0)), INTENT(IN),    DIMENSION(:,:) :: A
        COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), DIMENSION(:,:) :: U,V
        COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), DIMENSION(:) :: D
        INTEGER, INTENT(IN) :: NCON
        !Local
        Complex (Kind=Kind(0.d0)), Allocatable ::  A1(:,:),U1(:,:)
        Integer :: N,I,J
        character (len=64) :: file_sr, File
 #ifdef MPI
        INTEGER :: Isize, Irank,Ierr
        CALL mpi_comm_size(mpi_comm_world,isize,ierr)
        CALL mpi_comm_rank(mpi_comm_world,irank,ierr)
 #endif
        file_sr = "SDV"
 #ifdef MPI
        file = file_i(file_sr, irank)
 #else
        file = file_sr
 #endif
        CALL qr(a,u,v,ncon)
        n = Size(a,1)
        Allocate (a1(n,n),u1(n,n))
        !DO I = 1,N
        !   DO J = 1,N
        !      WRITE(6,*) I,J,V(I,J)
        !   ENDDO
        !ENDDO
        a1 = v
        CALL svd(a1,u1,d,v,ncon)
        Call mmult(a1,u,u1)
        u = a1
udv_wrap_pivot()
subroutine udv_wrap_mod::udv_wrap_pivot (complex (kind=kind(0.d0)), dimension(:,:), intent(in) A, complex (kind=kind(0.d0)), dimension(:,:), intent(inout) U, complex (kind=kind(0.d0)), dimension(:), intent(inout) D, complex (kind=kind(0.d0)), dimension(:,:), intent(inout) V, integer, intent(in) NCON, integer, intent(in) N1, integer, intent(in) N2)
Definition at line 55 of file UDV_WRAP.f90.
References qdrp_mod::pivot_phase(), and udv_wrap().
Referenced by cgr(), global_mod::compute_fermion_det(), wrapul(), and wrapur().
         Use qdrp_mod
        Implicit NONE
        COMPLEX (Kind=Kind(0.d0)), INTENT(IN),    DIMENSION(:,:) :: A
        COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), DIMENSION(:,:) :: U,V
        COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), DIMENSION(:) :: D
        INTEGER, INTENT(IN) :: NCON
        INTEGER, INTENT(IN) :: N1,N2
        ! Locals
        REAL (Kind=Kind(0.d0)) :: VHELP(N2), XNORM(N2), XMAX, XMEAN
        INTEGER :: IVPT(N2), IVPTM1(N2), I, J, K, IMAX
        COMPLEX (Kind=Kind(0.d0))  :: A1(N1,N2), A2(N1,N2), V1(N2,N2), phase, beta
        DO i = 1,n2
           xnorm(i) = 0.d0
           DO j = 1,n1
              xnorm(i) = xnorm(i) + dble( a(j,i) * conjg( a(j,i) ) )
           ENDDO
        ENDDO
        vhelp = xnorm
        DO i = 1,n2
           xmax = vhelp(1)
           imax = 1
           DO j = 2,n2
              IF (vhelp(j).GT.xmax)  THEN
                 imax = j
                 xmax = vhelp(j)
              ENDIF
           ENDDO
           vhelp(imax) = -1.d0
           ivptm1(imax)=  i
           ivpt(i) = imax
        ENDDO
        DO i = 1,n2
           k = ivpt(i)
           a1(:, i) = a(:, k)
        ENDDO
        CALL udv_wrap(a1,u,d,v,ncon)
        v1 = v
        phase=det_c(v1,n2)
        Call pivot_phase(phase,ivpt,size(d,1))
        beta=1/phase
        !scale first row of R with 1/phase to set Det(R)=1 [=Det(V)]
        call zscal(size(v,2),beta,v(1,1),size(v,1))
        ! scale first column of U to correct the scaling in V such that UDV is not changed
        call zscal(size(u,1),phase,u(1,1),1)
        v1 = v
        DO i = 1,n2
           k = ivptm1(i)
           v(:, i) = v1(:,k)
        ENDDO
        IF (ncon == 1) THEN
           !Check the result  A = U D V
           DO j = 1,n2
              a1(:, j) = d * v(:, j)
           ENDDO
           Write(6,*) 'Here'
           Call mmult (a2,u,a1)
           CALL compare(a,a2,xmax,xmean)
           Write (6,*) 'Check afer  Pivoting', xmax
        ENDIF