ALF: hop_mod Module Reference
hop_mod Module Reference
This module computes and stores the exponential of the hopping matrix. It also provide routines to carry out multiplications with , , , and . The last equality are important for the symmetric Trotter option. (See variable: Symm in the Hamiltonian module)
Functions/Subroutines
subroutine hop_mod_init
This functions sets up the exponentiated matrices.
subroutine hop_mod_mmthr (In, nf)
subroutine hop_mod_mmthr_1d2 (In, nf)
subroutine hop_mod_mmthr_m1 (In, nf)
subroutine hop_mod_mmthl (In, nf)
subroutine hop_mod_mmthlc (In, nf)
subroutine hop_mod_mmthl_m1 (In, nf)
subroutine hop_mod_mmthl_m1_1d2 (In, nf)
subroutine hop_mod_symm (Out, In)
Out = exp(-Delta tau /2 T) In exp(Delta tau /2 T)
Variables
complex(kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private exp_t
complex(kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private exp_t_m1
complex(kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private exp_t_1d2
complex(kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private exp_t_m1_1d2
complex(kind=kind(0.d0)), dimension(:,:), allocatable, private u_hlp
complex(kind=kind(0.d0)), dimension(:,:), allocatable, private u_hlp1
complex(kind=kind(0.d0)), dimension(:,:), allocatable, private v_hlp
complex(kind=kind(0.d0)), dimension(:,:), allocatable, private v_hlp1
integer, save, private ncheck
integer, save, private ndim_hop
real(kind=kind(0.d0)), save, private zero
Detailed Description
This module computes and stores the exponential of the hopping matrix. It also provide routines to carry out multiplications with , , , and . The last equality are important for the symmetric Trotter option. (See variable: Symm in the Hamiltonian module)
Author
ALF-project
Function/Subroutine Documentation
hop_mod_init()
subroutine hop_mod::hop_mod_init ()
This functions sets up the exponentiated matrices.
Author
ALF-project We symmetrize the upper part of those matrices.
Definition at line 70 of file Hop_mod.f90.
References exp_t, exp_t_1d2, exp_t_m1, exp_t_m1_1d2, hamiltonian::n_fl, ncheck, hamiltonian::ndim, ndim_hop, hamiltonian::op_t, u_hlp, u_hlp1, v_hlp, v_hlp1, and zero.
Referenced by main().
           Implicit none
           Integer :: nc, nf, i,j
           Complex (Kind=Kind(0.d0)) :: g
           ncheck = size(op_t,1)
           If ( size(op_t,2) /= n_fl ) then
              Write(6,*) 'Error in the number of flavors.'
              stop
           Endif
           ndim_hop = op_t(1,1)%N
           !Write(6,*) 'In Hop_mod: ', Ndim, Ndim_hop, Ncheck
           Do nc = 1, ncheck
              do nf = 1,n_fl
                 if ( ndim_hop /= op_t(nc,nf)%N ) Then
                    Write(6,*)  'Different size of Hoppings not  implemented '
                    stop
                 endif
              enddo
           enddo
           Allocate ( exp_t(ndim_hop,ndim_hop,ncheck,n_fl) )
           Allocate ( exp_t_m1(ndim_hop,ndim_hop,ncheck,n_fl) )
           Allocate ( exp_t_1d2(ndim_hop,ndim_hop,ncheck,n_fl) )
           Allocate ( exp_t_m1_1d2(ndim_hop,ndim_hop,ncheck,n_fl) )
           Allocate ( v_hlp(ndim_hop,ndim) )
           Allocate ( v_hlp1(ndim_hop,ndim) )
           Allocate ( u_hlp(ndim, ndim_hop) )
           Allocate ( u_hlp1(ndim, ndim_hop) )
           exp_t = cmplx(0.d0, 0.d0, kind(0.d0))
           exp_t_m1 = cmplx(0.d0, 0.d0, kind(0.d0))
           do nf = 1,n_fl
              do nc = 1,ncheck
                 g = op_t(nc,nf)%g
                 Call  op_exp(g,op_t(nc,nf),exp_t(:,:,nc,nf))
                 g = -op_t(nc,nf)%g
                 Call  op_exp(g,op_t(nc,nf),exp_t_m1(:,:,nc,nf))
                 g = op_t(nc,nf)%g/2.d0
                 Call  op_exp(g,op_t(nc,nf),exp_t_1d2(:,:,nc,nf))
                 g = -op_t(nc,nf)%g/2.d0
                 Call  op_exp(g,op_t(nc,nf),exp_t_m1_1d2(:,:,nc,nf))
                 ! symmetrize the upper part of Exp_T and Exp_T_M1
                 DO i = 1, ndim_hop
                    DO j = i, ndim_hop
                       exp_t(i, j, nc, nf) = (exp_t(i, j, nc, nf) + conjg(exp_t(j, i, nc, nf)))/2.d0
                       exp_t_m1(i, j, nc, nf) = (exp_t_m1(i, j, nc, nf) + conjg(exp_t_m1(j, i, nc, nf)))/2.d0
                    ENDDO
                 ENDDO
              enddo
           enddo
           zero = 1.e-12
hop_mod_mmthl()
subroutine hop_mod::hop_mod_mmthl (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer nf)
Definition at line 203 of file Hop_mod.f90.
References exp_t, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by wrapgrdo(), wrapgr_mod::wrapgrdo(), and wrapul().
           ! InOut:  In = IN * e^{ -dtau T }
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer :: nf
           !Local
           Integer :: nc, N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  1, ncheck
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('R','U',ndim_hop,n1,n2,exp_t(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_mmthl_m1()
subroutine hop_mod::hop_mod_mmthl_m1 (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer nf)
Definition at line 253 of file Hop_mod.f90.
References exp_t_m1, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by tau_m_mod::proprm1(), wrapgrup(), and wrapgr_mod::wrapgrup().
           ! InOut:  In = IN * e^{ dtau T }
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer :: nf
           !Local
           Integer :: nc, N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  ncheck,1,-1
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('R','U',ndim_hop,n1,n2,exp_t_m1(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_mmthl_m1_1d2()
subroutine hop_mod::hop_mod_mmthl_m1_1d2 (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer nf)
Definition at line 279 of file Hop_mod.f90.
References exp_t_m1_1d2, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by hop_mod_symm().
           ! InOut:  In = IN * e^{ dtau T/2 }
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer :: nf
           !Local
           Integer :: nc, N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  ncheck,1,-1
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('R','U',ndim_hop,n1,n2,exp_t_m1_1d2(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_mmthlc()
subroutine hop_mod::hop_mod_mmthlc (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer nf)
Definition at line 228 of file Hop_mod.f90.
References exp_t, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by wrapul().
           ! InOut:  In = IN * e^{ -dtau T }
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer :: nf
           !Local
           Integer :: nc, N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  1, ncheck
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('L','U',ndim_hop,n1,n2,exp_t(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_mmthr()
subroutine hop_mod::hop_mod_mmthr (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer, intent(in) nf)
Definition at line 131 of file Hop_mod.f90.
References exp_t, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by tau_m_mod::propr(), wrapgrup(), wrapgr_mod::wrapgrup(), and wrapur().
           ! InOut:  In = e^{ -dtau T }.IN
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer, intent(IN) :: nf
           !Local
           Integer :: nc, N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  ncheck,1,-1
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('L','U',ndim_hop,n1,n2,exp_t(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_mmthr_1d2()
subroutine hop_mod::hop_mod_mmthr_1d2 (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer, intent(in) nf)
Definition at line 154 of file Hop_mod.f90.
References exp_t_1d2, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by hop_mod_symm().
           ! InOut:  In = e^{ -dtau T /2 }.IN
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer, intent(IN) :: nf
           !Local
           Integer :: nc, N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  ncheck,1,-1
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('L','U',ndim_hop,n1,n2,exp_t_1d2(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_mmthr_m1()
subroutine hop_mod::hop_mod_mmthr_m1 (complex (kind=kind(0.d0)), dimension(:,:), intent(inout) In, integer nf)
Definition at line 178 of file Hop_mod.f90.
References exp_t_m1, ncheck, ndim_hop, hamiltonian::op_t, and zero.
Referenced by wrapgrdo(), and wrapgr_mod::wrapgrdo().
           ! InOut:  In = e^{  dtau T }.IN
           Implicit none
           Complex (Kind=Kind(0.d0)), intent(INOUT)  :: IN(:,:)
           Integer :: nf
           !Local
           Integer :: nc , N1, N2
           n1=size(in,1)
           n2=size(in,2)
           do nc =  1,ncheck
              If ( dble( op_t(nc,nf)%g*conjg(op_t(nc,nf)%g) ) > zero ) then
                 call zslhemm('L','U',ndim_hop,n1,n2,exp_t_m1(:,:,nc,nf),op_t(nc,nf)%P,in)
              Endif
           Enddo
hop_mod_symm()
subroutine hop_mod::hop_mod_symm (complex (kind=kind(0.d0)), dimension(:,:,:), intent(out) Out, complex (kind=kind(0.d0)), dimension(:,:,:), intent(in) In)
Out = exp(-Delta tau /2 T) In exp(Delta tau /2 T)
Author
ALF-project
Definition at line 330 of file Hop_mod.f90.
References hop_mod_mmthl_m1_1d2(), and hop_mod_mmthr_1d2().
Referenced by main(), tau_m_mod::tau_m(), and tau_p_mod::tau_p().
           Implicit none
           COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:), Intent(Out):: Out
           COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:), Intent(IN):: In
           Integer :: nf
           out = in
           Do nf = 1, size(in,3)
              Call hop_mod_mmthr_1d2   (out(:,:,nf), nf )
              Call hop_mod_mmthl_m1_1d2(out(:,:,nf), nf )
           enddo
Variable Documentation
exp_t
complex (kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private hop_mod::exp_t private
Definition at line 53 of file Hop_mod.f90.
Referenced by hop_mod_init(), hop_mod_mmthl(), hop_mod_mmthlc(), and hop_mod_mmthr().
       Complex (Kind=Kind(0.d0)), allocatable, private :: Exp_T(:,:,:,:), Exp_T_M1(:,:,:,:)
exp_t_1d2
complex (kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private hop_mod::exp_t_1d2 private
Definition at line 54 of file Hop_mod.f90.
Referenced by hop_mod_init(), and hop_mod_mmthr_1d2().
       Complex (Kind=Kind(0.d0)), allocatable, private :: Exp_T_1D2(:,:,:,:), Exp_T_M1_1D2(:,:,:,:)
exp_t_m1
complex (kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private hop_mod::exp_t_m1 private
Definition at line 53 of file Hop_mod.f90.
Referenced by hop_mod_init(), hop_mod_mmthl_m1(), and hop_mod_mmthr_m1().
exp_t_m1_1d2
complex (kind=kind(0.d0)), dimension(:,:,:,:), allocatable, private hop_mod::exp_t_m1_1d2 private
Definition at line 54 of file Hop_mod.f90.
Referenced by hop_mod_init(), and hop_mod_mmthl_m1_1d2().
ncheck
integer, save, private hop_mod::ncheck private
Definition at line 56 of file Hop_mod.f90.
Referenced by hop_mod_init(), hop_mod_mmthl(), hop_mod_mmthl_m1(), hop_mod_mmthl_m1_1d2(), hop_mod_mmthlc(), hop_mod_mmthr(), hop_mod_mmthr_1d2(), and hop_mod_mmthr_m1().
       Integer, private, save ::  Ncheck, Ndim_hop
ndim_hop
integer, save, private hop_mod::ndim_hop private
Definition at line 56 of file Hop_mod.f90.
Referenced by hop_mod_init(), hop_mod_mmthl(), hop_mod_mmthl_m1(), hop_mod_mmthl_m1_1d2(), hop_mod_mmthlc(), hop_mod_mmthr(), hop_mod_mmthr_1d2(), and hop_mod_mmthr_m1().
u_hlp
complex (kind=kind(0.d0)), dimension(:,:), allocatable, private hop_mod::u_hlp private
Definition at line 55 of file Hop_mod.f90.
Referenced by hop_mod_init().
       Complex (Kind=Kind(0.d0)), allocatable, private :: U_HLP(:,:), U_HLP1(:,:),  V_HLP(:,:), V_HLP1(:,:)
u_hlp1
complex (kind=kind(0.d0)), dimension(:,:), allocatable, private hop_mod::u_hlp1 private
Definition at line 55 of file Hop_mod.f90.
Referenced by hop_mod_init().
v_hlp
complex (kind=kind(0.d0)), dimension(:,:), allocatable, private hop_mod::v_hlp private
Definition at line 55 of file Hop_mod.f90.
Referenced by hop_mod_init().
v_hlp1
complex (kind=kind(0.d0)), dimension(:,:), allocatable, private hop_mod::v_hlp1 private
Definition at line 55 of file Hop_mod.f90.
Referenced by hop_mod_init().
zero
real (kind=kind(0.d0)), save, private hop_mod::zero private
Definition at line 57 of file Hop_mod.f90.
Referenced by hop_mod_init(), hop_mod_mmthl(), hop_mod_mmthl_m1(), hop_mod_mmthl_m1_1d2(), hop_mod_mmthlc(), hop_mod_mmthr(), hop_mod_mmthr_1d2(), hop_mod_mmthr_m1(), and main().
       Real (Kind=Kind(0.d0)), private, save  :: Zero