ALF: qdrp_mod Module Reference
qdrp_mod Module Reference
This constructs a decompostion Mat = Q D R P^* using a pivoted QR decomposition.
Functions/Subroutines
subroutine qdrp_decompose (Ndim, N_part, Mat, D, IPVT, TAU, WORK, LWORK)
! This constructs a decompostion Mat = Q D R P^* using a pivoted QR decomposition
subroutine pivot_phase (Phase, IPVT, N_size)
Detailed Description
This constructs a decompostion Mat = Q D R P^* using a pivoted QR decomposition.
Author
ALF-project
Function/Subroutine Documentation
pivot_phase()
subroutine qdrp_mod::pivot_phase (complex(kind=kind(0.d0)), intent(inout) Phase, integer, dimension(:), intent(in) IPVT, integer, intent(in) N_size)
Definition at line 104 of file QDRP_decompose.f90.
Referenced by udv_state_mod::decompose_udv_state(), and udv_wrap_mod::udv_wrap_pivot().
         Implicit none
         COMPLEX(kind=kind(0.d0)), Intent(INOUT) :: Phase
         Integer, Dimension(:), Intent(IN)       :: IPVT
         Integer,               Intent(IN)       :: N_size
         Integer:: i, next, L, VISITED(N_size)
         visited=0
         do i = 1, n_size
             if (visited(i) .eq. 0) then
                 next = i
                 l = 0
                 do while (visited(next) .eq. 0)
                  l = l + 1
                  visited(next) = 1
                  next = ipvt(next)
                 enddo
                 if(mod(l, 2) .eq. 0) then
                     phase = -phase
                 endif
             endif
         enddo
qdrp_decompose()
subroutine qdrp_mod::qdrp_decompose (integer, intent(in) Ndim, integer, intent(in) N_part, complex(kind=kind(0.d0)), dimension(:,:), intent(inout) Mat, complex(kind=kind(0.d0)), dimension(:), intent(inout) D, integer, dimension(:), intent(inout), allocatable IPVT, complex(kind=kind(0.d0)), dimension(:), intent(inout), allocatable TAU, complex(kind=kind(0.d0)), dimension(:), intent(inout), allocatable WORK, integer, intent(inout) LWORK)
! This constructs a decompostion Mat = Q D R P^* using a pivoted QR decomposition
Author
ALF-project
Parameters
Ndim[in] The size of the involved matrices
Mat[inout] The matrix that we want to decompose. The Householder reflectors and the upper triangular matrix are returned in Mat on exit
D[inout] The diagonal elements
IPVT[inout] A Pivoting vector that collects the permutations. Can be used by ?LAPMR and ?LAPMT
TAU[inout] The scalar factors for the Householder decomposition
WORK[inout] work memory. We query and allocate it in this routine. Needs to be deallocated outside.
LWORK[inout] optimal size of the work memory.
Definition at line 61 of file QDRP_decompose.f90.
Referenced by cgr(), and udv_state_mod::decompose_udv_state().
 Implicit None
 Integer, intent(in) :: Ndim
 Integer, intent(in) :: N_part
 Integer, intent(inout) :: LWORK
 Integer, Dimension(:), intent(inout), Allocatable :: IPVT
 COMPLEX(Kind=Kind(0.d0)), Dimension(:,:), Intent(inout) :: Mat
 COMPLEX(Kind=Kind(0.d0)), Dimension(:), Intent(inout) :: D
 COMPLEX(Kind=Kind(0.d0)), Dimension(:), Intent(inout), Allocatable :: TAU
 COMPLEX(Kind=Kind(0.d0)), Dimension(:), Intent(INOUT), Allocatable :: WORK
 COMPLEX(Kind=Kind(0.d0)), Dimension(:), Allocatable :: RWORK
 COMPLEX(Kind=Kind(0.d0)) :: Z
 Integer :: info, i, j
 Real(Kind=Kind(0.d0)) :: X
         ALLOCATE(rwork(2*ndim))
         ! Query optimal amount of memory
         call zgeqp3(ndim, n_part, mat(1,1), ndim, ipvt, tau(1), z, -1, rwork(1), info)
         lwork = int(dble(z))
         ALLOCATE(work(lwork))
         ! QR decomposition of Mat with full column pivoting, Mat * P = Q * R
         call zgeqp3(ndim, n_part, mat(1,1), ndim, ipvt, tau(1), work(1), lwork, rwork(1), info)
         DEALLOCATE(rwork)
         ! separate off D
         do i = 1, n_part
         ! plain diagonal entry
             x = abs(mat(i, i))
 !             ! a inf-norm
 !             X = TPUP(i, i+izamax(Ndim+1-i, TPUP(i, i), Ndim)-1)
 !             ! another inf-norm
 !             X = TPUP(i, i-1+izmax1(Ndim+1-i, TPUP(i, i), Ndim))
 !             ! 1-norm
 !            X = DZSUM1(N_size+1-i, TPUP(i, i), N_size)
             ! 2-norm
 !            X = DZNRM2(N_size+1-i, TPUP(i, i), N_size)
             d(i) = x
             do j = i, n_part
                 mat(i, j) = mat(i, j) / x
             enddo
         enddo