ALF: tau_m_mod Module Reference
tau_m_mod Module Reference
This module handles calculation of imagimary time displaced Green functions and
calls the routine ObserT.f90 in the Hamiltonian module, so as to compute the defined time dispalced correlations functions.
Functions/Subroutines
subroutine tau_m (udvst, GR, PHASE, NSTM, NWRAP, STAB_NT)
subroutine propr (AIN, NT)
subroutine proprm1 (AIN, NT)
Detailed Description
This module handles calculation of imagimary time displaced Green functions and
calls the routine ObserT.f90 in the Hamiltonian module, so as to compute the defined time dispalced correlations functions.
Author
ALF-project This modules is for the finite temperature code.
Function/Subroutine Documentation
propr()
subroutine tau_m_mod::propr (complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(inout) AIN, integer, intent(in) NT)
Definition at line 185 of file tau_m.f90.
References hop_mod::hop_mod_mmthr(), hamiltonian::nsigma, operator_mod::op_mmultr(), and hamiltonian::op_v.
Referenced by tau_m(), and tau_p_mod::tau_p().
            ! Ain =       B(NT-1, NT1)
            ! Aout= Ain = B(NT  , NT1)
            Implicit none
            Complex (Kind=Kind(0.D0)), intent(INOUT) :: Ain(Ndim,Ndim,N_FL)
            Integer, INTENT(IN) :: NT
            !Locals
            Integer :: nf,n
            Do nf = 1,n_fl
               Call hop_mod_mmthr(ain(:,:,nf),nf)
               Do n = 1,Size(op_v,1)
 !                  X = Phi(nsigma(n,nt),Op_V(n,nf)%type)
                  Call op_mmultr(ain(:,:,nf),op_v(n,nf),nsigma%f(n,nt),'n')
               ENDDO
            Enddo
proprm1()
subroutine tau_m_mod::proprm1 (complex (kind=kind(0.d0)), dimension(ndim, ndim, n_fl), intent(inout) AIN, integer NT)
Definition at line 209 of file tau_m.f90.
References hop_mod::hop_mod_mmthl_m1(), hamiltonian::nsigma, operator_mod::op_mmultl(), and hamiltonian::op_v.
Referenced by tau_m(), and tau_p_mod::tau_p().
            !Ain = B^{-1}(NT-1, NT1)
            !Aout= B^{-1}(NT  , NT1)
            Implicit none
            !Arguments
            Complex (Kind=Kind(0.D0)), intent(Inout) ::  AIN(Ndim, Ndim, N_FL)
            Integer :: NT
            ! Locals
            Integer :: nf, n
            do nf = 1,n_fl
               !Call MMULT(HLP4,Ain(:,:,nf),Exp_T_M1(:,:,nf) )
               Call hop_mod_mmthl_m1(ain(:,:,nf),nf)
               Do n =1,Size(op_v,1)
 !                  X = -Phi(nsigma(n,nt),Op_V(n,nf)%type)
                  Call op_mmultl(ain(:,:,nf),op_v(n,nf),-nsigma%f(n,nt),'n')
               Enddo
            enddo
tau_m()
subroutine tau_m_mod::tau_m (class(udv_state), dimension(:,:), intent(in), allocatable udvst, complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) GR, complex (kind=kind(0.d0)), intent(in) PHASE, integer, intent(in) NSTM, integer, intent(in) NWRAP, integer, dimension(0:nstm), intent(in) STAB_NT)
Definition at line 53 of file tau_m.f90.
References control::control_precision_tau(), hop_mod::hop_mod_symm(), hamiltonian::ltrot, hamiltonian::obsert(), hamiltonian::projector, propr(), proprm1(), hamiltonian::symm, hamiltonian::wf_r, and wrapur().
Referenced by main().
            Implicit none
            Interface
               SUBROUTINE wrapur(NTAU1, NTAU, udvr)
                 Use hamiltonian
                 Use udv_state_mod
                 Implicit none
                 CLASS(UDV_State), intent(inout), ALLOCATABLE, dimension(:) :: UDVr
                 Integer :: NTAU1, NTAU
               END SUBROUTINE wrapur
               SUBROUTINE cgr2_2(GRT0, GR00, GRTT, GR0T, udv2, udv1, LQ)
                 Use mymats
                 Use udv_wrap_mod
                 Use udv_state_mod
                 Implicit none
                 !  Arguments
                 Integer,  intent(in) :: LQ
                 CLASS(UDV_State), intent(in) :: udv1, udv2
                 Complex (Kind=Kind(0.d0)), intent(inout) :: GRT0(LQ,LQ), GR0T(LQ,LQ), GR00(LQ,LQ), GRTT(LQ,LQ)
               end SUBROUTINE cgr2_2
            end Interface
            Integer, Intent(In) :: NSTM, NWRAP
            CLASS(UDV_State), Dimension(:,:), ALLOCATABLE, INTENT(IN) :: udvst
            Complex (Kind=Kind(0.d0)), Intent(in) :: GR(NDIM,NDIM,N_FL),  Phase
            Integer, Intent(In) :: STAB_NT(0:NSTM)
            ! Local
            ! This could be placed as  private for the module
            Complex (Kind=Kind(0.d0))  :: GT0(NDIM,NDIM,N_FL),  G00(NDIM,NDIM,N_FL), GTT(NDIM,NDIM,N_FL), G0T(NDIM,NDIM,N_FL)
            Complex (Kind=Kind(0.d0)), Dimension(:,:,:), Allocatable  :: GT0_T,  G00_T, GTT_T, G0T_T
            CLASS(UDV_State), DIMENSION(:), ALLOCATABLE :: udvr
            Complex (Kind=Kind(0.d0))  :: HLP4(Ndim,Ndim), HLP5(Ndim,Ndim), HLP6(Ndim,Ndim)
            Complex (Kind=Kind(0.d0))  ::  Z
            Integer  ::  I, J, nf, NT, NT1, NTST, NST
            If (symm) Then
               Allocate ( g00_t(ndim,ndim,n_fl), g0t_t(ndim,ndim,n_fl), gt0_t(ndim,ndim,n_fl),  gtt_t(ndim,ndim,n_fl) )
            endif
            !Tau = 0
            Do nf = 1, n_fl
               DO j = 1,ndim
                  DO i = 1,ndim
                     z = cmplx(0.d0, 0.d0, kind(0.d0))
                     if (i == j ) z = cmplx(1.d0,0.d0,kind(0.d0))
                     g00(i,j,nf) = gr(i,j,nf)
                     gt0(i,j,nf) = gr(i,j,nf)
                     gtt(i,j,nf) = gr(i,j,nf)
                     g0t(i,j,nf) = -(z - gr(i,j,nf))
                  ENDDO
               ENDDO
            Enddo
            nt = 0
            ! In Module Hamiltonian
            If (symm) then
               Call hop_mod_symm(g00_t,g00)
               Call hop_mod_symm(gtt_t,gtt)
               Call hop_mod_symm(g0t_t,g0t)
               Call hop_mod_symm(gt0_t,gt0)
               CALL obsert(nt,  gt0_t,g0t_t,g00_t,gtt_t, phase)
            Else
               CALL obsert(nt,  gt0,g0t,g00,gtt, phase)
            Endif
            ALLOCATE(udvr(n_fl))
            z = cmplx(1.d0,0.d0,kind(0.d0))
            Do nf = 1, n_fl
               if (projector) then
                 CALL udvr(nf)%init(ndim,'r',wf_r(nf)%P)
               else
                 CALL udvr(nf)%init(ndim,'r')
               endif
            enddo
            nst = 1
            DO nt = 0,ltrot - 1
               ! Now wrapup:
               nt1 = nt + 1
               CALL propr   (gt0,nt1)
               CALL proprm1 (g0t,nt1)
               CALL proprm1 (gtt,nt1)
               CALL propr   (gtt,nt1)
               ! In Module Hamiltonian
               If (symm) then
                  Call hop_mod_symm(g00_t,g00)
                  Call hop_mod_symm(gtt_t,gtt)
                  Call hop_mod_symm(g0t_t,g0t)
                  Call hop_mod_symm(gt0_t,gt0)
                  CALL obsert(nt1, gt0_t,g0t_t,g00_t,gtt_t,phase)
               Else
                  CALL obsert(nt1, gt0,g0t,g00,gtt,phase)
               Endif
               IF ( stab_nt(nst) == nt1 .AND.  nt1 .NE. ltrot ) THEN
                  !NTST = NT1 - NWRAP
                  !NST  = NT1/(NWRAP)
                  ntst = stab_nt(nst-1)
                  ! WRITE(6,*) 'NT1, NST: ', NT1,NST
                  CALL wrapur(ntst, nt1, udvr)
                  DO nf = 1,n_fl
                     hlp4(:,:) = gtt(:,:,nf)
                     hlp5(:,:) = gt0(:,:,nf)
                     hlp6(:,:) = g0t(:,:,nf)
                     Call cgr2_2(gt0(:,:,nf), g00(:,:,nf), gtt(:,:,nf), g0t(:,:,nf), &
                          & udvr(nf), udvst(nst, nf), ndim)
                     Call control_precision_tau(gr(:,:,nf), g00(:,:,nf), ndim)
                     Call control_precision_tau(hlp4      , gtt(:,:,nf), ndim)
                     Call control_precision_tau(hlp5      , gt0(:,:,nf), ndim)
                     Call control_precision_tau(hlp6      , g0t(:,:,nf), ndim)
                  Enddo
                  nst = nst + 1
               Endif
            ENDDO
            DO nf = 1, n_fl
               CALL udvr(nf)%dealloc
            ENDDO
            DEALLOCATE(udvr)
            If (symm) Then
               Deallocate ( g00_t, g0t_t, gt0_t,  gtt_t )
            endif