ALF: control Module Reference
control Module Reference
This module handles the calculation of the acceptance ratio. It also monitors the precision of the code, as well as the timing.
Functions/Subroutines
subroutine control_init
subroutine control_upgrade (toggle)
subroutine control_upgrade_eff (toggle)
subroutine control_upgrade_temp (toggle)
subroutine control_upgrade_glob (toggle, size_clust)
subroutine control_precisiong (A, B, Ndim)
subroutine control_precision_tau (A, B, Ndim)
subroutine control_precisionp (Z, Z1)
subroutine control_precisionp_glob (Z, Z1)
subroutine control_print (Group_Comm)
subroutine make_truncation (prog_truncation, cpu_max, count_bin_start, count_bin_end)
Variables
real(kind=kind(0.d0)), save, private xmeang
real(kind=kind(0.d0)), save, private xmaxg
real(kind=kind(0.d0)), save, private xmaxp
real(kind=kind(0.d0)), save, private xmean_tau
real(kind=kind(0.d0)), save, private xmax_tau
integer(kind=kind(0.d0)), save, private count_cpu_start
integer(kind=kind(0.d0)), save, private count_cpu_end
integer(kind=kind(0.d0)), save, private count_rate
integer(kind=kind(0.d0)), save, private count_max
integer, save, private ncg
integer, save, private ncg_tau
integer(kind=kind(0.d0)), save, private nc_up
integer(kind=kind(0.d0)), save, private acc_up
integer(kind=kind(0.d0)), save, private nc_eff_up
integer(kind=kind(0.d0)), save, private acc_eff_up
integer(kind=kind(0.d0)), save, private nc_glob_up
integer(kind=kind(0.d0)), save, private acc_glob_up
integer(kind=kind(0.d0)), save, private nc_temp_up
integer(kind=kind(0.d0)), save, private acc_temp_up
real(kind=kind(0.d0)), save, private xmaxp_glob
real(kind=kind(0.d0)), save, private xmeanp_glob
integer(kind=kind(0.d0)), save, private nc_phase_glob
real(kind=kind(0.d0)), save, private size_clust_glob_up
real(kind=kind(0.d0)), save, private size_clust_glob_acc_up
Detailed Description
This module handles the calculation of the acceptance ratio. It also monitors the precision of the code, as well as the timing.
Author
ALF-project
Function/Subroutine Documentation
control_init()
subroutine control::control_init ()
Definition at line 66 of file control_mod.f90.
References acc_eff_up, acc_glob_up, acc_temp_up, acc_up, count_cpu_start, count_max, count_rate, nc_eff_up, nc_glob_up, nc_phase_glob, nc_temp_up, nc_up, ncg, ncg_tau, size_clust_glob_acc_up, size_clust_glob_up, xmax_tau, xmaxg, xmaxp, xmaxp_glob, xmean_tau, xmeang, and xmeanp_glob.
Referenced by main().
         Implicit none
         xmeang     = 0.d0
         xmean_tau  = 0.d0
         xmaxg      = 0.d0
         xmax_tau   = 0.d0
         xmaxp      = 0.d0
         xmeanp_glob= 0.d0
         xmaxp_glob = 0.d0
         ncg          = 0
         ncg_tau      = 0
         nc_up        = 0
         acc_up       = 0
         nc_eff_up    = 0
         acc_eff_up   = 0
         nc_glob_up   = 0
         acc_glob_up  = 0
         nc_phase_glob= 0
         nc_temp_up   = 0
         acc_temp_up  = 0
         size_clust_glob_up    = 0.d0
         size_clust_glob_acc_up= 0.d0
         call system_clock(count_cpu_start,count_rate,count_max)
control_precision_tau()
subroutine control::control_precision_tau (complex (kind=kind(0.d0)), dimension(ndim,ndim) A, complex (kind=kind(0.d0)), dimension(ndim,ndim) B, integer Ndim)
Definition at line 144 of file control_mod.f90.
References ncg_tau, xmax_tau, and xmean_tau.
Referenced by tau_m_mod::tau_m().
         Implicit none
         Integer :: Ndim
         Complex (Kind=Kind(0.d0)) :: A(Ndim,Ndim), B(Ndim,Ndim)
         Real    (Kind=Kind(0.d0)) :: XMAX, XMEAN
         ncg_tau = ncg_tau + 1
         xmean = 0.d0
         xmax  = 0.d0
         CALL compare(a, b, xmax, xmean)
         IF (xmax  >  xmax_tau) xmax_tau = xmax
         xmean_tau = xmean_tau + xmean
control_precisiong()
subroutine control::control_precisiong (complex (kind=kind(0.d0)), dimension(ndim,ndim) A, complex (kind=kind(0.d0)), dimension(ndim,ndim) B, integer Ndim)
Definition at line 129 of file control_mod.f90.
References ncg, xmaxg, and xmeang.
Referenced by main().
         Implicit none
         Integer :: Ndim
         Complex (Kind=Kind(0.d0)) :: A(Ndim,Ndim), B(Ndim,Ndim)
         Real    (Kind=Kind(0.d0)) :: XMAX, XMEAN
         ncg = ncg + 1
         xmean = 0.d0
         xmax  = 0.d0
         CALL compare(a, b, xmax, xmean)
         IF (xmax  >  xmaxg) xmaxg = xmax
         xmeang = xmeang + xmean
control_precisionp()
subroutine control::control_precisionp (complex (kind=kind(0.d0)), intent(in) Z, complex (kind=kind(0.d0)), intent(in) Z1)
Definition at line 160 of file control_mod.f90.
References xmaxp.
Referenced by main().
         Implicit none
         Complex (Kind=Kind(0.D0)), INTENT(IN) :: Z,Z1
         Real    (Kind=Kind(0.D0)) :: X
         x = abs(z-z1)
         if ( x > xmaxp ) xmaxp = x
control_precisionp_glob()
subroutine control::control_precisionp_glob (complex (kind=kind(0.d0)), intent(in) Z, complex (kind=kind(0.d0)), intent(in) Z1)
Definition at line 169 of file control_mod.f90.
References nc_phase_glob, xmaxp_glob, and xmeanp_glob.
Referenced by global_mod::global_updates().
         Implicit none
         Complex (Kind=Kind(0.D0)), INTENT(IN) :: Z,Z1
         Real    (Kind=Kind(0.D0)) :: X
         x = abs(z-z1)
         if ( x > xmaxp_glob ) xmaxp_glob = x
         xmeanp_glob = xmeanp_glob + x
         nc_phase_glob = nc_phase_glob + 1
control_print()
subroutine control::control_print (integer, intent(in) Group_Comm)
Definition at line 180 of file control_mod.f90.
References acc_eff_up, acc_glob_up, acc_temp_up, acc_up, count_cpu_end, count_cpu_start, count_max, count_rate, nc_eff_up, nc_glob_up, nc_phase_glob, nc_temp_up, nc_up, ncg, ncg_tau, size_clust_glob_acc_up, size_clust_glob_up, xmax_tau, xmaxg, xmaxp, xmaxp_glob, xmean_tau, xmeang, and xmeanp_glob.
Referenced by main().
 #ifdef MPI
         Use mpi
 #endif
         Implicit none
         Integer, Intent(IN) :: Group_Comm
         Character (len=64) :: file1
         Real (Kind=Kind(0.d0)) :: Time, Acc, Acc_eff, Acc_Glob, Acc_Temp, size_clust_Glob, size_clust_Glob_ACC
 #ifdef MPI
         REAL (Kind=Kind(0.d0))  :: X
         Integer        :: Ierr, Isize, Irank, irank_g, isize_g, igroup
         CALL mpi_comm_size(mpi_comm_world,isize,ierr)
         CALL mpi_comm_rank(mpi_comm_world,irank,ierr)
         call mpi_comm_rank(group_comm, irank_g, ierr)
         call mpi_comm_size(group_comm, isize_g, ierr)
         igroup           = irank/isize_g
 #endif
         acc = 0.d0
         IF (nc_up > 0 )  acc = dble(acc_up)/dble(nc_up)
         acc_eff = 0.d0
         IF (nc_eff_up > 0 )  acc_eff = dble(acc_eff_up)/dble(nc_eff_up)
         acc_glob = 0.d0
         size_clust_glob = 0.d0
         size_clust_glob_acc = 0.d0
         IF (nc_glob_up    > 0 )  then
           acc_glob    = dble(acc_glob_up)/dble(nc_glob_up)
           size_clust_glob     = size_clust_glob_up     / dble( nc_glob_up)
           size_clust_glob_acc = size_clust_glob_acc_up / dble(acc_glob_up)
         endif
         acc_temp = 0.d0
         IF (nc_temp_up    > 0 )  acc_temp    = dble(acc_temp_up)/dble(nc_temp_up)
         IF (nc_phase_glob > 0 ) xmeanp_glob  = xmeanp_glob/dble(nc_phase_glob)
         call system_clock(count_cpu_end)
         time = (count_cpu_end-count_cpu_start)/dble(count_rate)
         if (count_cpu_end .lt. count_cpu_start) time = (count_max+count_cpu_end-count_cpu_start)/dble(count_rate)
 #if defined(MPI)
         x = 0.d0
         CALL mpi_reduce(acc,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         acc = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(acc_eff,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         acc_eff = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(acc_glob,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         acc_glob = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(acc_temp ,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         acc_temp  = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(size_clust_glob,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         size_clust_glob = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(size_clust_glob_acc,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         size_clust_glob_acc = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(xmeang,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         xmeang = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(xmean_tau,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         xmean_tau = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(xmeanp_glob,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         xmeanp_glob = x/dble(isize_g)
         x = 0.d0
         CALL mpi_reduce(time,x,1,mpi_real8,mpi_sum, 0,group_comm,ierr)
         time = x/dble(isize_g)
         CALL mpi_reduce(xmaxg,x,1,mpi_real8,mpi_max, 0,group_comm,ierr)
         xmaxg = x
         CALL mpi_reduce(xmax_tau,x,1,mpi_real8,mpi_max, 0,group_comm,ierr)
         xmax_tau= x
         CALL mpi_reduce(xmaxp,x,1,mpi_real8,mpi_max, 0,group_comm,ierr)
         xmaxp = x
         CALL mpi_reduce(xmaxp_glob,x,1,mpi_real8,mpi_max, 0,group_comm,ierr)
         xmaxp_glob = x
 #endif
 #if defined(TEMPERING)
         write(file1,'(A,I0,A)') "Temp_",igroup,"/info"
 #else
         file1 = "info"
 #endif
 #if defined(MPI)
         If (irank_g == 0 ) then
 #endif
            Open (unit=50,file=file1, status="unknown", position="append")
            If (ncg > 0 ) then
               xmeang = xmeang/dble(ncg)
               Write(50,*) ' Precision Green  Mean, Max : ', xmeang, xmaxg
               Write(50,*) ' Precision Phase, Max       : ', xmaxp
            endif
            If ( ncg_tau > 0 ) then
               xmean_tau = xmean_tau/dble(ncg_tau)
               Write(50,*) ' Precision tau    Mean, Max : ', xmean_tau, xmax_tau
            endif
            Write(50,*) ' Acceptance                 : ', acc
            Write(50,*) ' Effective Acceptance       : ', acc_eff
 #if defined(TEMPERING)
            Write(50,*) ' Acceptance Tempering       : ', acc_temp
 #endif
            !If (ACC_Glob > 1.D-200 ) then
               Write(50,*) ' Acceptance_Glob              : ', acc_glob
               Write(50,*) ' Mean Phase diff Glob         : ', xmeanp_glob
               Write(50,*) ' Max  Phase diff Glob         : ', xmaxp_glob
               Write(50,*) ' Average cluster size         : ', size_clust_glob
               Write(50,*) ' Average accepted cluster size: ', size_clust_glob_acc
            !endif
            Write(50,*) ' CPU Time                   : ', time
            Close(50)
 #if defined(MPI)
         endif
 #endif
control_upgrade()
subroutine control::control_upgrade (logical toggle)
Definition at line 95 of file control_mod.f90.
References acc_up, and nc_up.
Referenced by upgrade(), and upgrade2().
         Implicit none
         Logical :: toggle
         nc_up = nc_up + 1
         if (toggle) acc_up = acc_up + 1
control_upgrade_eff()
subroutine control::control_upgrade_eff (logical toggle)
Definition at line 102 of file control_mod.f90.
References acc_eff_up, and nc_eff_up.
Referenced by upgrade(), upgrade2(), wrapgr_mod::wrapgrdo(), and wrapgr_mod::wrapgrup().
         Implicit none
         Logical :: toggle
         nc_eff_up = nc_eff_up + 1
         if (toggle) acc_eff_up = acc_eff_up + 1
control_upgrade_glob()
subroutine control::control_upgrade_glob (logical toggle, real (kind=kind(0.d0)), intent(in) size_clust)
Definition at line 116 of file control_mod.f90.
References acc_glob_up, nc_glob_up, size_clust_glob_acc_up, and size_clust_glob_up.
Referenced by global_mod::global_updates().
         Implicit none
         Logical :: toggle
         Real (Kind=Kind(0.d0)), intent(in) :: size_clust
         nc_glob_up = nc_glob_up + 1
         size_clust_glob_up = size_clust_glob_up + size_clust
         if (toggle) then
           acc_glob_up = acc_glob_up + 1
           size_clust_glob_acc_up = size_clust_glob_acc_up + size_clust
         endif
control_upgrade_temp()
subroutine control::control_upgrade_temp (logical toggle)
Definition at line 109 of file control_mod.f90.
References acc_temp_up, and nc_temp_up.
Referenced by global_mod::exchange_step().
         Implicit none
         Logical :: toggle
         nc_temp_up  =  nc_temp_up    +  1
         if (toggle)  acc_temp_up  = acc_temp_up + 1
make_truncation()
subroutine control::make_truncation (logical, intent(out) prog_truncation, real(kind=kind(0.d0)), intent(in) cpu_max, integer(kind=kind(0.d0)), intent(in) count_bin_start, integer(kind=kind(0.d0)), intent(in) count_bin_end)
Definition at line 313 of file control_mod.f90.
References count_cpu_start, count_max, and count_rate.
Referenced by main().
       !!!!!!! Written by M. Bercx
       ! This subroutine checks if the conditions for a controlled termination of the program are met.
       ! The subroutine contains a hard-coded threshold (in unit of bins):
       ! if time_remain/time_bin_duration < threshold the program terminates.
 #ifdef MPI
       Use mpi
 #endif
       logical, intent(out)                 :: prog_truncation
       real(kind=kind(0.d0)), intent(in)    :: cpu_max
       integer(kind=kind(0.d0)), intent(in) :: count_bin_start, count_bin_end
       real(kind=kind(0.d0))                :: count_alloc_end
       real(kind=kind(0.d0))                :: time_bin_duration,time_remain,bins_remain,threshold
 #ifdef MPI
       real(kind=kind(0.d0))                :: bins_remain_mpi
       integer                              :: err_mpi,rank_mpi,tasks_mpi
 #endif
       threshold = 1.5d0
       prog_truncation = .false.
 #ifdef MPI
       call mpi_comm_size(mpi_comm_world, tasks_mpi, err_mpi)
       call mpi_comm_rank(mpi_comm_world, rank_mpi, err_mpi)
 #endif
       count_alloc_end   = count_cpu_start + cpu_max*3600*count_rate
       time_bin_duration = (count_bin_end-count_bin_start)/dble(count_rate)
       time_remain       = (count_alloc_end - count_bin_end)/dble(count_rate)
       if (count_bin_end .lt. count_bin_start) then ! the counter has wrapped around
          time_bin_duration = (count_max+count_bin_end-count_bin_start)/dble(count_rate)
          time_remain       = (count_alloc_end - count_bin_end-count_max)/dble(count_rate)
       endif
       bins_remain       = time_remain/time_bin_duration
 #ifdef MPI
       call mpi_reduce(bins_remain,bins_remain_mpi,1,mpi_double_precision,mpi_sum,0,mpi_comm_world,err_mpi)
 #endif
 #ifdef MPI
       if (rank_mpi .eq. 0) bins_remain_mpi = bins_remain_mpi/tasks_mpi
       call mpi_bcast(bins_remain_mpi,1, mpi_double_precision,0, mpi_comm_world,err_mpi)
       if (bins_remain_mpi .lt. threshold) prog_truncation = .true.
 #else
       if (bins_remain .lt. threshold) prog_truncation = .true.
 #endif
Variable Documentation
acc_eff_up
integer (kind=kind(0.d0)), save, private control::acc_eff_up private
Definition at line 54 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_eff().
acc_glob_up
integer (kind=kind(0.d0)), save, private control::acc_glob_up private
Definition at line 55 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_glob().
acc_temp_up
integer (kind=kind(0.d0)), save, private control::acc_temp_up private
Definition at line 56 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_temp().
acc_up
integer (kind=kind(0.d0)), save, private control::acc_up private
Definition at line 53 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade().
count_cpu_end
integer (kind=kind(0.d0)), save, private control::count_cpu_end private
Definition at line 51 of file control_mod.f90.
Referenced by control_print().
count_cpu_start
integer (kind=kind(0.d0)), save, private control::count_cpu_start private
Definition at line 51 of file control_mod.f90.
Referenced by control_init(), control_print(), and make_truncation().
     Integer (Kind=Kind(0.d0)), private, save :: count_CPU_start,count_CPU_end,count_rate,count_max
count_max
integer (kind=kind(0.d0)), save, private control::count_max private
Definition at line 51 of file control_mod.f90.
Referenced by control_init(), control_print(), and make_truncation().
count_rate
integer (kind=kind(0.d0)), save, private control::count_rate private
Definition at line 51 of file control_mod.f90.
Referenced by control_init(), control_print(), and make_truncation().
nc_eff_up
integer (kind=kind(0.d0)), save, private control::nc_eff_up private
Definition at line 54 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_eff().
     Integer (Kind=Kind(0.d0)) , private, save :: NC_eff_up, ACC_eff_up
nc_glob_up
integer (kind=kind(0.d0)), save, private control::nc_glob_up private
Definition at line 55 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_glob().
     Integer (Kind=kind(0.d0)),  private, save :: NC_Glob_up, ACC_Glob_up
nc_phase_glob
integer (kind=kind(0.d0)), save, private control::nc_phase_glob private
Definition at line 58 of file control_mod.f90.
Referenced by control_init(), control_precisionp_glob(), and control_print().
     Integer (Kind=Kind(0.d0)),  private, save :: NC_Phase_GLob
nc_temp_up
integer (kind=kind(0.d0)), save, private control::nc_temp_up private
Definition at line 56 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_temp().
     Integer (Kind=kind(0.d0)),  private, save :: NC_Temp_up, ACC_Temp_up
nc_up
integer (kind=kind(0.d0)), save, private control::nc_up private
Definition at line 53 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade().
     Integer (Kind=Kind(0.d0)) , private, save :: NC_up, ACC_up
ncg
integer, save, private control::ncg private
Definition at line 52 of file control_mod.f90.
Referenced by control_init(), control_precisiong(), and control_print().
     Integer          , private, save :: NCG, NCG_tau
ncg_tau
integer, save, private control::ncg_tau private
Definition at line 52 of file control_mod.f90.
Referenced by control_init(), control_precision_tau(), and control_print().
size_clust_glob_acc_up
real (kind=kind(0.d0)), save, private control::size_clust_glob_acc_up private
Definition at line 60 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_glob().
size_clust_glob_up
real (kind=kind(0.d0)), save, private control::size_clust_glob_up private
Definition at line 60 of file control_mod.f90.
Referenced by control_init(), control_print(), and control_upgrade_glob().
     real    (Kind=Kind(0.d0)),  private, save :: size_clust_Glob_up, size_clust_Glob_ACC_up
xmax_tau
real (kind=kind(0.d0)), save, private control::xmax_tau private
Definition at line 50 of file control_mod.f90.
Referenced by control_init(), control_precision_tau(), and control_print().
xmaxg
real (kind=kind(0.d0)), save, private control::xmaxg private
Definition at line 50 of file control_mod.f90.
Referenced by control_init(), control_precisiong(), and control_print().
xmaxp
real (kind=kind(0.d0)), save, private control::xmaxp private
Definition at line 50 of file control_mod.f90.
Referenced by control_init(), control_precisionp(), and control_print().
xmaxp_glob
real (kind=kind(0.d0)), save, private control::xmaxp_glob private
Definition at line 57 of file control_mod.f90.
Referenced by control_init(), control_precisionp_glob(), and control_print().
     real    (Kind=Kind(0.d0)),  private, save :: XMAXP_Glob, XMEANP_Glob
xmean_tau
real (kind=kind(0.d0)), save, private control::xmean_tau private
Definition at line 50 of file control_mod.f90.
Referenced by control_init(), control_precision_tau(), and control_print().
xmeang
real (kind=kind(0.d0)), save, private control::xmeang private
Definition at line 50 of file control_mod.f90.
Referenced by control_init(), control_precisiong(), and control_print().
     real    (Kind=Kind(0.d0)), private, save :: XMEANG, XMAXG, XMAXP,  Xmean_tau, Xmax_tau
xmeanp_glob
real (kind=kind(0.d0)), save, private control::xmeanp_glob private
Definition at line 57 of file control_mod.f90.
Referenced by control_init(), control_precisionp_glob(), and control_print().