ALF: hamiltonian Module Reference
hamiltonian Module Reference
This module defines the Hamiltonian and observables. Here, we have included a set of predefined Hamiltonians. They include the Hubbard and SU(N) tV models on honeycomb, pi-flux and square lattices.
Functions/Subroutines
subroutine ham_set
Sets the Hamiltonian.
subroutine ham_v
Sets the interaction.
real(kind=kind(0.d0)) function s0 (n, nt, Hs_new)
Single spin flip S0 ratio.
subroutine setup_ising_action
Setup bonds and median lattice.
subroutine alloc_obs (Ltau)
Specifiy the equal time and time displaced observables.
subroutine global_move (T0_Proposal_ratio, nsigma_old, size_clust)
Global moves.
real(kind=kind(0.d0)) function delta_s0_global (Nsigma_old)
Computes the ratio exp(S0(new))/exp(S0(old))
subroutine obser (GR, Phase, Ntau)
Computes equal time observables.
subroutine obsert (NT, GT0, G0T, G00, GTT, PHASE)
Computes time displaced observables.
subroutine pr_obs (LTAU)
Prints out the bins. No need to change this routine.
subroutine init_obs (Ltau)
Initializes observables to zero before each bins. No need to change this routine.
subroutine global_move_tau (T0_Proposal_ratio, S0_ratio, Flip_list, Flip_length, Flip_value, ntau)
Specify a global move on a given time slice tau.
subroutine hamiltonian_set_nsigma (Initial_field)
The user can set the initial field.
Variables
type(operator), dimension(:,:), allocatable op_v
type(operator), dimension(:,:), allocatable op_t
type(wavefunction), dimension(:), allocatable wf_l
type(wavefunction), dimension(:), allocatable wf_r
class(fields), allocatable nsigma
integer ndim
integer n_fl
integer n_sun
integer ltrot
integer thtrot
logical projector
integer group_comm
logical symm
type(lattice), private latt
type(unit_cell), private latt_unit
integer, private l1
integer, private l2
real(kind=kind(0.d0)), private ham_t
real(kind=kind(0.d0)), private ham_u
real(kind=kind(0.d0)), private ham_chem
real(kind=kind(0.d0)), private ham_h
real(kind=kind(0.d0)), private ham_j
real(kind=kind(0.d0)), private ham_xi
real(kind=kind(0.d0)), private xb_x
real(kind=kind(0.d0)), private phi_x
real(kind=kind(0.d0)), private ham_tv
real(kind=kind(0.d0)), private ham_alpha
real(kind=kind(0.d0)), private percent_change
real(kind=kind(0.d0)), private xb_y
real(kind=kind(0.d0)), private phi_y
real(kind=kind(0.d0)), private dtau
real(kind=kind(0.d0)), private beta
real(kind=kind(0.d0)), private theta
character(len=64), private model
character(len=64), private lattice_type
logical, private one_dimensional
logical, private checkerboard
integer, dimension(:,:), allocatable, private list
integer, dimension(:,:), allocatable, private invlist
type(obser_vec), dimension(:), allocatable, private obs_scal
Privat Observables.
type(obser_latt), dimension(:), allocatable, private obs_eq
type(obser_latt), dimension(:), allocatable, private obs_tau
real(kind=kind(0.d0)), dimension(-1:1), private dw_ising_tau
Storage for the Ising action.
real(kind=kind(0.d0)), dimension(-1:1), private dw_ising_space
integer, dimension(:,:), allocatable, private l_bond
integer, dimension(:,:), allocatable, private l_bond_inv
integer, dimension(:,:), allocatable, private ising_nnlist
Detailed Description
This module defines the Hamiltonian and observables. Here, we have included a set of predefined Hamiltonians. They include the Hubbard and SU(N) tV models on honeycomb, pi-flux and square lattices.
Author
ALF-project
The public variables of this module are the following
Parameters
[public] OP_V
 Type (Operator), dimension(:,:), allocatable
 List of operators of type=1,2 and 3 describing the sequence of interactions on a time slice.
 The first index runs over this sequence. The second corresponds to the flavor index.
[public] OP_T
 Type (Operator), dimension(:,:), allocatable
 Sequence of  operators  accounting for the  hopping on a  time slice. This can include  various
 checkerboard decompositions. The first index runs over this sequence. The second corresponds to
 the flavor index.
The progagation reads: . That is first the hopping and then the potential energy.
[public] WF_L
Type (WaveFunction), dimension(:),   allocatable
 Left trial wave function.
[public] WF_R
Type (WaveFunction), dimension(:),   allocatable
 Right trial wave function.   For both wave functions the index runs over the flavor index.
[public] nsigma(:,:)
Class(Fields), allocatable
 Array containing all auxiliary fields. The first index runs through the operator sequence. The second
 through the time slies.
[public] Ndim
Integer
 Total number of orbitals. e.g. # unit cells * # orbitals per unit cell.
[public] N_FL
Integer
 # of flavors.  Propagation is block diagonal in flavors.
[public] N_SUN
Integer
 # of colors.  Propagation is color independent.
[public] Ltrot
Integer
 Available measurment interval in units of Delta Tau.
[public] Thtrot
Integer
 Effective projection parameter in units of Delta Tau.  (Only relevant if projective option is turned on)
[public] Projector
Logical
 Flag for projector. If true then the total number of time slices will correspond to Ltrot + 2*Thtrot
[public] Group_Comm
Integer
 Defines MPI communicator
[public] Symm
Logical
If set to true then the green functions will be symmetrized before being sent to the Obser, ObserT subroutines. In particular, the transformation, will be carried out and will be sent to the Obser and ObserT subroutines. Note that if you want to use this feature, then you have to be sure the hopping and interaction terms are decomposed symmetrically. If Symm is true, the propagation reads:
You still have to add some docu for the other private variables in this module.
Function/Subroutine Documentation
alloc_obs()
subroutine hamiltonian::alloc_obs (integer, intent(in) Ltau)
Specifiy the equal time and time displaced observables.
Author
ALF Collaboration
Parameters
[in] ltau Ltau=1 if time displaced correlations are considered.
Definition at line 876 of file Hamiltonian_Examples.f90.
References latt, latt_unit, ltrot, obs_eq, obs_scal, obs_tau, observables::obser_latt_make(), observables::obser_vec_make(), and thtrot.
Referenced by main().
           Implicit none
           Integer, Intent(In) :: Ltau
           Integer    ::  i, N, Ns,Nt,No, Norb
           Character (len=64) ::  Filename
           norb = latt_unit%Norb
           ! Scalar observables
           Allocate ( obs_scal(4) )
           Do i = 1,Size(obs_scal,1)
              select case (i)
              case (1)
                 n = 1;   filename ="Kin"
              case (2)
                 n = 1;   filename ="Pot"
              case (3)
                 n = 1;   filename ="Part"
              case (4)
                 n = 1;   filename ="Ener"
              case default
                 Write(6,*) ' Error in Alloc_obs '
              end select
              Call obser_vec_make(obs_scal(i),n,filename)
           enddo
           ! Equal time correlators
           Allocate ( obs_eq(5) )
           Do i = 1,Size(obs_eq,1)
              select case (i)
              case (1)
                 ns = latt%N;  no = norb;  filename ="Green"
              case (2)
                 ns = latt%N;  no = norb;  filename ="SpinZ"
              case (3)
                 ns = latt%N;  no = norb;  filename ="SpinXY"
              case (4)
                 ns = latt%N;  no = norb;  filename ="Den"
              case (5)
                 ns = latt%N;  no = norb;  filename ="SpinT"
              case default
                 Write(6,*) ' Error in Alloc_obs '
              end select
              nt = 1
              Call obser_latt_make(obs_eq(i),ns,nt,no,filename)
           enddo
           If (ltau == 1) then
              ! Equal time correlators
              Allocate ( obs_tau(4) )
              Do i = 1,Size(obs_tau,1)
                 select case (i)
                 case (1)
                    ns = latt%N; no = norb;  filename ="Green"
                 case (2)
                    ns = latt%N; no = norb;  filename ="SpinZ"
                 case (3)
                    ns = latt%N; no = norb;  filename ="SpinXY"
                 case (4)
                    ns = latt%N; no = norb;  filename ="Den"
                 case default
                    Write(6,*) ' Error in Alloc_obs '
                 end select
                 nt = ltrot+1-2*thtrot
                 Call obser_latt_make(obs_tau(i),ns,nt,no,filename)
              enddo
           endif
delta_s0_global()
real (kind=kind(0.d0)) function hamiltonian::delta_s0_global (class (fields), intent(in), allocatable Nsigma_old)
Computes the ratio exp(S0(new))/exp(S0(old))
Author
ALF Collaboration
This function computes the ratio
e^{-S0(nsigma)}/e^{-S0(nsigma_old)}
Parameters
[IN] nsigma_old, Type(Fields)
  Old configuration. The new configuration is stored in nsigma.
Definition at line 1008 of file Hamiltonian_Examples.f90.
References dtau, ham_h, ham_j, l_bond, latt, ltrot, model, and nsigma.
Referenced by global_mod::compute_ratio_global(), and global_mod::exchange_step().
           !  This function computes the ratio:  e^{-S0(nsigma)}/e^{-S0(nsigma_old)}
           Implicit none
           ! Arguments
           class(fields), allocatable, INTENT(IN) :: nsigma_old
           ! Local
           Integer :: I,n,n1,n2,n3,n4,nt,nt1, nc_F, nc_J, nc_h_p, nc_h_m
           delta_s0_global = 1.d0
           If ( model == "Hubbard_SU2_Ising" ) then
              nc_f = 0
              nc_j = 0
              nc_h_p = 0
              nc_h_m = 0
              Do i = 1,latt%N
                 n1  = l_bond(i,1)
                 n2  = l_bond(latt%nnlist(i,1,0),2)
                 n3  = l_bond(latt%nnlist(i,0,1),1)
                 n4  = l_bond(i,2)
                 do nt = 1,ltrot
                    nt1 = nt +1
                    if (nt == ltrot) nt1 = 1
                    if (nsigma%i(n1,nt) == nsigma%i(n1,nt1) ) then
                       nc_h_p = nc_h_p + 1
                    else
                       nc_h_m = nc_h_m + 1
                    endif
                    if (nsigma_old%i(n1,nt) == nsigma_old%i(n1,nt1) ) then
                       nc_h_p = nc_h_p - 1
                    else
                       nc_h_m = nc_h_m - 1
                    endif
                    if (nsigma%i(n4,nt) == nsigma%i(n4,nt1) ) then
                       nc_h_p = nc_h_p + 1
                    else
                       nc_h_m = nc_h_m + 1
                    endif
                    if (nsigma_old%i(n4,nt) == nsigma_old%i(n4,nt1) ) then
                       nc_h_p = nc_h_p - 1
                    else
                       nc_h_m = nc_h_m - 1
                    endif
                    nc_f = nc_f + nsigma%i    (n1,nt)*nsigma%i    (n2,nt)*nsigma%i    (n3,nt)*nsigma%i  (n4,nt)  &
                         &      - nsigma_old%i(n1,nt)*nsigma_old%i(n2,nt)*nsigma_old%i(n3,nt)*nsigma_old%i(n4,nt)
                    nc_j = nc_j + nsigma%i(n1,nt)*nsigma%i(n2,nt) + &
                         &        nsigma%i(n2,nt)*nsigma%i(n3,nt) + &
                         &        nsigma%i(n3,nt)*nsigma%i(n4,nt) + &
                         &        nsigma%i(n4,nt)*nsigma%i(n1,nt) - &
                         &        nsigma_old%i(n1,nt)*nsigma_old%i(n2,nt) - &
                         &        nsigma_old%i(n2,nt)*nsigma_old%i(n3,nt) - &
                         &        nsigma_old%i(n3,nt)*nsigma_old%i(n4,nt) - &
                         &        nsigma_old%i(n4,nt)*nsigma_old%i(n1,nt)
                 enddo
              enddo
              !             Delta_S0_global = ( sinh(Dtau*Ham_h)**nc_h_m ) * (cosh(Dtau*Ham_h)**nc_h_p) * &
              !                  &            exp( -Dtau*(Ham_F*real(nc_F,kind(0.d0)) -  Ham_J*real(nc_J,kind(0.d0))))
              ! No flux in example code. May want to include it.
              delta_s0_global = ( sinh(dtau*ham_h)**nc_h_m ) * (cosh(dtau*ham_h)**nc_h_p) * &
                   &            exp( dtau* ham_j*real(nc_J,kind(0.d0)))
              !Write(6,*) Delta_S0_global
           endif
global_move()
subroutine hamiltonian::global_move (real (kind=kind(0.d0)), intent(out) T0_Proposal_ratio, class (fields), intent(in), allocatable nsigma_old, real (kind=kind(0.d0)), intent(out) size_clust)
Global moves.
Author
ALF Collaboration
This routine generates a global update and returns the propability T0_Proposal_ratio = T0(sigma_out-> sigma_in) / T0(sigma_in -> sigma_out)
Parameters
[IN] nsigma_old, Type(Fields)
  Old configuration. The new configuration is stored in nsigma.
[OUT] T0_Proposal_ratio Real T0_Proposal_ratio = T0(sigma_new -> sigma_old) / T0(sigma_old -> sigma_new)
[OUT] Size_clust Real
  Size of cluster that will be flipped.
Definition at line 971 of file Hamiltonian_Examples.f90.
References nranf(), and nsigma.
Referenced by global_mod::global_updates().
           Implicit none
           Real (Kind=Kind(0.d0)), intent(out) :: T0_Proposal_ratio, size_clust
           class(fields),  allocatable, Intent(IN)  :: nsigma_old
           ! Local
           Integer :: N_op, N_tau, n1,n2, n
           t0_proposal_ratio  = 1.d0
           size_clust         = 3.d0
           nsigma%f = nsigma_old%f
           nsigma%t = nsigma_old%t
           n_op  = size(nsigma_old%f,1)
           n_tau = size(nsigma_old%f,2)
           Do n  = 1, nint(size_clust)
              n1 = nranf(n_op)
              n2 = nranf(n_tau)
              nsigma%f(n1,n2) = nsigma_old%flip(n1,n2)
           enddo
global_move_tau()
subroutine hamiltonian::global_move_tau (real (kind = kind(0.d0)), intent(out) T0_Proposal_ratio, real (kind = kind(0.d0)), intent(out) S0_ratio, integer, dimension(:), intent(out) Flip_list, integer, intent(out) Flip_length, real (kind = kind(0.d0)), dimension(:), intent(out) Flip_value, integer, intent(in) ntau)
Specify a global move on a given time slice tau.
Author
ALF Collaboration
Parameters
[in] ntau Integer
  Time slice
[out] T0_Proposal_ratio,Real
  T0_Proposal_ratio = T0( sigma_new -> sigma ) /  T0( sigma -> sigma_new)
[out] S0_ratio,Real
  S0_ratio = e^( S_0(sigma_new) ) / e^( S_0(sigma) )
[out] Flip_length Integer
  Number of flips stored in the first  Flip_length entries of the array Flip_values.
  Has to be smaller than NDIM
[out] Flip_list Integer(Ndim)
  List of spins to be flipped: nsigma%f(Flip_list(1),ntau) ... nsigma%f(Flip_list(Flip_Length),ntau)
  Note that Ndim = size(Op_V,1)
[out] Flip_value Real(Ndim)
  Flip_value(:)= nsigma%flip(Flip_list(:),ntau)
  Note that Ndim = size(Op_V,1)
Definition at line 1474 of file Hamiltonian_Examples.f90.
References dtau, lrc_mod::lrc_draw_field(), model, n_sun, ndim, nranf(), nsigma, op_v, percent_change, and s0().
Referenced by wrapgr_mod::wrapgr_random_update().
           Implicit none
           Real (Kind = Kind(0.d0)),INTENT(OUT) :: T0_Proposal_ratio,  S0_ratio
           Integer                , INTENT(OUT) :: Flip_list(:)
           Real (Kind = Kind(0.d0)),INTENT(OUT) :: Flip_value(:)
           Integer, INTENT(OUT) :: Flip_length
           Integer, INTENT(IN)    :: ntau
           ! Local
           Integer :: n_op, n, ns
           Real (Kind=Kind(0.d0)) :: T0_proposal
           If (model == "LRC" ) then
              Call lrc_draw_field(percent_change, dtau, nsigma%f(:,ntau), flip_value,n_sun)
              Do n = 1,ndim
                 flip_list(n) = n
                 !Write(6,*) Flip_value(n), nsigma%f(n,ntau)
              Enddo
              !Write(6,*)
              flip_length    = ndim
              ! T0_Proposal_ration exactly cancels S0_ratio
              t0_proposal_ratio = 1.d0
              s0_ratio          = 1.d0
           else
              flip_length = nranf(4)
              do n = 1,flip_length
                 n_op = nranf(size(op_v,1))
                 flip_list(n)  = n_op
                 flip_value(n) = nsigma%flip(n_op,ntau)
                 If ( op_v(n_op,1)%type == 1 ) then
                    s0_ratio          =   s0(n_op,ntau,flip_value(n))
                    t0_proposal       =  1.d0 - 1.d0/(1.d0+s0_ratio) ! No move prob
                    If ( t0_proposal > ranf_wrap() ) then
                       t0_proposal_ratio =  1.d0 / s0_ratio
                    else
                       t0_proposal_ratio = 0.d0
                    endif
                 else
                    t0_proposal_ratio = 1.d0
                    s0_ratio          = 1.d0
                 endif
              Enddo
           endif
ham_set()
subroutine hamiltonian::ham_set ()
Sets the Hamiltonian.
Author
ALF Collaboration
Definition at line 183 of file Hamiltonian_Examples.f90.
References beta, checkerboard, dtau, group_comm, ham_alpha, ham_chem, ham_h, ham_j, ham_t, ham_tv, ham_u, ham_v(), ham_xi, invlist, l1, l2, latt, latt_unit, lattice_type, list, lrc_mod::lrc_print(), lrc_mod::lrc_set_vij(), ltrot, model, n_fl, n_sun, ndim, op_t, percent_change, phi_x, phi_y, predefined_structures::predefined_hopping(), predefined_structures::predefined_latt(), predefined_structures::predefined_trialwavefunction(), projector, setup_ising_action(), symm, theta, thtrot, wf_l, wf_r, xb_x, and xb_y.
Referenced by main().
 #if defined (MPI) || defined(TEMPERING)
           Use mpi
 #endif
           Implicit none
           integer                :: ierr, N_part, nf
           Character (len=64) :: file_info, file_para
           ! L1, L2, Lattice_type, List(:,:), Invlist(:,:) -->  Lattice information
           ! Ham_T, Chem, Phi_X, XB_B, Checkerboard, Symm   -->  Hopping
           ! Interaction                              -->  Model
           ! Simulation type                          -->  Finite  T or Projection  Symmetrize Trotter.
           namelist /var_lattice/  l1, l2, lattice_type, model,  checkerboard, n_sun, phi_x, xb_x, symm
           namelist /var_hubbard/  ham_t, ham_chem, ham_u,  dtau, beta, theta, projector
           namelist /var_lrc/      ham_t, ham_chem, ham_u, ham_alpha, percent_change, dtau, beta, theta, projector
           namelist /var_ising/    ham_t, ham_chem, ham_u, ham_h, ham_j, ham_xi, dtau, beta, theta, projector
           namelist /var_t_v/      ham_t, ham_chem, ham_tv, dtau, beta, theta, projector
 #ifdef MPI
           Integer        :: Isize, Irank, irank_g, isize_g, igroup
           Integer        :: STATUS(MPI_STATUS_SIZE)
 #endif
           ! Global "Default" values.
           n_sun        = 1
           checkerboard = .false.
           symm         = .false.
           phi_x        = 0.d0
           xb_x         = 1.d0
           phi_y        = 0.d0
           xb_y         = 1.d0
 #ifdef MPI
           CALL mpi_comm_size(mpi_comm_world,isize,ierr)
           CALL mpi_comm_rank(mpi_comm_world,irank,ierr)
           call mpi_comm_rank(group_comm, irank_g, ierr)
           call mpi_comm_size(group_comm, isize_g, ierr)
           igroup           = irank/isize_g
           !if ( irank_g == 0 )   write(6,*) "Mpi Test", igroup, isize_g
 #endif
           ! Open files
 #if defined(MPI)
           If (irank_g == 0 ) then
 #endif
              file_para = "parameters"
              file_info = "info"
 #if defined(TEMPERING)
              write(file_para,'(A,I0,A)') "Temp_",igroup,"/parameters"
              write(file_info,'(A,I0,A)') "Temp_",igroup,"/info"
 #endif
              OPEN(unit=5,file=file_para,status='old',action='read',iostat=ierr)
              OPEN(unit = 50,file=file_info,status="unknown",position="append")
 #ifdef MPI
           Endif
 #endif
 #ifdef MPI
           If (irank_g == 0 ) then
 #endif
              IF (ierr /= 0) THEN
                 WRITE(*,*) 'unable to open <parameters>',ierr
                 stop
              END IF
              READ(5,nml=var_lattice)
 #ifdef MPI
           Endif
           CALL mpi_bcast(l1          ,1  ,mpi_integer,   0,group_comm,ierr)
           CALL mpi_bcast(l2          ,1  ,mpi_integer,   0,group_comm,ierr)
           CALL mpi_bcast(n_sun       ,1  ,mpi_integer,   0,group_comm,ierr)
           CALL mpi_bcast(phi_x       ,1  ,mpi_real8  ,   0,group_comm,ierr)
           CALL mpi_bcast(xb_x        ,1  ,mpi_real8  ,   0,group_comm,ierr)
           CALL mpi_bcast(model       ,64 ,mpi_character, 0,group_comm,ierr)
           CALL mpi_bcast(checkerboard,1  ,mpi_logical  , 0,group_comm,ierr)
           CALL mpi_bcast(symm        ,1  ,mpi_logical  , 0,group_comm,ierr)
           CALL mpi_bcast(lattice_type,64 ,mpi_character, 0,group_comm,ierr)
 #endif
           Call predefined_latt(lattice_type, l1,l2,ndim, list,invlist,latt,latt_unit)
 #ifdef MPI
           If (irank_g == 0) then
 #endif
              Write(50,*) '====================================='
              Write(50,*) 'Model is      : ', model
              Write(50,*) 'Lattice is    : ', lattice_type
              Write(50,*) '# of orbitals : ', ndim
              If (lattice_type == "Square" .or. lattice_type == "One_dimensional" ) then
                 Write(50,*) 'X_boundary    : ', xb_x
                 Write(50,*) 'Flux_X        : ', phi_x
              Endif
              Write(50,*) 'Checkerboard  : ', checkerboard
              Write(50,*) 'Symm. decomp  : ', symm
 #ifdef MPI
           Endif
 #endif
           ! Default is finite temperature.
           projector = .false.
           theta = 0.d0
           thtrot = 0
           Select Case (model)
           Case ("LRC")
              n_sun = 2
              n_fl  = 1
 #ifdef MPI
              If (irank_g == 0 ) then
 #endif
                 READ(5,nml=var_lrc)
                 ltrot = nint(beta/dtau)
                 if (projector) thtrot = nint(theta/dtau)
                 ltrot = ltrot+2*thtrot
                 if (projector) then
                   Write(50,*) 'Projective version'
                   Write(50,*) 'Theta         : ', theta
                   Write(50,*) 'Tau_max       : ', beta
                 else
                   Write(50,*) 'Finite temperture version'
                   Write(50,*) 'Beta          : ', beta
                 endif
                 Write(50,*) 'dtau,Ltrot_eff: ', dtau,ltrot
                 Write(50,*) 'N_SUN         : ', n_sun
                 Write(50,*) 'N_FL          : ', n_fl
                 Write(50,*) 't             : ', ham_t
                 Write(50,*) 'Ham_U         : ', ham_u
                 Write(50,*) 'Ham_alpha     : ', ham_alpha
                 Write(50,*) 'Percent_change: ', percent_change
                 Write(50,*) 'Ham_chem      : ', ham_chem
 #ifdef MPI
              Endif
 #endif
 #ifdef MPI
              CALL mpi_bcast(ltrot         ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(thtrot        ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(projector     ,1,mpi_logical,0,group_comm,ierr)
              CALL mpi_bcast(ham_t         ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_chem      ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_u         ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_alpha     ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(percent_change,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(dtau          ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(beta          ,1,mpi_real8  ,0,group_comm,ierr)
 #endif
           Case ("Hubbard_Mz")
              n_fl  = 2
              n_sun = 1
 #ifdef MPI
              If (irank_g == 0 ) then
 #endif
                 READ(5,nml=var_hubbard)
                 ltrot = nint(beta/dtau)
                 if (projector) thtrot = nint(theta/dtau)
                 ltrot = ltrot+2*thtrot
                 if (projector) then
                   Write(50,*) 'Projective version'
                   Write(50,*) 'Theta         : ', theta
                   Write(50,*) 'Tau_max       : ', beta
                 else
                   Write(50,*) 'Finite temperture version'
                   Write(50,*) 'Beta          : ', beta
                 endif
                 Write(50,*) 'dtau,Ltrot_eff: ', dtau,ltrot
                 Write(50,*) 'N_SUN         : ', n_sun
                 Write(50,*) 'N_FL          : ', n_fl
                 Write(50,*) 't             : ', ham_t
                 Write(50,*) 'Ham_U         : ', ham_u
                 Write(50,*) 'Ham_chem      : ', ham_chem
 #ifdef MPI
              Endif
 #endif
 #ifdef MPI
              CALL mpi_bcast(ltrot    ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(thtrot   ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(projector,1,mpi_logical,0,group_comm,ierr)
              CALL mpi_bcast(ham_t    ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_chem ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_u    ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(dtau     ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(beta     ,1,mpi_real8  ,0,group_comm,ierr)
 #endif
           Case ("Hubbard_SU2")
              n_fl = 1
              n_sun = 2
 #ifdef MPI
              If (irank_g == 0 ) then
 #endif
                 READ(5,nml=var_hubbard)
                 ltrot = nint(beta/dtau)
                 if (projector) thtrot = nint(theta/dtau)
                 ltrot = ltrot+2*thtrot
                 if (projector) then
                    Write(50,*) 'Projective version'
                    Write(50,*) 'Theta         : ', theta
                    Write(50,*) 'Tau_max       : ', beta
                 else
                    Write(50,*) 'Finite temperture version'
                    Write(50,*) 'Beta          : ', beta
                 endif
                 Write(50,*) 'dtau,Ltrot_eff: ', dtau,ltrot
                 Write(50,*) 'N_SUN         : ', n_sun
                 Write(50,*) 'N_FL          : ', n_fl
                 Write(50,*) 't             : ', ham_t
                 Write(50,*) 'Ham_U         : ', ham_u
                 Write(50,*) 'Ham_chem      : ', ham_chem
 #ifdef MPI
              Endif
 #endif
 #ifdef MPI
              CALL mpi_bcast(ltrot    ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(thtrot   ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(projector,1,mpi_logical,0,group_comm,ierr)
              CALL mpi_bcast(ham_t    ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_chem ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(ham_u    ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(dtau     ,1,mpi_real8  ,0,group_comm,ierr)
              CALL mpi_bcast(beta     ,1,mpi_real8  ,0,group_comm,ierr)
 #endif
           Case ("Hubbard_SU2_Ising")
              n_fl = 1
              n_sun = 2
 #ifdef MPI
              If (irank_g == 0 ) then
 #endif
                 READ(5,nml=var_ising)
                 ltrot = nint(beta/dtau)
                 if (projector) thtrot = nint(theta/dtau)
                 ltrot = ltrot+2*thtrot
                 if (projector) then
                   Write(50,*) 'Projective version'
                   Write(50,*) 'Theta         : ', theta
                   Write(50,*) 'Tau_max       : ', beta
                 else
                   Write(50,*) 'Finite temperture version'
                   Write(50,*) 'Beta          : ', beta
                 endif
                 Write(50,*) 'dtau,Ltrot_eff: ', dtau,ltrot
                 Write(50,*) 'N_SUN         : ', n_sun
                 Write(50,*) 'N_FL          : ', n_fl
                 Write(50,*) 't             : ', ham_t
                 Write(50,*) 'Ham_U         : ', ham_u
                 Write(50,*) 'Ham_chem      : ', ham_chem
                 Write(50,*) 'Ham_xi        : ', ham_xi
                 Write(50,*) 'Ham_J         : ', ham_j
                 Write(50,*) 'Ham_h         : ', ham_h
 #ifdef MPI
              Endif
 #endif
              If ( lattice_type == "Honeycomb" .or. lattice_type == "Pi_Flux" ) then
                 Write(6,*) "Hubbard_SU2_Ising is only implemented for a square lattice"
                 stop
              Endif
 #ifdef MPI
              CALL mpi_bcast(ltrot    ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(thtrot   ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(projector,1,mpi_logical,0,group_comm,ierr)
              CALL mpi_bcast(ham_t    ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_chem ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_u    ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(dtau     ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(beta     ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_xi   ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_j    ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_h    ,1,mpi_real8,0,group_comm,ierr)
 #endif
              Call setup_ising_action
           Case ("t_V")
              n_fl  = 1
 #ifdef MPI
              If (irank_g == 0 ) then
 #endif
                 READ(5,nml=var_t_v )
                 ltrot = nint(beta/dtau)
                 if (projector) thtrot = nint(theta/dtau)
                 ltrot = ltrot+2*thtrot
                 if (projector) then
                   Write(50,*) 'Projective version'
                   Write(50,*) 'Theta         : ', theta
                   Write(50,*) 'Tau_max       : ', beta
                 else
                   Write(50,*) 'Finite temperture version'
                   Write(50,*) 'Beta          : ', beta
                 endif
                 Write(50,*) 'dtau,Ltrot_eff: ', dtau,ltrot
                 Write(50,*) 'N_SUN         : ', n_sun
                 Write(50,*) 'N_FL          : ', n_fl
                 Write(50,*) 't             : ', ham_t
                 Write(50,*) 'Ham_chem      : ', ham_chem
                 Write(50,*) 'Ham_tV         : ', ham_tv
 #ifdef MPI
              Endif
 #endif
 #ifdef MPI
              CALL mpi_bcast(ltrot    ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(thtrot   ,1,mpi_integer,0,group_comm,ierr)
              CALL mpi_bcast(projector,1,mpi_logical,0,group_comm,ierr)
              CALL mpi_bcast(ham_t    ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_chem ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(ham_tv   ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(dtau     ,1,mpi_real8,0,group_comm,ierr)
              CALL mpi_bcast(beta     ,1,mpi_real8,0,group_comm,ierr)
 #endif
           Case default
              Write(6,*) "Model not yet implemented!"
              stop
           end Select
           Call predefined_hopping(lattice_type, ndim, list,invlist, latt, latt_unit, &
            &                      dtau, ham_t, ham_chem, xb_x, xb_y, phi_x, phi_y, &
            &                      n_fl,  checkerboard, symm, op_t )
           if (projector) then
              n_part = ndim/2
              Call predefined_trialwavefunction(lattice_type ,ndim,  list,invlist,latt, latt_unit, &
                   &                            n_part, n_fl,  wf_l, wf_r)
 #ifdef MPI
              If (irank_g == 0) then
 #endif
                 Do nf = 1,n_fl
                    Write(50,*) 'Degen of right trial wave function: ', wf_r(nf)%Degen
                    Write(50,*) 'Degen of left  trial wave function: ', wf_l(nf)%Degen
                 enddo
 #ifdef MPI
              Endif
 #endif
           endif
 #ifdef MPI
           If (irank_g == 0 )  then
 #endif
              close(50)
              Close(5)
 #ifdef MPI
           endif
 #endif
 ! #ifdef MPI
 !           If (Irank == 0 )  then
 ! #endif
 ! #if defined(STAB1)
 !              Write(50,*) 'STAB1 is defined '
 ! #endif
 !
 ! #if defined(QRREF)
 !              Write(50,*) 'QRREF is defined '
 ! #endif
 !              close(50)
 !              Close(5)
 ! #ifdef MPI
 !           endif
 ! #endif
           If (model == "LRC" ) Then
              Call lrc_set_vij(latt, latt_unit, ham_u, ham_alpha, list, invlist)
 #ifdef MPI
              If (irank_g == 0 )  then
 #endif
                 Call lrc_print(latt, latt_unit, list, invlist)
 #ifdef MPI
              Endif
 #endif
           Endif
           call ham_v
ham_v()
subroutine hamiltonian::ham_v ()
Sets the interaction.
Author
ALF Collaboration
Definition at line 577 of file Hamiltonian_Examples.f90.
References dtau, ham_tv, ham_u, ham_xi, invlist, l_bond_inv, latt, latt_unit, lattice_type, model, n_fl, n_sun, ndim, operator_mod::op_make(), operator_mod::op_set(), and op_v.
Referenced by ham_set().
           Implicit none
           Integer :: nf, I, I1, I2,  nc, nc1,  J
           Real (Kind=Kind(0.d0)) :: X
           Select case (model)
           Case ("LRC")
              Allocate(op_v(ndim,n_fl))
              do nf = 1,n_fl
                 do i  = 1, ndim
                    Call op_make(op_v(i,nf),1)
                 enddo
              enddo
              Do nf = 1,n_fl
                 nc = 0
                 Do i = 1,ndim
                    nc = nc + 1
                    op_v(nc,nf)%P(1) = i
                    op_v(nc,nf)%O(1,1) = cmplx(1.d0  ,0.d0, kind(0.d0))
                    op_v(nc,nf)%alpha  = cmplx(-0.5d0,0.d0, kind(0.d0))
                    op_v(nc,nf)%g      = cmplx(0.d0  ,dtau, kind(0.d0))
                    op_v(nc,nf)%type   = 3
                    Call op_set( op_v(nc,nf) )
                 Enddo
              Enddo
           Case ("Hubbard_SU2")
              !Write(50,*) 'Model is ', Model
              Allocate(op_v(ndim,n_fl))
              do nf = 1,n_fl
                 do i  = 1, ndim
                    Call op_make(op_v(i,nf),1)
                 enddo
              enddo
              Do nf = 1,n_fl
                 nc = 0
                 Do i = 1,ndim
                    nc = nc + 1
                    op_v(nc,nf)%P(1) = i
                    op_v(nc,nf)%O(1,1) = cmplx(1.d0  ,0.d0, kind(0.d0))
                    op_v(nc,nf)%alpha  = cmplx(-0.5d0,0.d0, kind(0.d0))
                    !! Three fields
                    op_v(nc,nf)%g      = sqrt(cmplx(-dtau*ham_u/(dble(n_sun)), 0.d0, kind(0.d0)))
                    op_v(nc,nf)%type   = 2
                    !! Hirsch Decomp  *** This is just for testing  type = 3 **   This was just for testing
                    !! Op_V(nc,nf)%g      = cmplx(0.d0, acos(exp(-DTAU*ham_U/2.d0)), kind(0.D0))
                    !! Op_V(nc,nf)%type   = 3
                    Call op_set( op_v(nc,nf) )
                 Enddo
              Enddo
           Case ("Hubbard_Mz")
              Allocate(op_v(ndim,n_fl))
              do nf = 1,n_fl
                 do i  = 1, ndim
                    Call op_make(op_v(i,nf),1)
                 enddo
              enddo
              Do nf = 1,n_fl
                 nc = 0
                 x = 1.d0
                 if (nf == 2) x = -1.d0
                 Do i = 1,ndim
                    nc = nc + 1
                    op_v(nc,nf)%P(1) = i
                    op_v(nc,nf)%O(1,1) = cmplx(1.d0, 0.d0, kind(0.d0))
                    op_v(nc,nf)%g      = x*sqrt(cmplx(dtau*ham_u/2.d0, 0.d0, kind(0.d0)))
                    op_v(nc,nf)%alpha  = cmplx(0.d0, 0.d0, kind(0.d0))
                    op_v(nc,nf)%type   = 2
                    Call op_set( op_v(nc,nf) )
                 Enddo
              Enddo
           Case ("Hubbard_SU2_Ising")
              Allocate(op_v(3*ndim,n_fl))
              do nf = 1,n_fl
                 do i  =  1, latt_unit%N_coord*ndim
                    call op_make(op_v(i,nf),2)
                 enddo
                 do i  = latt_unit%N_coord*ndim +1 ,  latt_unit%N_coord*ndim + ndim ! For Hubbatd
                    Call op_make(op_v(i,nf),1)
                 enddo
              enddo
              Do nc = 1,ndim*latt_unit%N_coord   ! Runs over bonds.  Coordination number = 2.
                 ! For the square lattice Ndim = Latt%N
                 i1 = l_bond_inv(nc,1)
                 i2 = i1
                 if ( l_bond_inv(nc,2)  == 1 ) i2 = latt%nnlist(i1,1,0)
                 if ( l_bond_inv(nc,2)  == 2 ) i2 = latt%nnlist(i1,0,1)
                 op_v(nc,1)%P(1) = i1
                 op_v(nc,1)%P(2) = i2
                 op_v(nc,1)%O(1,2) = cmplx(1.d0 ,0.d0, kind(0.d0))
                 op_v(nc,1)%O(2,1) = cmplx(1.d0 ,0.d0, kind(0.d0))
                 op_v(nc,1)%g = cmplx(-dtau*ham_xi,0.d0,kind(0.d0))
                 op_v(nc,1)%alpha = cmplx(0d0,0.d0, kind(0.d0))
                 op_v(nc,1)%type =1
                 Call op_set( op_v(nc,1) )
              Enddo
              Do i = 1,ndim
                 nc1 = latt_unit%N_coord*ndim + i
                 op_v(nc1,1)%P(1)   = i
                 op_v(nc1,1)%O(1,1) = cmplx(1.d0  ,0.d0, kind(0.d0))
                 op_v(nc1,1)%g      = sqrt(cmplx(-dtau*ham_u/(dble(n_sun)), 0.d0, kind(0.d0)))
                 op_v(nc1,1)%alpha  = cmplx(-0.5d0,0.d0, kind(0.d0))
                 op_v(nc1,1)%type   = 2
                 !!  Hirsch Decomp  *** This is just for testing  type = 3 **
                 !!Op_V(nc1,1)%g      = cmplx(0.d0, acos(exp(-DTAU*ham_U/2.d0)), kind(0.D0))
                 !!Op_V(nc1,1)%type   = 3
                 Call op_set( op_v(nc1,1) )
              Enddo
           case ("t_V")
              Allocate(op_v(latt_unit%N_coord*latt%N,1))
              do i  =  1, latt_unit%N_coord*latt%N
                 call op_make(op_v(i,1),2)
              enddo
              select case (lattice_type)
              case ("Square")
                 !Write(6,*) "N_coord, Latt%N", N_coord, Latt%N, Dtau, ham_tV
                 nc = 0
                 do i = 1,latt%N
                    i1 = i
                    do nc1 = 1,latt_unit%N_coord
                       nc = nc + 1
                       if (nc1 == 1 ) i2 = latt%nnlist(i,1,0)
                       if (nc1 == 2 ) i2 = latt%nnlist(i,0,1)
                       op_v(nc,1)%P(1) = i1
                       op_v(nc,1)%P(2) = i2
                       op_v(nc,1)%O(1,2) = cmplx(1.d0 ,0.d0, kind(0.d0))
                       op_v(nc,1)%O(2,1) = cmplx(1.d0 ,0.d0, kind(0.d0))
                       op_v(nc,1)%g      = sqrt(cmplx(-dtau*ham_tv, 0.d0, kind(0.d0)))
                       op_v(nc,1)%alpha  = cmplx(0.d0, 0.d0, kind(0.d0))
                       op_v(nc,1)%type   = 2
                       Call op_set( op_v(nc,1) )
                    Enddo
                 Enddo
              case ("Pi_Flux")
                 nc = 0
                 do i = 1,latt%N
                    i1 = invlist(i,1)
                    do nc1 = 1,latt_unit%N_coord
                       nc = nc + 1
                       If (nc1 == 1 )  i2 = invlist(i,2)
                       If (nc1 == 2 )  i2 = invlist(latt%nnlist(i,0, 1),2)
                       If (nc1 == 3 )  i2 = invlist(latt%nnlist(i,-1,1),2)
                       If (nc1 == 4 )  i2 = invlist(latt%nnlist(i,-1,0),2)
                       op_v(nc,1)%P(1) = i1
                       op_v(nc,1)%P(2) = i2
                       op_v(nc,1)%O(1,2) = cmplx(1.d0 ,0.d0, kind(0.d0))
                       op_v(nc,1)%O(2,1) = cmplx(1.d0 ,0.d0, kind(0.d0))
                       op_v(nc,1)%g     = sqrt(cmplx(-dtau*ham_tv, 0.d0, kind(0.d0)))
                       op_v(nc,1)%alpha = cmplx(0.d0, 0.d0, kind(0.d0))
                       op_v(nc,1)%type  = 2
                       Call op_set( op_v(nc,1) )
                    Enddo
                 Enddo
              case default
                 Write(6,*) "Lattice for t-V  not implemented"
                 stop
              End select
           case default
              Write(6,*) "Model not yet implemented!"
              stop
           end Select
hamiltonian_set_nsigma()
subroutine hamiltonian::hamiltonian_set_nsigma (real (kind=kind(0.d0)), dimension(:,:), intent(out), allocatable Initial_field)
The user can set the initial field.
Author
ALF Collaboration
Parameters
[OUT] Initial_field Real(:,:)
  Upon entry Initial_field is not allocated. If alloacted then it will contain the
  the initial field
Definition at line 1537 of file Hamiltonian_Examples.f90.
Referenced by main().
         Implicit none
         Real (Kind=Kind(0.d0)), allocatable, dimension(:,:), Intent(OUT) :: Initial_field
init_obs()
subroutine hamiltonian::init_obs (integer, intent(in) Ltau)
Initializes observables to zero before each bins. No need to change this routine.
Author
ALF Collaboration
Definition at line 1413 of file Hamiltonian_Examples.f90.
References obs_eq, obs_scal, obs_tau, observables::obser_latt_init(), and observables::obser_vec_init().
Referenced by main().
           Implicit none
           Integer, Intent(In) :: Ltau
           ! Local
           Integer :: I
           Do i = 1,Size(obs_scal,1)
              Call obser_vec_init(obs_scal(i))
           Enddo
           Do i = 1,Size(obs_eq,1)
              Call obser_latt_init(obs_eq(i))
           Enddo
           If (ltau == 1) then
              Do i = 1,Size(obs_tau,1)
                 Call obser_latt_init(obs_tau(i))
              Enddo
           Endif
obser()
subroutine hamiltonian::obser (complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) GR, complex (kind=kind(0.d0)), intent(in) Phase, integer, intent(in) Ntau)
Computes equal time observables.
Author
ALF Collaboration
Parameters
[IN] Gr Complex(:,:,:)
  Green function: Gr(I,J,nf) = <c_{I,nf } c^{dagger}_{J,nf } > on time slice ntau
[IN] Phase Complex
  Phase
[IN] Ntau Integer
  Time slice
Definition at line 1101 of file Hamiltonian_Examples.f90.
References ham_t, ham_u, invlist, latt, latt_unit, lattice_type, list, lrc_mod::lrc_v_int(), model, n_sun, obs_eq, and obs_scal.
Referenced by main().
           Implicit none
           Complex (Kind=Kind(0.d0)), INTENT(IN) :: GR(Ndim,Ndim,N_FL)
           Complex (Kind=Kind(0.d0)), Intent(IN) :: PHASE
           Integer, INTENT(IN)          :: Ntau
           !Local
           Complex (Kind=Kind(0.d0)) :: GRC(Ndim,Ndim,N_FL), ZK
           Complex (Kind=Kind(0.d0)) :: Zrho, Zkin, ZPot, Z, ZP,ZS, ZZ, ZXY
           Integer :: I,J, imj, nf, dec, I1, J1, no_I, no_J,n
           zp = phase/Real(Phase, kind(0.D0))
           zs = Real(Phase, kind(0.D0))/Abs(Real(Phase, kind(0.D0)))
           Do nf = 1,n_fl
              Do i = 1,ndim
                 Do j = 1,ndim
                    grc(i, j, nf) = -gr(j, i, nf)
                 Enddo
                 grc(i, i, nf) = 1.d0 + grc(i, i, nf)
              Enddo
           Enddo
           ! GRC(i,j,nf) = < c^{dagger}_{j,nf } c_{j,nf } >
           ! Compute scalar observables.
           Do i = 1,Size(obs_scal,1)
              obs_scal(i)%N         =  obs_scal(i)%N + 1
              obs_scal(i)%Ave_sign  =  obs_scal(i)%Ave_sign + Real(ZS,kind(0.d0))
           Enddo
           zkin = cmplx(0.d0, 0.d0, kind(0.d0))
           Do nf = 1,n_fl
              Do i = 1,latt%N
                 Do n = 1,latt_unit%N_coord
                    Select Case (lattice_type)
                    Case ("Square")
                       i1 = i
                       If (n == 1)  j1 = latt%nnlist(i,1,0)
                       If (n == 2)  j1 = latt%nnlist(i,0,1)
                    Case ("Honeycomb")
                       i1 = invlist(i,1)
                       If (n == 1)  j1 = invlist(i,2)
                       If (n == 2)  j1 = invlist(latt%nnlist(i,1,-1),2)
                       If (n == 3)  j1 = invlist(latt%nnlist(i,0,-1),2)
                    Case Default
                       stop
                    end Select
                    zkin = zkin +  grc( i1,j1, nf ) + grc(j1,i1,nf)
                 Enddo
              Enddo
           Enddo
           zkin = -ham_t*zkin * dble(n_sun)
           obs_scal(1)%Obs_vec(1)  =    obs_scal(1)%Obs_vec(1) + zkin *zp* zs
           zpot = cmplx(0.d0, 0.d0, kind(0.d0))
           If ( model == "Hubbard_SU2" .or. model == "Hubbard_SU2_Ising" ) then
              dec = 1
              Do i = 1,ndim
                 zpot = zpot + grc(i,i,1) * grc(i,i, dec)
              Enddo
              zpot = zpot*ham_u
           elseif (model == "Hubbard_MZ") then
              dec = 2
              Do i = 1,ndim
                 zpot = zpot + grc(i,i,1) * grc(i,i, dec)
              Enddo
              zpot = zpot*ham_u
           elseif (model == "LRC") then
              z =  cmplx(dble(n_sun), 0.d0, kind(0.d0))
              Do i = 1,ndim
                 zpot = zpot +    lrc_v_int(i,i)* grc(i,i, 1)* grc(i,i,1)
                 Do j = i+1,ndim
                    zpot = zpot + z*lrc_v_int(i,j)*(z *  grc(i,i, 1)* grc(j,j,1)  + grc(i,j,1)*gr(i,j,1) )
                 Enddo
              Enddo
           Endif
           obs_scal(2)%Obs_vec(1)  =  obs_scal(2)%Obs_vec(1) + zpot * zp*zs
           zrho = cmplx(0.d0,0.d0, kind(0.d0))
           Do nf = 1,n_fl
              Do i = 1,ndim
                 zrho = zrho + grc(i,i,nf)
              enddo
           enddo
           zrho = zrho* dble(n_sun)
           obs_scal(3)%Obs_vec(1)  =    obs_scal(3)%Obs_vec(1) + zrho * zp*zs
           obs_scal(4)%Obs_vec(1)  =    obs_scal(4)%Obs_vec(1) + (zkin + zpot)*zp*zs
           ! Compute spin-spin, Green, and den-den correlation functions  !  This is general N_SUN, and  N_FL = 1
           DO i = 1,Size(obs_eq,1)
              obs_eq(i)%N        = obs_eq(i)%N + 1
              obs_eq(i)%Ave_sign = obs_eq(i)%Ave_sign + real(ZS,kind(0.d0))
           ENDDO
           If ( model == "Hubbard_SU2" .or. model == "Hubbard_SU2_Ising" .or. model == "t_V" .or. model== "LRC"  ) then
              z =  cmplx(dble(n_sun), 0.d0, kind(0.d0))
              Do i1 = 1,ndim
                 i    = list(i1,1)
                 no_i = list(i1,2)
                 Do j1 = 1,ndim
                    j    = list(j1,1)
                    no_j = list(j1,2)
                    imj = latt%imj(i,j)
                    ! Green
                    obs_eq(1)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(1)%Obs_Latt(imj,1,no_i,no_j) + &
                         &               z * grc(i1,j1,1) *  zp*zs
                    ! SpinZ
                    obs_eq(2)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(2)%Obs_Latt(imj,1,no_i,no_j) + &
                         &               z * grc(i1,j1,1) * gr(i1,j1,1) * zp*zs
                    ! SpinXY
                    obs_eq(3)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(3)%Obs_Latt(imj,1,no_i,no_j) + &
                         &               z * grc(i1,j1,1) * gr(i1,j1,1) * zp*zs
                    ! SpinT
                    obs_eq(5)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(5)%Obs_Latt(imj,1,no_i,no_j) + &
                         &               z * grc(i1,j1,1) * gr(i1,j1,1) * zp*zs
                    ! Den
                    obs_eq(4)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(4)%Obs_Latt(imj,1,no_i,no_j)  +  &
                         &     (    grc(i1,i1,1) * grc(j1,j1,1) *z     + &
                         &          grc(i1,j1,1) * gr(i1,j1,1 )           &
                         &                                   ) * z* zp*zs
                 ENDDO
                 obs_eq(4)%Obs_Latt0(no_i) =  obs_eq(4)%Obs_Latt0(no_i) +  z * grc(i1,i1,1) * zp * zs
              ENDDO
           elseif (model == "Hubbard_Mz" ) Then
              Do i1 = 1,ndim
                 i    = list(i1,1)
                 no_i = list(i1,2)
                 Do j1 = 1,ndim
                    j    = list(j1,1)
                    no_j = list(j1,2)
                    imj = latt%imj(i,j)
                    ! Green
                    obs_eq(1)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(1)%Obs_Latt(imj,1,no_i,no_j) + &
                         &                          ( grc(i1,j1,1) + grc(i1,j1,2)) *  zp*zs
                    ! SpinZ
                    zz =       grc(i1,j1,1) * gr(i1,j1,1) +  grc(i1,j1,2) * gr(i1,j1,2)    + &
                         &    (grc(i1,i1,2) - grc(i1,i1,1))*(grc(j1,j1,2) - grc(j1,j1,1))
                    obs_eq(2)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(2)%Obs_Latt(imj,1,no_i,no_j) + zz* zp*zs
                    ! SpinXY
                    ! c^d_(i,u) c_(i,d) c^d_(j,d) c_(j,u)  +  c^d_(i,d) c_(i,u) c^d_(j,u) c_(j,d)
                    zxy =  grc(i1,j1,1) * gr(i1,j1,2) +  grc(i1,j1,2) * gr(i1,j1,1)
                    obs_eq(3)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(3)%Obs_Latt(imj,1,no_i,no_j) + zxy* zp*zs
                    ! SpinT
                    obs_eq(5)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(5)%Obs_Latt(imj,1,no_i,no_j) + (2.d0*zxy + zz)*zp*zs/3.d0
                    !Den
                    obs_eq(4)%Obs_Latt(imj,1,no_i,no_j) =  obs_eq(4)%Obs_Latt(imj,1,no_i,no_j) + &
                         & (   grc(i1,j1,1) * gr(i1,j1,1) +  grc(i1,j1,2) * gr(i1,j1,2)    + &
                         &   (grc(i1,i1,2) + grc(i1,i1,1))*(grc(j1,j1,2) + grc(j1,j1,1))     ) * zp*zs
                 enddo
                 obs_eq(4)%Obs_Latt0(no_i) =  obs_eq(4)%Obs_Latt0(no_i) +  (grc(i1,i1,1) + grc(i1,i1,2)) * zp*zs
              enddo
           Endif
obsert()
subroutine hamiltonian::obsert (integer, intent(in) NT, complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) GT0, complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) G0T, complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) G00, complex (kind=kind(0.d0)), dimension(ndim,ndim,n_fl), intent(in) GTT, complex (kind=kind(0.d0)), intent(in) PHASE)
Computes time displaced observables.
Author
ALF Collaboration
Parameters
[IN] NT, Integer
  Imaginary time
[IN] GT0, GTT, G00, GTT, Complex(:,:,:)
  Green functions:
  GT0(I,J,nf) = <T c_{I,nf }(tau) c^{dagger}_{J,nf }(0  )>
  G0T(I,J,nf) = <T c_{I,nf }(0  ) c^{dagger}_{J,nf }(tau)>
  G00(I,J,nf) = <T c_{I,nf }(0  ) c^{dagger}_{J,nf }(0  )>
  GTT(I,J,nf) = <T c_{I,nf }(tau) c^{dagger}_{J,nf }(tau)>
[IN] Phase Complex
  Phase
Definition at line 1288 of file Hamiltonian_Examples.f90.
References latt, list, model, n_sun, and obs_tau.
Referenced by tau_m_mod::tau_m(), and tau_p_mod::tau_p().
           Implicit none
           Integer         , INTENT(IN) :: NT
           Complex (Kind=Kind(0.d0)), INTENT(IN) :: GT0(Ndim,Ndim,N_FL),G0T(Ndim,Ndim,N_FL),G00(Ndim,Ndim,N_FL),GTT(Ndim,Ndim,N_FL)
           Complex (Kind=Kind(0.d0)), INTENT(IN) :: Phase
           !Locals
           Complex (Kind=Kind(0.d0)) :: Z, ZP, ZS
           Integer :: IMJ, I, J, I1, J1, no_I, no_J
           zp = phase/Real(Phase, kind(0.D0))
           zs = Real(Phase, kind(0.D0))/Abs(Real(Phase, kind(0.D0)))
           If (nt == 0 ) then
              DO i = 1,Size(obs_tau,1)
                 obs_tau(i)%N = obs_tau(i)%N + 1
                 obs_tau(i)%Ave_sign = obs_tau(i)%Ave_sign + Real(ZS,kind(0.d0))
              ENDDO
           endif
           If ( model == "Hubbard_SU2" .or. model == "Hubbard_SU2_Ising" .or. model == "t_V" .or. model == "LRC"  ) then
              z =  cmplx(dble(n_sun),0.d0, kind(0.d0))
              Do i1 = 1,ndim
                 i    = list(i1,1)
                 no_i = list(i1,2)
                 Do j1 = 1,ndim
                    j    = list(j1,1)
                    no_j = list(j1,2)
                    imj = latt%imj(i,j)
                    ! Green
                    obs_tau(1)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(1)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         & +  z * gt0(i1,j1,1) * zp* zs
                    ! SpinZ
                    obs_tau(2)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(2)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         &      - z*g0t(j1,i1,1) * gt0(i1,j1,1) *zp*zs
                    ! SpinXY
                    obs_tau(3)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(3)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         &      - z*g0t(j1,i1,1) * gt0(i1,j1,1) *zp*zs
                    ! Den
                    obs_tau(4)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(4)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         & + ( z*z*(cmplx(1.d0,0.d0,kind(0.d0)) - gtt(i1,i1,1))*       &
                         &         (cmplx(1.d0,0.d0,kind(0.d0)) - g00(j1,j1,1))  -     &
                         &     z * gt0(i1,j1,1)*g0t(j1,i1,1)                                ) * zp * zs
                 Enddo
                 obs_tau(4)%Obs_Latt0(no_i) = obs_tau(4)%Obs_Latt0(no_i) + &
                      &         z*(cmplx(1.d0,0.d0,kind(0.d0)) - gtt(i1,i1,1)) * zp * zs
              Enddo
           Elseif ( model == "Hubbard_Mz"  ) then
              Do i1 = 1,ndim
                 i    = list(i1,1)
                 no_i = list(i1,2)
                 Do j1 = 1,ndim
                    j    = list(j1,1)
                    no_j = list(j1,2)
                    imj = latt%imj(i,j)
                    !Green
                    obs_tau(1)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(1)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         &   +   ( gt0(i1,j1,1) + gt0(i1,j1,2) ) * zp* zs
                    !SpinZ
                    obs_tau(2)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(2)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                        & +  ( &
                        &    (gtt(i1,i1,1) -  gtt(i1,i1,2) ) * ( g00(j1,j1,1)  -  g00(j1,j1,2) )   &
                        &  - (g0t(j1,i1,1) * gt0(i1,j1,1)  +  g0t(j1,i1,2) * gt0(i1,j1,2) )    )*zp*zs
                    !SpinXY
                    obs_tau(3)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(3)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         &  - &
                         &   (g0t(j1,i1,1) * gt0(i1,j1,2)  +  g0t(j1,i1,2) * gt0(i1,j1,1))*zp*zs
                    !Den
                    obs_tau(4)%Obs_Latt(imj,nt+1,no_i,no_j) =  obs_tau(4)%Obs_Latt(imj,nt+1,no_i,no_j)  &
                         & +  (                                        &
                         &    (cmplx(2.d0,0.d0,kind(0.d0)) - gtt(i1,i1,1) - gtt(i1,i1,2) ) * &
                         &    (cmplx(2.d0,0.d0,kind(0.d0)) - g00(j1,j1,1) - g00(j1,j1,2) )   &
                         & -  ( g0t(j1,i1,1) * gt0(i1,j1,1) + g0t(j1,i1,2) * gt0(i1,j1,2) )  )*zp*zs
                 enddo
                 obs_tau(4)%Obs_Latt0(no_i) =  obs_tau(4)%Obs_Latt0(no_i) + &
                      &       (cmplx(2.d0,0.d0,kind(0.d0)) - gtt(i1,i1,1) - gtt(i1,i1,2)) * zp * zs
              Enddo
           Endif
pr_obs()
subroutine hamiltonian::pr_obs (integer, intent(in) LTAU)
Prints out the bins. No need to change this routine.
Author
ALF Collaboration
Definition at line 1381 of file Hamiltonian_Examples.f90.
References dtau, group_comm, latt, obs_eq, obs_scal, obs_tau, observables::print_bin_latt(), and observables::print_bin_vec().
Referenced by main().
           Implicit none
           Integer,  Intent(In) ::  Ltau
           !Local
           Integer :: I
           Do i = 1,Size(obs_scal,1)
              Call  print_bin_vec(obs_scal(i),group_comm)
           enddo
           Do i = 1,Size(obs_eq,1)
              Call  print_bin_latt(obs_eq(i),latt,dtau,group_comm)
           enddo
           If (ltau  == 1 ) then
              Do i = 1,Size(obs_tau,1)
                 Call  print_bin_latt(obs_tau(i),latt,dtau,group_comm)
              enddo
           endif
s0()
real (kind=kind(0.d0)) function hamiltonian::s0 (integer, intent(in) n, integer, intent(in) nt, real (kind=kind(0.d0)), intent(in) Hs_new)
Single spin flip S0 ratio.
Author
ALF Collaboration
S0=exp(-S0(new))/exp(-S0(old)) where the new configuration correpsonds to the old one up to a spin flip of Operator n on time slice nt
Parameters
[in] n Operator index
[in] nt Time slice
[in] hs_new New local field on time slice nt and operator index n
Definition at line 755 of file Hamiltonian_Examples.f90.
References dtau, dw_ising_space, dw_ising_tau, ising_nnlist, lrc_mod::lrc_s0(), ltrot, model, n_sun, nsigma, and op_v.
Referenced by global_move_tau(), wrapgr_mod::wrapgrdo(), and wrapgr_mod::wrapgrup().
           Implicit none
           Integer, Intent(IN) :: n
           Integer, Intent(IN) :: nt
           Real (Kind=Kind(0.d0)), Intent(In) :: Hs_new
           Integer :: nt1,I
           !Write(6,*) "Hi1"
           s0 = 1.d0
           If ( op_v(n,1)%type == 1 ) then
              do i = 1,4
                 s0 = s0*dw_ising_space(nsigma%i(n,nt)*nsigma%i(ising_nnlist(n,i),nt))
              enddo
              nt1 = nt +1
              if (nt1 > ltrot) nt1 = 1
              s0 = s0*dw_ising_tau(nsigma%i(n,nt)*nsigma%i(n,nt1))
              nt1 = nt - 1
              if (nt1 < 1  ) nt1 = ltrot
              s0 = s0*dw_ising_tau(nsigma%i(n,nt)*nsigma%i(n,nt1))
              If (s0 < 0.d0) Write(6,*) 'S0 : ', s0
           endif
           If (model == "LRC" ) then
              !Write(6,*) "Hi2"
              s0 = lrc_s0(n,dtau,nsigma%f(:,nt),hs_new,n_sun)
           Endif
setup_ising_action()
subroutine hamiltonian::setup_ising_action ()
Setup bonds and median lattice.
Author
ALF Collaboration
Note that the median lattice on which the Ising bond fields are defined could be defined generally in the predefined lattice subroutine.
Definition at line 798 of file Hamiltonian_Examples.f90.
References dtau, dw_ising_space, dw_ising_tau, ham_h, ham_j, ising_nnlist, l1, l2, l_bond, l_bond_inv, latt, and latt_unit.
Referenced by ham_set().
           ! This subroutine sets up lists and arrays so as to enable an
           ! an efficient calculation of  S0(n,nt)
           Integer :: nc, nth, n, n1, n2, n3, n4, I, I1, n_orientation
           Real (Kind=Kind(0.d0)) :: X_p(2)
           ! Setup list of bonds for the square lattice.
           Allocate (l_bond(latt%N,2),  l_bond_inv(latt%N*latt_unit%N_coord,2) )
           nc = 0
           do nth = 1,2*latt_unit%N_coord
              Do n1= 1, l1/2
                 Do n2 = 1,l2
                    nc = nc + 1
                    n_orientation = 1
                    i1 = 1
                    If (nth == 1 ) then
                       x_p = dble(2*n1)*latt%a1_p + dble(n2)*latt%a2_p
                       i1 = inv_r(x_p,latt)
                       n_orientation = 1
                    elseif (nth == 2) then
                       x_p = dble(2*n1)*latt%a1_p + dble(n2)*latt%a2_p  + latt%a1_p
                       i1 = inv_r(x_p,latt)
                       n_orientation = 1
                    elseif (nth == 3) then
                       x_p = dble(n2)*latt%a1_p + dble(2*n1)*latt%a2_p
                       i1 = inv_r(x_p,latt)
                       n_orientation = 2
                    elseif (nth == 4) then
                       x_p = dble(n2)*latt%a1_p + dble(2*n1)*latt%a2_p  + latt%a2_p
                       i1 = inv_r(x_p,latt)
                       n_orientation = 2
                    endif
                    l_bond(i1,n_orientation) = nc
                    l_bond_inv(nc,1) = i1
                    l_bond_inv(nc,2) = n_orientation
                    ! The bond is given by  I1, I1 + a_(n_orientation).
                 Enddo
              Enddo
           Enddo
           ! Setup the nearest neigbour lists for the Ising spins.
           allocate(ising_nnlist(2*latt%N,4))
           do i  = 1,latt%N
              n  = l_bond(i,1)
              n1 = l_bond(latt%nnlist(i, 1, 0),2)
              n2 = l_bond(latt%nnlist(i, 0, 0),2)
              n3 = l_bond(latt%nnlist(i, 0,-1),2)
              n4 = l_bond(latt%nnlist(i, 1,-1),2)
              ising_nnlist(n,1) = n1
              ising_nnlist(n,2) = n2
              ising_nnlist(n,3) = n3
              ising_nnlist(n,4) = n4
              n  = l_bond(i,2)
              n1 = l_bond(latt%nnlist(i, 0, 1),1)
              n2 = l_bond(latt%nnlist(i,-1, 1),1)
              n3 = l_bond(latt%nnlist(i,-1, 0),1)
              n4 = l_bond(latt%nnlist(i, 0, 0),1)
              ising_nnlist(n,1) = n1
              ising_nnlist(n,2) = n2
              ising_nnlist(n,3) = n3
              ising_nnlist(n,4) = n4
           enddo
           dw_ising_tau( 1) = tanh(dtau*ham_h)
           dw_ising_tau(-1) = 1.d0/dw_ising_tau(1)
           dw_ising_space( 1) = exp(-2.d0*dtau*ham_j)
           dw_ising_space(-1) = exp( 2.d0*dtau*ham_j)
Variable Documentation
beta
real (kind=kind(0.d0)), private hamiltonian::beta private
Definition at line 157 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
checkerboard
logical, private hamiltonian::checkerboard private
Definition at line 159 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
dtau
real (kind=kind(0.d0)), private hamiltonian::dtau private
Definition at line 157 of file Hamiltonian_Examples.f90.
Referenced by delta_s0_global(), global_move_tau(), ham_set(), ham_v(), pr_obs(), s0(), and setup_ising_action().
       real (Kind=Kind(0.d0)),        private :: Dtau, Beta, Theta
dw_ising_space
real (kind=kind(0.d0)), dimension(-1:1), private hamiltonian::dw_ising_space private
Definition at line 169 of file Hamiltonian_Examples.f90.
Referenced by s0(), and setup_ising_action().
dw_ising_tau
real (kind=kind(0.d0)), dimension(-1:1), private hamiltonian::dw_ising_tau private
Storage for the Ising action.
Definition at line 169 of file Hamiltonian_Examples.f90.
Referenced by s0(), and setup_ising_action().
       Real (Kind=Kind(0.d0)),  private :: DW_Ising_tau(-1:1), DW_Ising_Space(-1:1)
group_comm
integer hamiltonian::group_comm
Definition at line 147 of file Hamiltonian_Examples.f90.
Referenced by confin(), confout(), global_mod::exchange_step(), global_mod::global_tempering_pr(), ham_set(), main(), and pr_obs().
       Integer              :: Group_Comm
ham_alpha
real (kind=kind(0.d0)), private hamiltonian::ham_alpha private
Definition at line 155 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
       real (Kind=Kind(0.d0)),        private :: ham_alpha, Percent_change
ham_chem
real (kind=kind(0.d0)), private hamiltonian::ham_chem private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
ham_h
real (kind=kind(0.d0)), private hamiltonian::ham_h private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by delta_s0_global(), ham_set(), and setup_ising_action().
ham_j
real (kind=kind(0.d0)), private hamiltonian::ham_j private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by delta_s0_global(), ham_set(), and setup_ising_action().
ham_t
real (kind=kind(0.d0)), private hamiltonian::ham_t private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), and obser().
       real (Kind=Kind(0.d0)),        private :: ham_T , ham_U,  Ham_chem, Ham_h, Ham_J, Ham_xi, XB_X, Phi_X, Ham_tV
ham_tv
real (kind=kind(0.d0)), private hamiltonian::ham_tv private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), and ham_v().
ham_u
real (kind=kind(0.d0)), private hamiltonian::ham_u private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), ham_v(), and obser().
ham_xi
real (kind=kind(0.d0)), private hamiltonian::ham_xi private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), and ham_v().
invlist
integer, dimension(:,:), allocatable, private hamiltonian::invlist private
Definition at line 160 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), ham_v(), and obser().
ising_nnlist
integer, dimension(:,:), allocatable, private hamiltonian::ising_nnlist private
Definition at line 170 of file Hamiltonian_Examples.f90.
Referenced by s0(), and setup_ising_action().
l1
integer, private hamiltonian::l1 private
Definition at line 153 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), and setup_ising_action().
       Integer,              private :: L1, L2
l2
integer, private hamiltonian::l2 private
Definition at line 153 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), and setup_ising_action().
l_bond
integer, dimension(:,:), allocatable, private hamiltonian::l_bond private
Definition at line 170 of file Hamiltonian_Examples.f90.
Referenced by delta_s0_global(), and setup_ising_action().
       Integer,  allocatable ,  private :: L_bond(:,:), L_bond_inv(:,:), Ising_nnlist(:,:)
l_bond_inv
integer, dimension(:,:), allocatable, private hamiltonian::l_bond_inv private
Definition at line 170 of file Hamiltonian_Examples.f90.
Referenced by ham_v(), and setup_ising_action().
latt
type (lattice), private hamiltonian::latt private
Definition at line 151 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), delta_s0_global(), ham_set(), ham_v(), obser(), obsert(), pr_obs(), and setup_ising_action().
       type(lattice),       private :: latt
latt_unit
type (unit_cell), private hamiltonian::latt_unit private
Definition at line 152 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), ham_set(), ham_v(), obser(), and setup_ising_action().
       type(unit_cell),     private :: latt_unit
lattice_type
character (len=64), private hamiltonian::lattice_type private
Definition at line 158 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), ham_v(), and obser().
list
integer, dimension(:,:), allocatable, private hamiltonian::list private
Definition at line 160 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), obser(), and obsert().
       Integer, allocatable, private :: List(:,:), Invlist(:,:)  ! For orbital structure of Unit cell
ltrot
integer hamiltonian::ltrot
Definition at line 144 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), global_mod::compute_ratio_global(), confin(), confout(), delta_s0_global(), ham_set(), main(), s0(), tau_m_mod::tau_m(), and tau_p_mod::tau_p().
       Integer              :: Ltrot
model
character (len=64), private hamiltonian::model private
Definition at line 158 of file Hamiltonian_Examples.f90.
Referenced by delta_s0_global(), global_move_tau(), ham_set(), ham_v(), obser(), obsert(), and s0().
       Character (len=64),   private :: Model, Lattice_type
n_fl
integer hamiltonian::n_fl
Definition at line 142 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_fermion_det(), global_mod::compute_ratio_global(), global_mod::exchange_step(), global_mod::global_updates(), ham_set(), ham_v(), hop_mod::hop_mod_init(), main(), wrapgr_mod::wrapgr_alloc(), wrapgr_mod::wrapgr_placegr(), wrapgr_mod::wrapgr_random_update(), wrapgr_mod::wrapgr_test(), wrapgrdo(), wrapgr_mod::wrapgrdo(), wrapgrup(), wrapgr_mod::wrapgrup(), wrapul(), and wrapur().
       Integer              :: N_FL
n_sun
integer hamiltonian::n_sun
Definition at line 143 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_ratio_global(), global_mod::exchange_step(), global_move_tau(), global_mod::global_updates(), ham_set(), ham_v(), main(), obser(), obsert(), s0(), and upgrade2().
       Integer              :: N_SUN
ndim
integer hamiltonian::ndim
Definition at line 141 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_fermion_det(), global_mod::compute_ratio_global(), global_mod::exchange_step(), global_move_tau(), global_mod::global_updates(), ham_set(), ham_v(), hop_mod::hop_mod_init(), main(), wrapgr_mod::wrapgr_alloc(), wrapgr_mod::wrapgr_placegr(), wrapgr_mod::wrapgr_random_update(), wrapgrdo(), wrapgr_mod::wrapgrdo(), and wrapgr_mod::wrapgrup().
       Integer              :: Ndim
nsigma
class (fields), allocatable hamiltonian::nsigma
Definition at line 140 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_ratio_global(), confin(), confout(), delta_s0_global(), global_mod::exchange_step(), global_move(), global_move_tau(), global_mod::global_updates(), main(), tau_m_mod::propr(), tau_m_mod::proprm1(), s0(), upgrade2(), wrapgr_mod::wrapgr_placegr(), wrapgr_mod::wrapgr_random_update(), wrapgrdo(), wrapgr_mod::wrapgrdo(), wrapgrup(), wrapgr_mod::wrapgrup(), wrapul(), and wrapur().
       class(fields)                   ,   allocatable :: nsigma
obs_eq
type (obser_latt), dimension(:), allocatable, private hamiltonian::obs_eq private
Definition at line 165 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), init_obs(), obser(), and pr_obs().
       type(obser_latt),  private, dimension(:), allocatable ::   obs_eq
obs_scal
type (obser_vec), dimension(:), allocatable, private hamiltonian::obs_scal private
Privat Observables.
Definition at line 164 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), init_obs(), obser(), and pr_obs().
       type(obser_vec ),  private, dimension(:), allocatable ::   obs_scal
obs_tau
type (obser_latt), dimension(:), allocatable, private hamiltonian::obs_tau private
Definition at line 166 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), init_obs(), obsert(), and pr_obs().
       type(obser_latt),  private, dimension(:), allocatable ::   obs_tau
one_dimensional
logical, private hamiltonian::one_dimensional private
Definition at line 159 of file Hamiltonian_Examples.f90.
       Logical,              private :: One_dimensional, Checkerboard
op_t
type (operator), dimension(:,:), allocatable hamiltonian::op_t
Definition at line 137 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), hop_mod::hop_mod_init(), hop_mod::hop_mod_mmthl(), hop_mod::hop_mod_mmthl_m1(), hop_mod::hop_mod_mmthl_m1_1d2(), hop_mod::hop_mod_mmthlc(), hop_mod::hop_mod_mmthr(), hop_mod::hop_mod_mmthr_1d2(), and hop_mod::hop_mod_mmthr_m1().
       type(operator),     dimension(:,:), allocatable :: op_t
op_v
type (operator), dimension(:,:), allocatable hamiltonian::op_v
Definition at line 136 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_ratio_global(), confin(), global_mod::exchange_step(), global_move_tau(), global_mod::global_updates(), ham_v(), main(), tau_m_mod::propr(), tau_m_mod::proprm1(), s0(), upgrade2(), wrapgr_mod::wrapgr_placegr(), wrapgr_mod::wrapgr_random_update(), wrapgr_mod::wrapgr_test(), wrapgrdo(), wrapgr_mod::wrapgrdo(), wrapgrup(), wrapgr_mod::wrapgrup(), wrapul(), and wrapur().
       type(operator),     dimension(:,:), allocatable :: op_v
percent_change
real (kind=kind(0.d0)), private hamiltonian::percent_change private
Definition at line 155 of file Hamiltonian_Examples.f90.
Referenced by global_move_tau(), and ham_set().
phi_x
real (kind=kind(0.d0)), private hamiltonian::phi_x private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
phi_y
real (kind=kind(0.d0)), private hamiltonian::phi_y private
Definition at line 156 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
projector
logical hamiltonian::projector
Definition at line 146 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_fermion_det(), global_mod::exchange_step(), global_mod::global_updates(), ham_set(), main(), and tau_m_mod::tau_m().
       Logical              :: Projector
symm
logical hamiltonian::symm
Definition at line 148 of file Hamiltonian_Examples.f90.
Referenced by ham_set(), main(), tau_m_mod::tau_m(), and tau_p_mod::tau_p().
       Logical              :: Symm
theta
real (kind=kind(0.d0)), private hamiltonian::theta private
Definition at line 157 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
thtrot
integer hamiltonian::thtrot
Definition at line 145 of file Hamiltonian_Examples.f90.
Referenced by alloc_obs(), ham_set(), main(), and tau_p_mod::tau_p().
       Integer              :: Thtrot
wf_l
type (wavefunction), dimension(:), allocatable hamiltonian::wf_l
Definition at line 138 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_fermion_det(), global_mod::exchange_step(), global_mod::global_updates(), ham_set(), and main().
       type(wavefunction), dimension(:),   allocatable :: wf_l
wf_r
type (wavefunction), dimension(:), allocatable hamiltonian::wf_r
Definition at line 139 of file Hamiltonian_Examples.f90.
Referenced by global_mod::compute_fermion_det(), global_mod::global_updates(), ham_set(), main(), and tau_m_mod::tau_m().
       type(wavefunction), dimension(:),   allocatable :: wf_r
xb_x
real (kind=kind(0.d0)), private hamiltonian::xb_x private
Definition at line 154 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
xb_y
real (kind=kind(0.d0)), private hamiltonian::xb_y private
Definition at line 156 of file Hamiltonian_Examples.f90.
Referenced by ham_set().
       real (Kind=Kind(0.d0)),        private :: XB_Y, Phi_Y