ALF: wrapgr_mod Module Reference
wrapgr_mod Module Reference
Functions/Subroutines
subroutine wrapgr_alloc
Allocate, Deallocate space.
subroutine wrapgr_dealloc
subroutine wrapgrup (GR, NTAU, PHASE, Propose_S0, Nt_sequential_start, Nt_sequential_end, N_Global_tau)
subroutine wrapgrdo (GR, NTAU, PHASE, Propose_S0, Nt_sequential_start, Nt_sequential_end, N_Global_tau)
subroutine wrapgr_placegr (GR, m, m1, ntau)
The Green function on a given time slice reads G(tau) = (1 + B(tau) B(tau-1,0) B(beta,tau))^(-1) with B(tau) = U_n e^(d_n) U_n^(dag) .... U_1 e^(V_1) U_1^(dag) e^(-dtau H_t) On input you have G(tau,m) = [ 1 + U_m e^(d_m) U_m^(dag) U_m^(dag) ... U_1 e^(V_1) U_1^(dag) e^(-dtau H_t) B(tau-1,0) B(Beta,tau) U_n e^(d_n) U_n^(dag) ...U_(m+1) e^(d_(m+1)) U_(m+1)^(dag) U_(m+1) ] On output you have G(tau, m1)
subroutine wrapgr_random_update (GR, m, ntau, PHASE, N_Global_tau)
subroutine wrapgr_sort (Flip_length, Flip_list, Flip_value)
subroutine wrapgr_test (Gr, ntau)
Variables
complex(kind=kind(0.d0)), dimension(:,:,:), allocatable, private gr_st
Privat.
Function/Subroutine Documentation
wrapgr_alloc()
subroutine wrapgr_mod::wrapgr_alloc ()
Allocate, Deallocate space.
Author
ALF-project
Definition at line 66 of file Wrapgr_mod.f90.
References gr_st, hamiltonian::n_fl, and hamiltonian::ndim.
Referenced by main().
     Implicit none
     Allocate (gr_st(ndim,ndim,n_fl) )
wrapgr_dealloc()
subroutine wrapgr_mod::wrapgr_dealloc ()
Definition at line 71 of file Wrapgr_mod.f90.
References gr_st.
Referenced by main().
     Implicit none
     deallocate ( gr_st )
wrapgr_placegr()
subroutine wrapgr_mod::wrapgr_placegr (complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, integer, intent(in) m, integer, intent(in) m1, integer, intent(in) ntau)
The Green function on a given time slice reads G(tau) = (1 + B(tau) B(tau-1,0) B(beta,tau))^(-1) with B(tau) = U_n e^(d_n) U_n^(dag) .... U_1 e^(V_1) U_1^(dag) e^(-dtau H_t) On input you have G(tau,m) = [ 1 + U_m e^(d_m) U_m^(dag) U_m^(dag) ... U_1 e^(V_1) U_1^(dag) e^(-dtau H_t) B(tau-1,0) B(Beta,tau) U_n e^(d_n) U_n^(dag) ...U_(m+1) e^(d_(m+1)) U_(m+1)^(dag) U_(m+1) ] On output you have G(tau, m1)
Parameters
[in,out] gr Note that m,m1 in [0,n]
Definition at line 279 of file Wrapgr_mod.f90.
References hamiltonian::n_fl, hamiltonian::ndim, hamiltonian::nsigma, hamiltonian::op_v, operator_mod::op_wrapdo(), and operator_mod::op_wrapup().
Referenced by wrapgr_random_update(), wrapgr_test(), wrapgrdo(), and wrapgrup().
 !--------------------------------------------------------------------
 !
 !--------------------------------------------------------------------
     Implicit none
     !Arguments
     COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:), INTENT(INOUT), allocatable :: GR
     Integer, INTENT(IN) :: m,m1, ntau
     !Local
     Integer :: n, nf, N_Type,  X
 !     Real (Kind=Kind(0.d0)) ::
     If (m == m1)  then
        return
     elseif  ( m1 > m  ) then
        !Write(6,*) "Wrapup from ",  m + 1, "to",  m1, " on tau=",  ntau
        Do n = m+1,m1
           Do nf = 1, n_fl
              x = nsigma(n,ntau)!Phi(nsigma(n,ntau),Op_V(n,nf)%type)
              n_type = 1
              Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
           enddo
           do nf = 1,n_fl
              n_type =  2
              Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
           enddo
        Enddo
     elseif  (m1 < m ) then
        !Write(6,*) "Wrapdo from ",  m, "to",  m1 + 1
        Do n =  m, m1+1 ,-1
           n_type = 2
           nf = 1
           x = nsigma(n,ntau)!Phi(nsigma(n,ntau),Op_V(n,nf)%type)
           do nf = 1,n_fl
              Call op_wrapdo( gr(:,:,nf), op_v(n,nf), x, ndim, n_type)
           enddo
           !Write(6,*) 'Upgrade : ', ntau,n
           nf = 1
           x = nsigma(n,ntau)!Phi(nsigma(n,ntau),Op_V(n,nf)%type)
           n_type = 1
           do nf = 1,n_fl
              Call op_wrapdo( gr(:,:,nf), op_v(n,nf), x, ndim, n_type )
           enddo
        enddo
     endif
wrapgr_random_update()
subroutine wrapgr_mod::wrapgr_random_update (complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, integer, intent(inout) m, integer, intent(in) ntau, complex (kind=kind(0.d0)), intent(inout) PHASE, integer, intent(in) N_Global_tau)
Author
ALF-project
On input: GR(tau,m) as defined in Global_tau_mod_PlaceGR and the direction of updating scheme direction=u –> You are visiting the time slices from tau = 1 to tau =Ltrot direction=d –> You are visiting the time slices from tau = Ltrot to tau = 1
The routine calls
Global_move_tau(T0_Proposal_ratio, Flip_list, Flip_length,ntau,m,direction) in the Hamiltonian module and then carries out the update
On output
Flip_length==1
Green function is on GR(tau,Flip_list(1) +1) if direction = u Green function is on GR(tau,Flip_list(1) -1) if direction = d This is valid if the move has or has not been accepted.
Flip_length > 1 Let m_min = min(Flip_list), m_max = max(Flip_list) direction = u –> On output Green on m_max is accepted. Green is on m_min if not accepted. direction = d –> On output Green on m_min if accepted. Green is on m_max if not accepted.
Definition at line 345 of file Wrapgr_mod.f90.
References hamiltonian::global_move_tau(), gr_st, hamiltonian::n_fl, hamiltonian::ndim, hamiltonian::nsigma, hamiltonian::op_v, operator_mod::op_wrapup(), upgrade2(), wrapgr_placegr(), and wrapgr_sort().
Referenced by wrapgrdo(), wrapgrup(), and wrapgrup().
 !--------------------------------------------------------------------
 !
 !--------------------------------------------------------------------
     Implicit none
     Interface
        Subroutine upgrade2(GR,N_op,NT,PHASE,Op_dim,ns_new, Prev_Ratiotot,S0_ratio, T0_Proposal_ratio, Acc, Mode)
          Use hamiltonian
          Use random_wrap
          Use control
          Implicit none
          Complex (Kind=Kind(0.d0)) :: GR(Ndim,Ndim, N_FL)
          Complex (Kind=Kind(0.d0)) :: Prev_Ratiotot
          Integer, INTENT(IN)       :: N_op, Nt, Op_dim
          Complex (Kind=Kind(0.d0)) :: Phase
          Integer                   :: ns_new
          Real    (Kind=Kind(0.d0)) :: S0_ratio, T0_Proposal_ratio
          Logical                   :: Acc
          Character (Len=64)        :: Mode
        end Subroutine upgrade2
     end Interface
     ! Arguments
     COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:), INTENT(INOUT), allocatable :: GR
     Integer,           INTENT(INOUT) :: m
     Integer,           INTENT(IN)    :: ntau, N_Global_tau
     Complex  (Kind=Kind(0.d0)), INTENT(INOUT) :: PHASE
     ! Space for local variables
     Integer                   :: n, Flip_length, nf, N_Type, ng_c, Flip_count, X
     Real    (Kind=Kind(0.d0)) :: T0_Proposal_ratio, T0_proposal,S0_ratio
     COMPLEX (Kind=Kind(0.d0)) :: Prev_Ratiotot
     Logical                   :: Acc
     Character (Len=64)        :: Mode
     Integer,      allocatable :: Flip_list(:), Flip_value(:), Flip_value_st(:)
     Real    (Kind=Kind(0.d0)) :: Zero = 10d-8
     Allocate ( flip_list(Size(op_v,1)), flip_value(Size(op_v,1)), flip_value_st(Size(op_v,1)) )
     Do ng_c = 1,n_global_tau
        ! New configuration
        Call global_move_tau(t0_proposal_ratio, s0_ratio,  flip_list, flip_length,flip_value,ntau )
        !Write(6,*)  "Calling global move",  m, Flip_list(1), nsigma(Flip_list(1),ntau),Flip_value(1)
        If ( t0_proposal_ratio  >  zero )  Then
           ! Order the list
           Call wrapgr_sort(flip_length,flip_list,flip_value)
           If ( flip_length > 1 ) then
              Do flip_count = 1, flip_length-1
                 flip_value_st(flip_count)  = nsigma( flip_list(flip_count), ntau  )
              Enddo
           endif
           prev_ratiotot = cmplx(1.d0,0.d0,kind(0.d0))
           !Write(6,*) "-----", Flip_length
           do flip_count = 1,flip_length
              n = flip_list(flip_count)
              !Write(6,*)  "PlaceGR",  m, n-1,ntau
              Call wrapgr_placegr(gr,m, n-1, ntau)
              !Write(6,*)  "Back from PlaceGR",  m, n-1,ntau
              If ( flip_count == 1 .and. flip_length > 1 ) gr_st = gr
              Do nf = 1, n_fl
                 x = nsigma(n,ntau)!Phi(nsigma(n,ntau),Op_V(n,nf)%type)
                 n_type = 1
                 Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
              enddo
              nf = 1
              If (flip_count <  flip_length)  then
                 mode = "Intermediate"
                 Call upgrade2(gr,n,ntau,phase,op_v(n,nf)%N_non_Zero,flip_value(flip_count), &
                      &        prev_ratiotot, s0_ratio, t0_proposal_ratio, acc, mode )
                 do nf = 1,n_fl
                    n_type =  2
                    Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
                 enddo
              else
                 !Write(6,*)  "Call Up mode final", n,ntau
                 mode = "Final"
                 Call upgrade2(gr,n,ntau,phase,op_v(n,nf)%N_non_Zero,flip_value(flip_count), &
                      &        prev_ratiotot, s0_ratio, t0_proposal_ratio, acc, mode )
                 !Write(6,*)  "Back from up mode final", n,ntau
                 !Write(6,*)  "Acceptance", Acc
                 do nf = 1,n_fl
                    n_type =  2
                    Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
                 enddo
              endif
              m = n
           enddo
           If ( .not. acc .and. flip_length > 1 ) then
              gr = gr_st
              m = flip_list(1) - 1
              Do flip_count = 1, flip_length-1
                 nsigma( flip_list(flip_count), ntau  ) = flip_value_st(flip_count)
              Enddo
           Endif
           !If (Acc) Call Hamiltonian_Print(Ntau)
        endif
     Enddo
     Deallocate ( flip_list, flip_value, flip_value_st )
wrapgr_sort()
subroutine wrapgr_mod::wrapgr_sort (integer, intent(in) Flip_length, integer, dimension(:), intent(inout), allocatable Flip_list, integer, dimension(:), intent(inout), allocatable Flip_value)
Definition at line 476 of file Wrapgr_mod.f90.
Referenced by wrapgr_random_update().
     ! Arguments
     Integer, INTENT(IN) :: Flip_length
     Integer, INTENT(INOUT), allocatable :: Flip_list(:), Flip_value(:)
     ! Local
     integer :: swaps            ! number of swaps made in one pass
     integer :: nc               ! loop variable
     integer :: temp             ! temporary holder for making swap
     if ( flip_length == 1 ) return
     !Write(6,*) 'Before sort'
     !DO nc = 1,Flip_length
     !   Write(6,*) Flip_list(nc),  Flip_value(nc)
     !Enddo
     do
        swaps      = 0           ! Initially, we've made no swaps
        do nc = 1, (flip_length - 1)
           if ( flip_list(nc)  >  flip_list(nc+1) ) then
              temp              = flip_list(nc  )
              flip_list(nc)     = flip_list(nc+1)
              flip_list(nc+1)   = temp
              temp              = flip_value(nc  )
              flip_value(nc)    = flip_value(nc+1)
              flip_value(nc+1)  = temp
              swaps             = swaps + 1
           end if
        end do
        if ( swaps == 0 ) exit ! do count swaps
     end do
     !Write(6,*) 'After sort'
     !DO nc = 1,Flip_length
     !   Write(6,*) Flip_list(nc),  Flip_value(nc)
     !Enddo
wrapgr_test()
subroutine wrapgr_mod::wrapgr_test (complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable Gr, integer ntau)
Definition at line 518 of file Wrapgr_mod.f90.
References gr_st, hamiltonian::n_fl, nranf(), hamiltonian::op_v, and wrapgr_placegr().
     ! Arguments
     COMPLEX (Kind=Kind(0.d0)), Dimension(:,:,:), INTENT(INOUT), allocatable :: GR
     Integer :: ntau
     ! Local
     Integer :: m, m1, N_size, nf, nth
     Real (Kind=kind(0.d0)) :: Xmean, Xmax
     !Input is the Green function on time slice tau
     n_size = size(op_v,1)
     gr_st = gr
     m = n_size
     m1 = 0
     DO nth = 1,10
        call wrapgr_placegr(gr,m,m1,ntau)
        Write(6,*) m, m1
        m = m1
        m1 =  nranf(n_size)-1
     enddo
     call wrapgr_placegr(gr,m,n_size,ntau)
     Write(6,*) m, n_size
     xmax = 0.d0
     Do nf = 1,n_fl
        Call compare(gr_st(:,:,nf),gr(:,:,nf),xmax,xmean)
     Enddo
     Write(6,*)  'Compare Global_tau_mod_Test ', xmax
     Deallocate ( gr_st )
wrapgrdo()
subroutine wrapgr_mod::wrapgrdo (complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, integer, intent(in) NTAU, complex (kind=kind(0.d0)), intent(inout) PHASE, logical, intent(in) Propose_S0, integer, intent(in) Nt_sequential_start, integer, intent(in) Nt_sequential_end, integer, intent(in) N_Global_tau)
Author
ALF-project
Given the green function matrix GR at time NTAU the routine carries out an update of the fields at time NTAU and propagates it to time NTAU-1 NTAU: [LTROT:1]
Definition at line 174 of file Wrapgr_mod.f90.
References control::control_upgrade_eff(), hop_mod::hop_mod_mmthl(), hop_mod::hop_mod_mmthr_m1(), hamiltonian::n_fl, hamiltonian::ndim, operator_mod::nflipl, nranf(), hamiltonian::nsigma, hamiltonian::op_v, operator_mod::op_wrapdo(), hamiltonian::s0(), upgrade2(), wrapgr_placegr(), and wrapgr_random_update().
Referenced by main().
 !--------------------------------------------------------------------
 !
 !
 !--------------------------------------------------------------------
     Use hamiltonian
     Use mymats
     Use hop_mod
     Implicit None
     Interface
        Subroutine upgrade2(GR,N_op,NT,PHASE,Op_dim,ns_new, Prev_Ratiotot, S0_ratio, T0_proposal_ratio, Acc, mode)
          Use hamiltonian
          Use random_wrap
          Use control
          Implicit none
          Complex (Kind=Kind(0.d0)) :: GR(Ndim,Ndim, N_FL)
          Complex (Kind=Kind(0.d0)) :: Prev_Ratiotot
          Integer, INTENT(IN)       :: N_op, Nt, Op_dim
          Complex (Kind=Kind(0.d0)) :: Phase
          Integer                   :: ns_new
          Real    (Kind=Kind(0.d0)) :: S0_ratio, T0_Proposal_ratio
          Character (Len=64)        :: Mode
          Logical                   :: Acc
        end Subroutine upgrade2
     End Interface
     ! Given GREEN at time NTAU => GREEN at time NTAU - 1,
     ! Upgrade NTAU  [LTROT:1]
     COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), allocatable :: GR(:,:,:)
     COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT) :: PHASE
     Integer, INTENT(IN) :: NTAU
     LOGICAL, INTENT(IN) :: Propose_S0
     INTEGER, INTENT(IN) :: Nt_sequential_start, Nt_sequential_end, N_Global_tau
     ! Local
     Integer :: nf, N_Type, n, spin, m, Flip_value(1)
     Complex (Kind=Kind(0.d0)) :: Prev_Ratiotot
     Real    (Kind=Kind(0.d0)) :: T0_proposal,  T0_Proposal_ratio,  S0_ratio
     Character (Len=64)        :: Mode
     Logical                   :: Acc, toggle1
     If ( n_global_tau > 0 ) then
        m         = Size(op_v,1)
        !Write(6,*) 'Call Ran_up ', m,ntau
        Call wrapgr_random_update(gr,m,ntau, phase, n_global_tau )
        Call wrapgr_placegr(gr,m, nt_sequential_end, ntau)
     Endif
     Do n =  nt_sequential_end, nt_sequential_start, -1
        n_type = 2
        nf = 1
        spin = nsigma(n,ntau)!Phi(nsigma(n,ntau),Op_V(n,nf)%type)
        do nf = 1,n_fl
           Call op_wrapdo( gr(:,:,nf), op_v(n,nf), spin, ndim, n_type)
        enddo
        !Write(6,*) 'Upgrade : ', ntau,n
        nf = 1
        t0_proposal       = 1.5d0
        t0_proposal_ratio = 1.d0
        s0_ratio          = s0(n,ntau)
        if ( propose_s0 ) then
           If ( op_v(n,nf)%type == 1)  then
              t0_proposal       = 1.d0 - 1.d0/(1.d0+s0_ratio)
              t0_proposal_ratio = 1.d0/s0_ratio
           endif
        Endif
        If ( t0_proposal > ranf_wrap() ) Then
           if  (op_v(n,nf)%type == 1 ) flip_value(1)  = -nsigma(n,ntau)
           if  (op_v(n,nf)%type == 2 ) flip_value(1)  =  nflipl(nsigma(n,ntau),nranf(3))
           mode = "Final"
           prev_ratiotot = cmplx(1.d0,0.d0,kind(0.d0))
           Call upgrade2(gr,n,ntau,phase,op_v(n,nf)%N_non_Zero,flip_value(1), prev_ratiotot, s0_ratio,t0_proposal_ratio, acc, mode )
        else
           toggle1 = .false.
           Call control_upgrade_eff(toggle1)
        Endif
        !Call Upgrade(GR,n,ntau,PHASE,Op_V(n,1)%N_non_zero)
        ! The spin has changed after the upgrade!
        nf = 1
        spin = nsigma(n,ntau)!Phi(nsigma(n,ntau),Op_V(n,nf)%type)
        n_type = 1
        do nf = 1,n_fl
           Call op_wrapdo( gr(:,:,nf), op_v(n,nf), spin, ndim, n_type )
        enddo
     enddo
     DO nf = 1,n_fl
        Call hop_mod_mmthl   (gr(:,:,nf), nf)
        Call hop_mod_mmthr_m1(gr(:,:,nf), nf)
     enddo
wrapgrup()
subroutine wrapgr_mod::wrapgrup (complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, integer, intent(in) NTAU, complex (kind=kind(0.d0)), intent(inout) PHASE, logical, intent(in) Propose_S0, integer, intent(in) Nt_sequential_start, integer, intent(in) Nt_sequential_end, integer, intent(in) N_Global_tau)
Author
ALF-project
Given the green function matrix GR at time NTAU the routine propagates it to time NTAU + 1 and carries out an update of the fields at time NTAU+1 NTAU: [0:LTROT-1]
Definition at line 77 of file Wrapgr_mod.f90.
References control::control_upgrade_eff(), hop_mod::hop_mod_mmthl_m1(), hop_mod::hop_mod_mmthr(), hamiltonian::n_fl, hamiltonian::ndim, operator_mod::nflipl, nranf(), hamiltonian::nsigma, hamiltonian::op_v, operator_mod::op_wrapup(), hamiltonian::s0(), upgrade2(), wrapgr_placegr(), and wrapgr_random_update().
Referenced by main().
 !--------------------------------------------------------------------
 !
 !
 !--------------------------------------------------------------------
     Use hamiltonian
     Use hop_mod
     Implicit none
     Interface
        Subroutine upgrade2(GR,N_op,NT,PHASE,Op_dim,ns_new, Prev_Ratiotot, S0_ratio, T0_proposal_ratio, Acc,mode)
          Use hamiltonian
          Use random_wrap
          Use control
          Implicit none
          Complex (Kind=Kind(0.d0)) :: GR(Ndim,Ndim, N_FL)
          Complex (Kind=Kind(0.d0)) :: Prev_Ratiotot
          Integer, INTENT(IN)       :: N_op, Nt, Op_dim
          Complex (Kind=Kind(0.d0)) :: Phase
          Integer                   :: ns_new
          Real    (Kind=Kind(0.d0)) :: S0_ratio, T0_Proposal_ratio
          Character (Len=64)        :: Mode
          Logical                   :: Acc
        end Subroutine upgrade2
     end Interface
     ! Arguments
     COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), allocatable ::  GR(:,:,:)
     COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT) ::  PHASE
     INTEGER, INTENT(IN) :: NTAU
     LOGICAL, INTENT(IN) :: Propose_S0
     INTEGER, INTENT(IN) :: Nt_sequential_start, Nt_sequential_end, N_Global_tau
     !Local
     Integer :: nf, N_Type, NTAU1,X,n, m, Flip_value(1)
     Complex (Kind=Kind(0.d0)) :: Prev_Ratiotot
     Real    (Kind=Kind(0.d0)) :: T0_proposal,  T0_Proposal_ratio,  S0_ratio
     Character (Len=64)        :: Mode
     Logical                   :: Acc, toggle1
     ! Wrap up, upgrade ntau1.  with B^{1}(tau1)
     ntau1 = ntau + 1
     Do nf = 1,n_fl
        CALL hop_mod_mmthr   (gr(:,:,nf), nf )
        CALL hop_mod_mmthl_m1(gr(:,:,nf), nf )
     Enddo
     Do n = nt_sequential_start,nt_sequential_end
        Do nf = 1, n_fl
           x = nsigma(n,ntau1)!Phi(nsigma(n,ntau1),Op_V(n,nf)%type)
           n_type = 1
           Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
        enddo
        nf = 1
        t0_proposal       = 1.5d0
        t0_proposal_ratio = 1.d0
        s0_ratio          = s0(n,ntau1)
        if ( propose_s0 ) then
           If ( op_v(n,nf)%type == 1)  then
              t0_proposal       = 1.d0 - 1.d0/(1.d0+s0_ratio)
              t0_proposal_ratio = 1.d0/s0_ratio
           endif
        Endif
        If ( t0_proposal > ranf_wrap() ) Then
           if  (op_v(n,nf)%type == 1 ) flip_value(1)  = -nsigma(n,ntau1)
           if  (op_v(n,nf)%type == 2 ) flip_value(1)  =  nflipl(nsigma(n,ntau1),nranf(3))
           mode = "Final"
           !Write(6,*) 'Hi', n, Op_V(n,nf)%type, T0_Proposal_ratio, S0_ratio
           prev_ratiotot = cmplx(1.d0,0.d0,kind(0.d0))
           Call upgrade2(gr,n,ntau1,phase,op_v(n,nf)%N_non_Zero,flip_value(1), prev_ratiotot, s0_ratio,t0_proposal_ratio, acc, mode )
        else
           toggle1 = .false.
           Call control_upgrade_eff(toggle1)
        Endif
        do nf = 1,n_fl
           n_type =  2
           Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
        enddo
     Enddo
     If ( n_global_tau > 0 ) then
        m         = nt_sequential_end
        !if ( Nt_sequential_start >  Nt_sequential_end ) m = Nt_sequential_start
        Call wrapgr_random_update(gr,m,ntau1, phase, n_global_tau )
        Call wrapgr_placegr(gr,m, Size(op_v,1), ntau1)
     Endif
Variable Documentation
gr_st
complex (kind=kind(0.d0)), dimension(:,:,:), allocatable, private wrapgr_mod::gr_st private
Privat.
Definition at line 55 of file Wrapgr_mod.f90.
Referenced by wrapgr_alloc(), wrapgr_dealloc(), wrapgr_random_update(), and wrapgr_test().
   Complex (Kind=Kind(0.d0)),  private, allocatable ::  GR_ST(:,:,:)