ALF: predefined_structures Module Reference
predefined_structures Module Reference
This module provides a set of predefined lattices, hoppings, interactions, trial wave functions as well as observables.
Functions/Subroutines
subroutine predefined_latt (Lattice_type, L1, L2, Norb, N_coord, Ndim, List, Invlist, Latt)
Definition of a set of lattices: Square, One_dimensional, Honeycomb, Pi_Flux.
subroutine predefined_hopping (Lattice_type, Norb, N_coord, Ndim, List, Invlist, Latt, Dtau, Ham_T, Ham_Chem, XB_X, XB_Y, Phi_X, Phi_Y, N_FL, Checkerboard, Symm, OP_T)
Hopping, with ot without checkerboard
Per flavor, the hopping is given by
If Symm is set to true and if Checkeborad is on, then one will carry out a symmetric decomposition so as to preserve the hermitian properties of the hopping. Thereby OP_T has dimension OP_T(N,N_FL)
subroutine predefined_trialwavefunction (Lattice_type, Norb, N_coord, Ndim, List, Invlist, Latt, N_part, N_FL, Degen, WF_L, WF_R)
Sets the trial wave function corresponding to the solution of the non-interacting tight binding Hamiltonian on the given lattice. Twisted boundary conditions (Phi_X=0.01) are implemented so as to generate a non-degenerate trial wave functions.
Detailed Description
This module provides a set of predefined lattices, hoppings, interactions, trial wave functions as well as observables.
Author
ALF-project
Function/Subroutine Documentation
predefined_hopping()
subroutine predefined_structures::predefined_hopping (character (len=64), intent(in) Lattice_type, integer, intent(in) Norb, integer, intent(in) N_coord, integer, intent(in) Ndim, integer, dimension(:,:), intent(in) List, integer, dimension(:,:), intent(in) Invlist, type(lattice), intent(in) Latt, real (kind=kind(0.d0)), intent(in) Dtau, real (kind=kind(0.d0)), intent(in) Ham_T, real (kind=kind(0.d0)), intent(in) Ham_Chem, real (kind=kind(0.d0)), intent(in) XB_X, real (kind=kind(0.d0)), intent(in) XB_Y, real (kind=kind(0.d0)), intent(in) Phi_X, real (kind=kind(0.d0)), intent(in) Phi_Y, integer, intent(in) N_FL, logical Checkerboard, logical Symm, type(operator), dimension(:,:), intent(out), allocatable OP_T)
Hopping, with ot without checkerboard
Per flavor, the hopping is given by
If Symm is set to true and if Checkeborad is on, then one will carry out a symmetric decomposition so as to preserve the hermitian properties of the hopping. Thereby OP_T has dimension OP_T(N,N_FL)
Author
ALF-project
Parameters
[in] Latttice_type Character(64)
     Square, One_dimensional, Honeycomb, Pi_Flux
[in] Norb Integer
     Number of orbitals per unit cell
[in] N_coord Integer
     Coordination number
[in] Ndim Integer
     Number of orbitals
[in] List,Invlist Integer(:,:)
      List(I=1.. Ndim,1)    =   Unit cell of site I
      List(I=1.. Ndim,2)    =   Orbital index  of site I
      Invlist(Unit_cell,Orbital) = site I
[in] Latt Type(Lattice)
      The Lattice
[in] Dtau Real
      Imaginary time step
[in] Ham_T Real
      Hopping matrix element
[in] Ham_Chem Real
      Chemical potential
[in] XB_X,YB_Y Real
      X, Y  Boundary conditions
[in] Phi_X,Phi_Y Real
      X, Y  Fluxes
[in] N_FL Integer
      Flavors
[in] Checkerboard Logical
      Allows for checkerboard decomposition
[in] Symm Logical
      Allows for symmetric checkerboard decomposition
[out] OP_T Type(operator)(N,N_FL)
      Hopping
Definition at line 282 of file Predefined_structures.f90.
References operator_mod::op_make(), and operator_mod::op_set().
Referenced by hamiltonian::ham_set(), and predefined_trialwavefunction().
         Implicit none
         Character (len=64), Intent(IN)           :: Lattice_type
         Integer, Intent(IN)                      :: Norb,N_coord, Ndim, N_FL
         Integer, Intent(IN), Dimension(:,:)      :: List, Invlist
         Type(Lattice), Intent(in)                :: Latt
         Real (Kind=Kind(0.d0)), Intent(In)       :: Dtau, Ham_T, Ham_Chem, XB_X, XB_Y, Phi_X, Phi_Y
         Logical                                  :: Checkerboard, Symm
         Type(Operator), Intent(Out),  dimension(:,:), allocatable  :: Op_T
         !Local
         Integer :: I, I1, J1, I2, n, Ncheck,nc, nc1, no, N_Fam, L_FAM
         Complex (Kind=Kind(0.d0)) :: ZX, ZY
         Real    (Kind=Kind(0.d0)) :: del_p(2), X, g
         If ( .not. checkerboard) then
            allocate(op_t(1,n_fl))
            do n = 1,n_fl
               Call op_make(op_t(1,n),ndim)
               nc = 1
               Select case (lattice_type)
               Case ("Square")
                  zx  =  exp( cmplx(0.d0, 2.d0 * acos(-1.d0)*phi_x/xnorm(latt%L1_p), kind=kind(0.d0) ) )
                  zy  =  exp( cmplx(0.d0, 2.d0 * acos(-1.d0)*phi_y/xnorm(latt%L2_p), kind=kind(0.d0) ) )
                  DO i = 1, latt%N
                     i1 = latt%nnlist(i,1,0)
                     i2 = latt%nnlist(i,0,1)
                     If ( latt%list(i,1) == 0 ) then
                        op_t(nc,n)%O(i,i1) = cmplx(-ham_t*xb_x, 0.d0, kind(0.d0))*zx
                        op_t(nc,n)%O(i1,i) = cmplx(-ham_t*xb_x, 0.d0, kind(0.d0))*conjg(zx)
                     else
                        op_t(nc,n)%O(i,i1) = cmplx(-ham_t, 0.d0, kind(0.d0))*zx
                        op_t(nc,n)%O(i1,i) = cmplx(-ham_t, 0.d0, kind(0.d0))*conjg(zx)
                     endif
                     If ( latt%list(i,2) == 0 ) then
                        op_t(nc,n)%O(i,i2) = cmplx(-ham_t*xb_y,    0.d0, kind(0.d0))*zy
                        op_t(nc,n)%O(i2,i) = cmplx(-ham_t*xb_y,    0.d0, kind(0.d0))*conjg(zy)
                     else
                        op_t(nc,n)%O(i,i2) = cmplx(-ham_t     ,    0.d0, kind(0.d0))*zy
                        op_t(nc,n)%O(i2,i) = cmplx(-ham_t     ,    0.d0, kind(0.d0))*conjg(zy)
                     endif
                     op_t(nc,n)%O(i ,i) = cmplx(-ham_chem, 0.d0, kind(0.d0))
                  Enddo
               Case ("One_dimensional")
                  zx  =  exp( cmplx(0.d0, 2.d0 * acos(-1.d0)*phi_x/xnorm(latt%L1_p), kind=kind(0.d0) ) )
                  DO i = 1, latt%N
                     i1 = latt%nnlist(i,1,0)
                     If ( latt%list(i,1) == 0 ) then
                        op_t(nc,n)%O(i,i1) = cmplx(-ham_t*xb_x, 0.d0, kind(0.d0))*zx
                        op_t(nc,n)%O(i1,i) = cmplx(-ham_t*xb_x, 0.d0, kind(0.d0))*conjg(zx)
                     else
                        op_t(nc,n)%O(i,i1) = cmplx(-ham_t, 0.d0, kind(0.d0))*zx
                        op_t(nc,n)%O(i1,i) = cmplx(-ham_t, 0.d0, kind(0.d0))*conjg(zx)
                     endif
                     op_t(nc,n)%O(i ,i) = cmplx(-ham_chem, 0.d0, kind(0.d0))
                  Enddo
               Case ("Honeycomb")
                  x = 2.d0 * acos(-1.d0)*phi_x / ( xnorm(latt%L1_p) * (xnorm(latt%a1_p)**2)  )
                  DO i = 1, latt%N
                     do no = 1,norb
                        i1 = invlist(i,no)
                        op_t(nc,n)%O(i1 ,i1) = cmplx(-ham_chem, 0.d0, kind(0.d0))
                     enddo
                     i1 = invlist(i,1)
                     j1 = i1
                     Do nc1 = 1,n_coord
                        select case (nc1)
                        case (1)
                           j1 = invlist(i,2)
                           del_p   =  (latt%a2_p - 0.5d0*latt%a1_p) * 2.d0/3.d0
                        case (2)
                           j1 = invlist(latt%nnlist(i,1,-1),2)
                           del_p   =  latt%a1_p - latt%a2_p + (latt%a2_p - 0.5d0*latt%a1_p) * 2.d0/3.d0
                        case (3)
                           j1 = invlist(latt%nnlist(i,0,-1),2)
                           del_p   =  - latt%a2_p + (latt%a2_p - 0.5d0*latt%a1_p) * 2.d0/3.d0
                        case default
                           Write(6,*) ' Error in  Ham_Hop '
                           stop
                        end select
                        zx = exp( cmplx(0.d0, x*iscalar(latt%a1_p,del_p), kind(0.d0) ) )
                        op_t(nc,n)%O(i1,j1) = cmplx(-ham_t,    0.d0, kind(0.d0)) * zx
                        op_t(nc,n)%O(j1,i1) = cmplx(-ham_t,    0.d0, kind(0.d0)) * conjg(zx)
                     Enddo
                  Enddo
               case("Pi_Flux")
                  DO i = 1, latt%N
                     do no = 1,norb
                        i1 = invlist(i,no)
                        op_t(nc,n)%O(i1 ,i1) = cmplx(-ham_chem, 0.d0, kind(0.d0))
                     enddo
                     i1 = invlist(i,1)
                     j1 = i1
                     Do nc1 = 1,n_coord
                        select case (nc1)
                        case (1)
                           j1 = invlist(i,2)
                        case (2)
                           j1 = invlist(latt%nnlist(i,0, 1),2)
                        case (3)
                           j1 = invlist(latt%nnlist(i,-1,1),2)
                        case (4)
                           j1 = invlist(latt%nnlist(i,-1,0),2)
                        case default
                           Write(6,*) ' Error in  Ham_Hop '
                           stop
                        end select
                        if (nc1 == 1 ) then
                           op_t(nc,n)%O(i1,j1) = cmplx( ham_t,    0.d0, kind(0.d0))
                           op_t(nc,n)%O(j1,i1) = cmplx( ham_t,    0.d0, kind(0.d0))
                        Else
                           op_t(nc,n)%O(i1,j1) = cmplx(-ham_t,    0.d0, kind(0.d0))
                           op_t(nc,n)%O(j1,i1) = cmplx(-ham_t,    0.d0, kind(0.d0))
                        endif
                     Enddo
                  Enddo
               case default
                  Write(6,*) "Lattice not yet implemented!"
                  stop
               end select
               Do i = 1,ndim
                  op_t(nc,n)%P(i) = i
               Enddo
               if ( abs(ham_t) < 1.e-6  .and.  abs(ham_chem) < 1.e-6 ) then
                  op_t(nc,n)%g = 0.d0
               else
                  op_t(nc,n)%g = -dtau
               endif
               op_t(nc,n)%alpha=cmplx(0.d0,0.d0, kind(0.d0))
               Call op_set(op_t(nc,n))
               !Do I = 1,Size(Op_T(nc,n)%E,1)
               !   Write(6,*) Op_T(nc,n)%E(I)
               !Enddo
            Enddo
         else
            select case (lattice_type)
            case ("Square")
               If (symm) then
                  n_fam = 2*(2*n_coord) -1  !  Number of Families = 4
                  l_fam = latt%N/2          !  Length of Families = LQ/4
                  Allocate(op_t(n_fam*l_fam,n_fl))
                  do n = 1,n_fl
                     do i  =  1, n_fam*l_fam
                        call op_make(op_t(i,n),2)
                     enddo
                     nc = 0
                     do nc1 = 1,n_fam
                        do i = 1,latt%N
                           if ( mod(latt%List(i,1) + latt%List(i,2),2) == 0 ) then
                              i1 = i
                              nc = nc + 1
                              select case (nc1)
                              case(1)
                                 i2 = latt%nnlist(i1, 1, 0)
                                 g = -dtau/2.d0
                              case(2)
                                 i2 = latt%nnlist(i1, 0, 1)
                                 g = -dtau/2.d0
                              case(3)
                                 i2 = latt%nnlist(i1,-1, 0)
                                 g = -dtau/2.d0
                              case(4)
                                 i2 = latt%nnlist(i1, 0,-1)
                                 g = -dtau
                              case(5)
                                 i2 = latt%nnlist(i1,-1, 0)
                                 g = -dtau/2.d0
                              case(6)
                                 i2 = latt%nnlist(i1, 0, 1)
                                 g = -dtau/2.d0
                              case(7)
                                 i2 = latt%nnlist(i1, 1, 0)
                                 g = -dtau/2.d0
                              end select
                              !Write(6,*) nc,nc1, Latt%List(I1,1), Latt%List(I1,2),Latt%List(I2,1), Latt%List(I2,2), I1, I2
                              op_t(nc,n)%P(1) = i1
                              op_t(nc,n)%P(2) = i2
                              op_t(nc,n)%O(1,2) = cmplx(-ham_t ,0.d0, kind(0.d0))
                              op_t(nc,n)%O(2,1) = cmplx(-ham_t ,0.d0, kind(0.d0))
                              op_t(nc,n)%O(1,1) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                              op_t(nc,n)%O(2,2) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                              if ( abs(ham_t) < 1.e-6  .and.  abs(ham_chem) < 1.e-6 ) then
                                 op_t(nc,n)%g = 0.d0
                              else
                                 op_t(nc,n)%g = g
                              endif
                              op_t(nc,n)%alpha  = cmplx( 0.d0, 0.d0, kind(0.d0) )
                              Call op_set( op_t(nc,n) )
                           endif
                        Enddo
                     Enddo
                  Enddo
               Else
                  n_fam = 2*n_coord !  Number of Families = 4
                  l_fam = latt%N/2  !  Length of Families = LQ/4
                  Allocate(op_t(n_fam*l_fam,n_fl))
                  do n = 1,n_fl
                     do i  =  1, n_fam*l_fam
                        call op_make(op_t(i,n),2)
                     enddo
                     nc = 0
                     do nc1 = 1,n_fam
                        do i = 1,latt%N
                           if ( mod(latt%List(i,1) + latt%List(i,2),2) == 0 ) then
                              i1 = i
                              nc = nc + 1
                              if (nc1 == 1 ) i2 = latt%nnlist(i1, 1, 0)
                              if (nc1 == 2 ) i2 = latt%nnlist(i1, 0, 1)
                              if (nc1 == 3 ) i2 = latt%nnlist(i1,-1, 0)
                              if (nc1 == 4 ) i2 = latt%nnlist(i1, 0,-1)
                              !Write(6,*) nc,nc1, Latt%List(I1,1), Latt%List(I1,2),Latt%List(I2,1), Latt%List(I2,2), I1, I2
                              op_t(nc,n)%P(1) = i1
                              op_t(nc,n)%P(2) = i2
                              op_t(nc,n)%O(1,2) = cmplx(-ham_t ,0.d0, kind(0.d0))
                              op_t(nc,n)%O(2,1) = cmplx(-ham_t ,0.d0, kind(0.d0))
                              op_t(nc,n)%O(1,1) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                              op_t(nc,n)%O(2,2) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                              if ( abs(ham_t) < 1.e-6  .and.  abs(ham_chem) < 1.e-6 ) then
                                 op_t(nc,n)%g = 0.d0
                              else
                                 op_t(nc,n)%g = -dtau
                              endif
                              op_t(nc,n)%alpha  = cmplx( 0.d0, 0.d0, kind(0.d0) )
                              Call op_set( op_t(nc,n) )
                           endif
                        Enddo
                     Enddo
                  Enddo
               Endif
            case ("Pi_Flux")
               If (symm) Then
                  Write(6,*) 'Pi-Flux Symm is not yet implemented'
                  stop
               else
                  Allocate(op_t(n_coord*latt%N,n_fl))
                  do n = 1,n_fl
                     !Write(6,*) 'N_coord, Latt%N ',  N_coord, Latt%N
                     do i  =  1, n_coord*latt%N
                        call op_make(op_t(i,n),2)
                     enddo
                     nc = 0
                     do nc1 = 1,n_coord
                        do i = 1,latt%N
                           i1 = invlist(i,1)
                           nc = nc + 1
                           If (nc1 == 1 )  i2 = invlist(i,2)
                           If (nc1 == 2 )  i2 = invlist(latt%nnlist(i,0, 1),2)
                           If (nc1 == 3 )  i2 = invlist(latt%nnlist(i,-1,1),2)
                           If (nc1 == 4 )  i2 = invlist(latt%nnlist(i,-1,0),2)
                           op_t(nc,n)%P(1) = i1
                           op_t(nc,n)%P(2) = i2
                           if (nc1 == 1 ) then
                              op_t(nc,n)%O(1,2) = cmplx( ham_t,    0.d0, kind(0.d0))
                              op_t(nc,n)%O(2,1) = cmplx( ham_t,    0.d0, kind(0.d0))
                           Else
                              op_t(nc,n)%O(1,2) = cmplx(-ham_t,    0.d0, kind(0.d0))
                              op_t(nc,n)%O(2,1) = cmplx(-ham_t,    0.d0, kind(0.d0))
                           endif
                           op_t(nc,n)%O(1,1) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(2,2) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                           if ( abs(ham_t) < 1.e-6  .and.  abs(ham_chem) < 1.e-6 ) then
                              op_t(nc,n)%g = 0.d0
                           else
                              op_t(nc,n)%g = -dtau
                           endif
                           op_t(nc,n)%alpha  = cmplx( 0.d0, 0.d0, kind(0.d0) )
                           Call op_set( op_t(nc,n) )
                        Enddo
                     Enddo
                  Enddo
               Endif
            case ("Honeycomb")
               If (symm) then
                  Allocate(op_t((2*n_coord-1)*latt%N,n_fl))
                  do n = 1,n_fl
                     do i  =  1, (2*n_coord-1)*latt%N
                        call op_make(op_t(i,n),2)
                     enddo
                     nc = 0
                     do nc1 = 1,(2*n_coord -1)
                        do i = 1,latt%N
                           i1 = invlist(i,1)
                           nc = nc + 1
                           select case (nc1)
                           case(1)
                              i2 = invlist(i,2)
                              g = -dtau/2.d0
                           case(2)
                              i2 = invlist(latt%nnlist(i,1,-1),2)
                              g = -dtau/2.d0
                           case(3)
                              i2 = invlist(latt%nnlist(i,0,-1),2)
                              g = -dtau
                           case(4)
                              i2 = invlist(latt%nnlist(i,1,-1),2)
                              g = -dtau/2.d0
                           case(5)
                              i2 = invlist(i,2)
                              g = -dtau/2.d0
                           end select
                           op_t(nc,n)%P(1) = i1
                           op_t(nc,n)%P(2) = i2
                           op_t(nc,n)%O(1,2) = cmplx(-ham_t ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(2,1) = cmplx(-ham_t ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(1,1) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(2,2) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                           if ( abs(ham_t) < 1.e-6  .and.  abs(ham_chem) < 1.e-6 ) then
                              op_t(nc,n)%g = 0.d0
                           else
                              op_t(nc,n)%g = g
                           endif
                           op_t(nc,n)%alpha  = cmplx( 0.d0, 0.d0, kind(0.d0) )
                           Call op_set( op_t(nc,n) )
                        Enddo
                     Enddo
                  Enddo
               Else
                  Allocate(op_t(n_coord*latt%N,n_fl))
                  do n = 1,n_fl
                     do i  =  1, n_coord*latt%N
                        call op_make(op_t(i,n),2)
                     enddo
                     nc = 0
                     do nc1 = 1,n_coord
                        do i = 1,latt%N
                           i1 = invlist(i,1)
                           nc = nc + 1
                           if (nc1 == 1 ) i2 = invlist(i,2)
                           if (nc1 == 2 ) i2 = invlist(latt%nnlist(i,1,-1),2)
                           if (nc1 == 3 ) i2 = invlist(latt%nnlist(i,0,-1),2)
                           op_t(nc,n)%P(1) = i1
                           op_t(nc,n)%P(2) = i2
                           op_t(nc,n)%O(1,2) = cmplx(-ham_t ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(2,1) = cmplx(-ham_t ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(1,1) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                           op_t(nc,n)%O(2,2) = cmplx(-ham_chem/4.d0 ,0.d0, kind(0.d0))
                           if ( abs(ham_t) < 1.e-6  .and.  abs(ham_chem) < 1.e-6 ) then
                              op_t(nc,n)%g = 0.d0
                           else
                              op_t(nc,n)%g = -dtau
                           endif
                           op_t(nc,n)%alpha  = cmplx( 0.d0, 0.d0, kind(0.d0) )
                           Call op_set( op_t(nc,n) )
                        Enddo
                     Enddo
                  Enddo
               Endif
               case default
                  Write(6,*) "Checkeboard is not implemented for this lattice"
               stop
            End select
         endif
predefined_latt()
subroutine predefined_structures::predefined_latt (character (len=64), intent(in) Lattice_type, integer, intent(in) L1, integer, intent(in) L2, integer, intent(out) Norb, integer, intent(out) N_coord, integer, intent(out) Ndim, integer, dimension(:,:), intent(out), allocatable List, integer, dimension(:,:), intent(out), allocatable Invlist, type(lattice), intent(out) Latt)
Definition of a set of lattices: Square, One_dimensional, Honeycomb, Pi_Flux.
Author
ALF-project
Parameters
[in] Latttice_type
 Character(64)
 Can take the values
 Square, One_dimensional, Honeycomb, Pi_Flux
[in] L1,L2
    Integer
    Size of the lattice in units of the lattice constants
[out] Norb
    Integer
    Number of orbitals per unit cell
[out] N_coord
    Integer
    Coordination number
[out] Ndim
    Integer
    Number of orbitals
[out] List,Invlist
    Integer(:,:)
    List(I=1.. Ndim,1)    =   Unit cell of site I
    List(I=1.. Ndim,2)    =   Orbital index  of site I
    Invlist(1..Unit_cell,1..Orbital) = site I
[out] Latt
    Type(Lattice)
    Sets the lattice
Definition at line 101 of file Predefined_structures.f90.
Referenced by hamiltonian::ham_set().
         Implicit none
         !Set the lattice
         Character (len=64), Intent(IN)                     :: Lattice_type
         Integer, Intent(IN)                                :: L1,L2
         Integer, Intent(OUT)                               :: Norb,N_coord, Ndim
         Integer, Intent(OUT), Dimension(:,:), allocatable  :: List, Invlist
         Type(Lattice), Intent(Out)                         :: Latt
         Real (Kind=Kind(0.d0))  :: a1_p(2), a2_p(2), L1_p(2), L2_p(2)
         Integer :: I, nc, no
         select case (lattice_type)
         case("Square")
            If (l1==1 .or. l2==1 ) then
               Write(6,*) 'For one-dimensional lattices set : L2 = 1'
               stop
            endif
            norb      = 1
            n_coord   = 2
            a1_p(1) =  1.0  ; a1_p(2) =  0.d0
            a2_p(1) =  0.0  ; a2_p(2) =  1.d0
            l1_p    =  dble(l1)*a1_p
            l2_p    =  dble(l2)*a2_p
            Call make_lattice( l1_p, l2_p, a1_p,  a2_p, latt )
         case("One_dimensional")
            If (l1 == 1 ) then
               Write(6,*) ' For one dimensional systems set  L2 = 1 '
               stop
            endif
            norb      = 1
            n_coord   = 1
            a1_p(1) =  1.0  ; a1_p(2) =  0.d0
            a2_p(1) =  0.0  ; a2_p(2) =  1.d0
            l1_p    =  dble(l1)*a1_p
            l2_p    =  dble(l2)*a2_p
            Call make_lattice( l1_p, l2_p, a1_p,  a2_p, latt )
         case("Honeycomb")
              If (l1==1 .or. l2==1 ) then
                 Write(6,*) 'For one-dimensional lattices set : L2 = 1'
                 stop
              endif
              norb    = 2
              n_coord = 3
              a1_p(1) =  1.d0   ; a1_p(2) =  0.d0
              a2_p(1) =  0.5d0  ; a2_p(2) =  sqrt(3.d0)/2.d0
              !del_p   =  (a2_p - 0.5*a1_p ) * 2.0/3.0
              l1_p    =  dble(l1) * a1_p
              l2_p    =  dble(l2) * a2_p
              Call make_lattice( l1_p, l2_p, a1_p,  a2_p, latt )
           case("Pi_Flux")
              If (l1==1 .or. l2==1 ) then
                 Write(6,*) 'For one-dimensional lattices set : L2 = 1'
                 stop
              endif
              norb    = 2
              n_coord = 4
              a1_p(1) =  1.d0   ; a1_p(2) =   1.d0
              a2_p(1) =  1.d0   ; a2_p(2) =  -1.d0
              !del_p   =  (a2_p - 0.5*a1_p ) * 2.0/3.0
              l1_p    =  dble(l1) * (a1_p - a2_p)/2.d0
              l2_p    =  dble(l2) * (a1_p + a2_p)/2.d0
              Call make_lattice( l1_p, l2_p, a1_p,  a2_p, latt )
           case default
              Write(6,*) "Lattice not yet implemented!"
              stop
           end select
           ! Call Print_latt(Latt)
           ! This is for the orbital structure.
           ndim = latt%N*norb
           Allocate (list(ndim,2), invlist(latt%N,norb))
           nc = 0
           Do i = 1,latt%N
              Do no = 1,norb
                 ! For the Honeycomb and pi-flux lattices no = 1,2 corresponds to the A,and B sublattice.
                 nc = nc + 1
                 list(nc,1) = i
                 list(nc,2) = no
                 invlist(i,no) = nc
              Enddo
           Enddo
predefined_trialwavefunction()
subroutine predefined_structures::predefined_trialwavefunction (character (len=64), intent(in) Lattice_type, integer, intent(in) Norb, integer, intent(in) N_coord, integer, intent(in) Ndim, integer, dimension(:,:), intent(in) List, integer, dimension(:,:), intent(in) Invlist, type(lattice), intent(in) Latt, integer, intent(in) N_part, integer, intent(in) N_FL, real (kind=kind(0.d0)), intent(out) Degen, type(wavefunction), dimension(:), intent(out), allocatable WF_L, type(wavefunction), dimension(:), intent(out), allocatable WF_R)
Sets the trial wave function corresponding to the solution of the non-interacting tight binding Hamiltonian on the given lattice. Twisted boundary conditions (Phi_X=0.01) are implemented so as to generate a non-degenerate trial wave functions.
Author
ALF-project
Parameters
[in] Lattice_type Character(64)
    Square, One_dimensional, Honeycomb, Pi_Flux
[in] Norb Integer
    Number of orbitals per unit cell
[in] N_coord Integer
    Coordination number
[in] Ndim Integer
     Number of orbitals
[in] List,Invlist Integer(:,:)
    List(I=1.. Ndim,1)    =   Unit cell of site I
    List(I=1.. Ndim,2)    =   Orbital index  of site I
    Invlist(Unit_cell,Orbital) = site I
[in] Latt Type(Lattice)
    The Lattice
[in] N_part Integer
    Particle number for each flavor
[in] N_FL Integer
    Flavor
[out] Degen Real
    Degeneracy:  E(N_part + 1) - E(N_part). Energy eigenvalues are ordered in ascending order.
[out] WF_L,WF_R Type(Wavefunction)(N_FL)
    Wavefunction
Definition at line 704 of file Predefined_structures.f90.
References operator_mod::op_clear(), predefined_hopping(), and wavefunction_mod::wf_alloc().
Referenced by hamiltonian::ham_set().
         Implicit none
         Character (len=64), Intent(IN)                :: Lattice_type
         Integer, Intent(IN)                           :: Norb,N_coord, Ndim, N_FL, N_part
         Integer, Intent(IN), Dimension(:,:)           :: List, Invlist
         Type(Lattice), Intent(in)                     :: Latt
         Real (Kind=Kind(0.d0)), Intent(out)           :: Degen
         Type(WaveFunction), Intent(out), Dimension(:), allocatable :: WF_L, WF_R
         Type(Operator),  dimension(:,:), allocatable  :: OP_tmp
         Real (Kind=Kind(0.d0))                        :: Dtau, Ham_T, Ham_Chem, XB_X, XB_Y, Phi_X, Phi_Y
         Logical                                       :: Checkerboard, Symm
         Integer :: N, nf, I1, I2
         Allocate(wf_l(n_fl),wf_r(n_fl))
         do n=1,n_fl
            Call wf_alloc(wf_l(n),ndim,n_part)
            Call wf_alloc(wf_r(n),ndim,n_part)
         enddo
         dtau     = 1.d0
         ham_t    = 1.d0
         ham_chem = 1.d0
         xb_x     = 1.d0
         xb_y     = 1.d0
         phi_x    = 0.01
         phi_y    = 0.d0
         checkerboard  = .false.
         symm          = .false.
         Call predefined_hopping(lattice_type, norb,n_coord,ndim, list,invlist,latt, &
            &                    dtau, ham_t, ham_chem, xb_x, xb_y, phi_x, phi_y, &
            &                    n_fl,  checkerboard, symm,  op_tmp )
         Do nf = 1,n_fl
             Call diag(op_tmp(1,nf)%O,op_tmp(1,nf)%U,op_tmp(1,nf)%E)
             do i2=1,n_part
                do i1=1,ndim
                   wf_l(nf)%P(i1,i2)=op_tmp(1,nf)%U(i1,i2)
                   wf_r(nf)%P(i1,i2)=op_tmp(1,nf)%U(i1,i2)
                enddo
             enddo
          enddo
          degen = op_tmp(1,1)%E(n_part+1) - op_tmp(1,1)%E(n_part)
          Do nf = 1,n_fl
             Call op_clear(op_tmp(1,nf),ndim)
          enddo
          Deallocate (op_tmp)