ALF: nranf.f90 File Reference
nranf.f90 File Reference
Functions/Subroutines
integer function nranf (N)
Function/Subroutine Documentation
nranf()
integer function nranf (integer N)
Definition at line 2 of file nranf.f90.
Referenced by hamiltonian::global_move_tau(), upgrade(), wrapgr_mod::wrapgr_test(), wrapgr_mod::wrapgrdo(), and wrapgr_mod::wrapgrup().
       Use random_wrap
       implicit none
       integer :: N
       nranf  = nint(ranf_wrap()*dble(n) + 0.5)
       if (nranf .lt. 1 ) nranf = 1
       if (nranf .gt. n ) nranf = n