ALF: upgrade.f90 File Reference
upgrade.f90 File Reference
Functions/Subroutines
subroutine upgrade2 (GR, N_op, NT, PHASE, Op_dim, ns_new, Prev_Ratiotot, S0_ratio, T0_proposal_ratio, toggle, mode)
This routine updates the field associated to the operator N_op on time slice NT to the value ns_new.
Function/Subroutine Documentation
upgrade2()
subroutine upgrade2 (complex (kind=kind(0.d0)), dimension(ndim,ndim, n_fl), intent(inout) GR, integer, intent(in) N_op, integer, intent(in) NT, complex (kind=kind(0.d0)), intent(inout) PHASE, integer, intent(in) Op_dim, integer, intent(in) ns_new, complex (kind=kind(0.d0)), intent(inout) Prev_Ratiotot, real (kind=kind(0.d0)), intent(in) S0_ratio, real (kind=kind(0.d0)), intent(in) T0_proposal_ratio, logical, intent(inout) toggle, character (len=64), intent(in) mode)
This routine updates the field associated to the operator N_op on time slice NT to the value ns_new.
Author
ALF-project
Parameters
[in,out] Gr(Ndim,Ndim,N_FL) Complex
  Green function.  In the move is accepted, then the Green function will be updated
[in] N_op Integer
  Operator number
[in] Nt Integer
  Time slice
[in] Op_dim Integer
  Number of non-zero eigenvalues of the Operator OP_V(N_op,Nt)
[in] nsigma_new Class(Fields)
  nsigma_new contains the new field. Note nsigma_new%f is a array of dimension  nsigma_new%f(1,1)
[in] Mode Character (Len=64)
  If  Mode=Intermediate  then the routine cumulates the fermion weight ratio in the variable
                         Prev_Ratiotot and updates the green function.
  If  Mode=Final         then the routine carries out the move and updates the Green function if accepted
[in,out] Prev_Ratiotot Complex
  Prev_Ratiotot = Prev_Ratiotot*Ratiotot.  Ratiotot corresponds to the ratio of the fermion weights.
[in] S0_ratio,T0_proposal_ratio Real
  If the mode is set to final then Weight = S0_Ratio*T0_proposal_ratio*Abs(Real(Ratiotot))
S0_ratio corresponds to ratio of the bosonic part of the action
T0_proposal_ratio corresponds to the proposal probability ratio
[in,out] toggle Logical
  Returns true if the move is accepted
[in,out] Phase Complex
  If mode=final and the move is accepted then phase is updated.
The phase is defeined as where is the full fermion weight
The weight reads
Definition at line 101 of file upgrade.f90.
References control::control_upgrade(), control::control_upgrade_eff(), hamiltonian::n_sun, hamiltonian::nsigma, and hamiltonian::op_v.
Referenced by wrapgr_mod::wrapgr_random_update(), wrapgr_mod::wrapgrdo(), and wrapgr_mod::wrapgrup().
 !--------------------------------------------------------------------
         Use hamiltonian
         Use random_wrap
         Use control
         Use fields_mod
         Implicit none
         Complex (Kind=Kind(0.d0)), INTENT(INOUT) :: GR(Ndim,Ndim, N_FL)
         Complex (Kind=Kind(0.d0)), INTENT(INOUT) :: Prev_Ratiotot
         Integer                  , INTENT(IN)    :: N_op, Nt, Op_dim
         Complex (Kind=Kind(0.d0)), INTENT(INOUT) :: Phase
         Integer                  , INTENT(IN)    :: ns_new
         Real    (Kind=Kind(0.d0)), INTENT(IN)    :: S0_ratio, T0_proposal_ratio
         Character (Len=64)       , INTENT(IN)    :: Mode
         Logical                  , INTENT(INOUT) :: toggle
         ! Local ::
         class(fields), allocatable   ::  nsigma_new
         Complex (Kind=Kind(0.d0)) :: Mat(Op_dim,Op_Dim), Delta(Op_dim,N_FL)
         Complex (Kind=Kind(0.d0)) :: Ratio(N_FL), Ratiotot, Z1
         Integer ::  n,m,nf, i
         Complex (Kind=Kind(0.d0)) :: Z, D_Mat, myexp, s1, s2
         Real    (Kind=Kind(0.d0)) :: Weight
         Complex (Kind=Kind(0.d0)) :: u(Ndim,Op_dim), v(Ndim,Op_dim) ,alpha, beta
         Complex (Kind=Kind(0.d0)) :: y_v(Ndim,Op_dim), xp_v(Ndim,Op_dim)
         Complex (Kind=Kind(0.d0)) :: x_v(Ndim,Op_dim)
         Complex (Kind=Kind(0.D0)), Dimension(:, :), Allocatable :: Zarr, grarr
         Complex (Kind=Kind(0.D0)), Dimension(:), Allocatable :: sxv, syu
         toggle = .false.
         ! if ( abs(OP_V(n_op,1)%g) < 1.D-12 )   return
         Allocate (nsigma_new)
         Call nsigma_new%make(1,1)
         ! Compute the ratio
         nf = 1
         nsigma_new%f(1,1)  = real(ns_new,kind=kind(0.d0))
         nsigma_new%t(1)    = op_v(n_op,nf)%Type
         Do nf = 1,n_fl
            !Z1 = Op_V(n_op,nf)%g * ( Phi_st(ns_new,Op_V(n_op,nf)%type) -  Phi_st(ns_old,Op_V(n_op,nf)%type))
            z1 = op_v(n_op,nf)%g * ( nsigma_new%Phi(1,1) -  nsigma%Phi(n_op,nt) )
            Do m = 1,op_v(n_op,nf)%N_non_zero
               myexp = exp( z1* op_v(n_op,nf)%E(m) )
               z = myexp - 1.d0
               delta(m,nf) = z
               do n = 1,op_v(n_op,nf)%N_non_zero
                  mat(n,m) = - z * gr( op_v(n_op,nf)%P(n), op_v(n_op,nf)%P(m),nf )
               Enddo
               mat(m,m) = myexp + mat(m,m)
            Enddo
            If (Size(mat,1) == 1 ) then
               d_mat = mat(1,1)
            elseif (Size(mat,1) == 2 ) then
               s1 = mat(1,1)*mat(2,2)
               s2 = mat(2,1)*mat(1,2)
               If (abs(s1) > abs(s2)) then
                 d_mat = s1*(1.d0 - s2/s1)
               else
                 d_mat = s2*(s1/s2 - 1.d0)
               Endif
               !  D_mat =  - Mat(2,1)*Mat(1,2)
            else
               d_mat = det(mat,Size(mat,1))
            endif
            ratio(nf) =  d_mat * exp( z1*op_v(n_op,nf)%alpha )
         Enddo
         ratiotot = product(ratio)
         nf = 1
         !Ratiotot = (Ratiotot**dble(N_SUN)) * Gama_st(ns_new, Op_V(n_op,nf)%type)/Gama_st(ns_old, Op_V(n_op,nf)%type)
         ratiotot = (ratiotot**dble(n_sun)) * nsigma_new%Gama(1,1)/nsigma%Gama(n_op,nt)
         !Write(6,*) Ratiotot
         If      (mode  == "Final"       ) Then
            !Write(6,*) "Up_I: ", Ratiotot
            ratiotot = ratiotot * prev_ratiotot
            !Write(6,*) "Up_f: ", Ratiotot
            weight = s0_ratio * t0_proposal_ratio * abs(  real(Phase * Ratiotot, kind=kind(0.d0))/real(Phase,kind=Kind(0.d0)) )
            !Write(6,*) Phase, Prev_Ratiotot, S0_ratio, T0_proposal_ratio, ns_old,ns_new
         elseif  (mode == "Intermediate" ) Then
            weight = 1.5d0
            !Write(6,*) "Up_I: ", Ratiotot
            prev_ratiotot = prev_ratiotot*ratiotot
         else
            Write(6,*) 'Error'
            stop
         endif
         toggle = .false.
         if ( weight > ranf_wrap() )  Then
            toggle = .true.
            If (mode == "Final"  )  phase = phase * ratiotot/sqrt(ratiotot*conjg(ratiotot))
            !Write(6,*) 'Accepted : ', Ratiotot
            Do nf = 1,n_fl
               ! Setup u(i,n), v(n,i)
               beta = 0.d0
               call zlaset('N', ndim, op_dim, beta, beta, u, size(u, 1))
               call zlaset('N', ndim, op_dim, beta, beta, v, size(v, 1))
               do n = 1,op_v(n_op,nf)%N_non_zero
                  u( op_v(n_op,nf)%P(n), n) = delta(n,nf)
                  do i = 1,ndim
                     v(i,n) = - gr( op_v(n_op,nf)%P(n), i, nf )
                  enddo
                  v(op_v(n_op,nf)%P(n), n)  = 1.d0 - gr( op_v(n_op,nf)%P(n),  op_v(n_op,nf)%P(n), nf)
               enddo
               call zlaset('N', ndim, op_dim, beta, beta, x_v, size(x_v, 1))
               call zlaset('N', ndim, op_dim, beta, beta, y_v, size(y_v, 1))
               i = op_v(n_op,nf)%P(1)
               x_v(i, 1) = u(i, 1)/(1.d0 + v(i,1)*u(i,1) )
               call zcopy(ndim, v(:, 1), 1, y_v(:, 1), 1)
               do n = 2,op_v(n_op,nf)%N_non_zero
                  call zcopy(ndim, u(:, n), 1, x_v(:, n), 1)
                  call zcopy(ndim, v(:, n), 1, y_v(:, n), 1)
                  z = 1.d0 + u( op_v(n_op,nf)%P(n), n)*v(op_v(n_op,nf)%P(n),n)
                  alpha = -1.d0
                  Allocate(syu(n), sxv(n))
                  call zgemv('T', ndim, n-1, alpha, y_v, ndim, u(1,n), 1, beta , syu, 1)
                  call zgemv('T', ndim, n-1, alpha, x_v, ndim, v(1,n), 1, beta , sxv, 1)
                  alpha = 1.d0
                  call zgemv('N', ndim, n-1, alpha, x_v, ndim, syu, 1, alpha, x_v(1, n), 1)
                  call zgemv('N', ndim, n-1, alpha, y_v, ndim, sxv, 1, alpha, y_v(1, n), 1)
                  do m = 1,n-1
                     z = z - syu(m)*sxv(m)
                  enddo
                  z = 1.d0/z
                  call zscal(ndim, z, x_v(1, n), 1)
                  Deallocate(syu, sxv)
               enddo
               IF (size(op_v(n_op,nf)%P, 1) == 1) THEN
                 CALL zcopy(ndim, gr(1, op_v(n_op,nf)%P(1), nf), 1, xp_v(1, 1), 1)
                 z = -x_v(op_v(n_op,nf)%P(1), 1)
                 CALL zgeru(ndim, ndim, z, xp_v(1,1), 1, y_v(1, 1), 1, gr(1,1,nf), ndim)
               ELSE
                 Allocate (zarr(size(op_v(n_op,nf)%P, 1), op_dim), grarr(ndim, op_dim))
                 zarr = x_v(op_v(n_op,nf)%P, :)
                 grarr = gr(:, op_v(n_op,nf)%P, nf)
                 alpha = 1.d0
                 CALL zgemm('N', 'N', ndim, op_dim, op_dim, alpha, grarr, ndim, zarr, size(op_v(n_op,nf)%P, 1), beta, xp_v, ndim)
                 Deallocate(zarr, grarr)
                 beta  = cmplx( 1.0d0, 0.0d0, kind(0.d0))
                 alpha = -1.d0
                 CALL zgemm('N','T',ndim,ndim,op_dim,alpha,xp_v, ndim, y_v, ndim,beta,gr(1,1,nf), ndim)
               ENDIF
            enddo
            ! Flip the spin
            nsigma%f(n_op,nt) = nsigma_new%f(1,1) ! real(ns_new,Kind=kind(0.d0))
         endif
         If ( mode == "Final" )  then
            Call control_upgrade(toggle)
            Call control_upgrade_eff(toggle)
         endif
         Call nsigma_new%clear()
         Deallocate (nsigma_new)