ALF: wrapgrup.f90 File Reference
wrapgrup.f90 File Reference
Functions/Subroutines
subroutine wrapgrup (GR, NTAU, PHASE)
Function/Subroutine Documentation
wrapgrup()
subroutine wrapgrup (complex (kind=kind(0.d0)), dimension(:,:,:), intent(inout), allocatable GR, integer, intent(in) NTAU, complex (kind=kind(0.d0)), intent(inout) PHASE)
Author
ALF-project
Given the green function matrix GR at time NTAU the routine propagates it to time NTAU + 1 and carries out an update of the fields at time NTAU+1 NTAU: [0:LTROT-1]
Definition at line 33 of file wrapgrup.f90.
References hop_mod::hop_mod_mmthl_m1(), hop_mod::hop_mod_mmthr(), hamiltonian::n_fl, hamiltonian::nsigma, hamiltonian::op_v, and wrapgr_mod::wrapgr_random_update().
 !--------------------------------------------------------------------
 !
 !
 !--------------------------------------------------------------------
         Use hamiltonian
         Use hop_mod
         Use wrapgr_mod
         Implicit none
         Interface
            Subroutine upgrade(GR,N_op,NT,PHASE,Op_dim)
              Use hamiltonian
              Implicit none
              Complex (Kind=Kind(0.d0)) :: GR(Ndim,Ndim, N_FL)
              Integer, INTENT(IN) :: N_op, Nt, Op_dim
              Complex (Kind=Kind(0.d0)) :: Phase
            End Subroutine upgrade
         End Interface
         ! Arguments
         COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT), allocatable ::  GR(:,:,:)
         COMPLEX (Kind=Kind(0.d0)), INTENT(INOUT) ::  PHASE
         INTEGER, INTENT(IN) :: NTAU
         !Local
         Integer :: nf, N_Type, NTAU1,n, m, X
         Complex (Kind=Kind(0.d0)) :: Mat_TMP(Ndim,Ndim)
 !         Real    (Kind=Kind(0.d0)) :: X
         Character (Len=1)  :: Direction
         ! Wrap up, upgrade ntau1.  with B^{1}(tau1)
         ntau1 = ntau + 1
         Do nf = 1,n_fl
            CALL hop_mod_mmthr   (gr(:,:,nf), nf )
            CALL hop_mod_mmthl_m1(gr(:,:,nf), nf )
            !CALL MMULT ( MAT_TMP,    Exp_T(:,:,nf), GR(:,:,nf)        )
            !CALL MMULT ( GR(:,:,nf), MAT_TMP      , Exp_T_M1(:,:,nf)  )
         Enddo
         Do n = nt_sequential_start,nt_sequential_end
            ! Write(6,*) 'Hi'
            Do nf = 1, n_fl
               x = nsigma(n,ntau1)!Phi(nsigma(n,ntau1),Op_V(n,nf)%type)
               n_type = 1
               Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
            enddo
            nf = 1
            Call upgrade(gr,n,ntau1,phase,op_v(n,nf)%N_non_Zero)
            do nf = 1,n_fl
               n_type =  2
               Call op_wrapup(gr(:,:,nf),op_v(n,nf),x,ndim,n_type)
            enddo
         Enddo
         If ( n_global_tau > 0 ) then
            direction = "u"
            m         = nt_sequential_end
            !Write(6,*) "Calling  Global_tau_mod_Random_update:", m,direction, Size(OP_V,1)
            Call wrapgr_random_update(gr,m,ntau1,direction, phase )
         Endif