ALF: wrapur.f90 File Reference
wrapur.f90 File Reference
Functions/Subroutines
subroutine wrapur (NTAU, NTAU1, UDVR)
Imaginary time propagation and udv decompostion from Ntau to Ntau1, Ntau1 > Ntau.
Function/Subroutine Documentation
wrapur()
subroutine wrapur (integer, intent(in) NTAU, integer, intent(in) NTAU1, class(udv_state), dimension(:), intent(inout), allocatable UDVR)
Imaginary time propagation and udv decompostion from Ntau to Ntau1, Ntau1 > Ntau.
Parameters
[in,out] udvr
On input B(NTAU ,1) = UR*DR*VR
On output B(NTAU1,1) = UR*DR*VR
Parameters
[in] Ntau,Ntau1 Integer
[in,out] UDVR Class(UDV_state)
Definition at line 34 of file wrapur.f90.
References hop_mod::hop_mod_mmthr(), hamiltonian::n_fl, hamiltonian::nsigma, hamiltonian::op_v, and udv_wrap_mod::udv_wrap_pivot().
Referenced by main(), tau_m_mod::tau_m(), and tau_p_mod::tau_p().
 !--------------------------------------------------------------------
 !
 !-------------------------------------------------------------------
         Use hop_mod
         Use udv_state_mod
 #if defined(STAB2) || defined(STAB1)
         Use hamiltonian
         Use udv_wrap_mod
         Implicit None
         ! Arguments
         CLASS(UDV_State), intent(inout), allocatable, dimension(:) :: udvr
         Integer,          Intent(IN) :: NTAU1, NTAU
         ! Working space.
         Complex (Kind=Kind(0.d0)) :: Z_ONE
         COMPLEX (Kind=Kind(0.d0)) :: V1(Ndim,Ndim), TMP(Ndim,Ndim), TMP1(Ndim,Ndim)
         Integer ::NCON, NT, I, J, n, nf
         Real (Kind=Kind(0.d0)) :: X
         ncon = 0  ! Test for UDV ::::  0: Off,  1: On.
         z_one = cmplx(1.d0, 0.d0, kind(0.d0))
         Do nf = 1,n_fl
            CALL initd(tmp,z_one)
            DO nt = ntau + 1, ntau1
               !CALL MMULT(TMP1,Exp_T(:,:,nf) ,TMP)
               Call hop_mod_mmthr(tmp,nf)
 !             TMP = TMP1
               Do n = 1,Size(op_v,1)
 !                  X = Phi(nsigma(n,nt),Op_V(n,nf)%type)
                  Call op_mmultr(tmp,op_v(n,nf),nsigma%f(n,nt),'n')
               ENDDO
            ENDDO
            CALL mmult(tmp1,tmp, udvr(nf)%U)
            if(allocated(udvr(nf)%V)) then
               DO j = 1,ndim
                   DO i = 1,ndim
                     tmp1(i,j) = tmp1(i,j)*udvr(nf)%D(j)
                   ENDDO
               ENDDO
               tmp = udvr(nf)%V
            endif
            CALL udv_wrap_pivot(tmp1(:,1:udvr(nf)%N_part), udvr(nf)%U, udvr(nf)%D, v1,ncon,ndim,udvr(nf)%N_part)
            if(allocated(udvr(nf)%V)) CALL mmult(udvr(nf)%V, v1, tmp)
         ENDDO
 #else
         Implicit None
         ! Arguments
         CLASS(UDV_State), intent(inout), allocatable, dimension(:) :: udvr
         Integer,          Intent(IN) :: NTAU1, NTAU
         ! Working space.
         Integer :: NT, n, nf
         Do nf = 1,n_fl
            DO nt = ntau + 1, ntau1
               Call hop_mod_mmthr(udvr(nf)%U,nf)
               Do n = 1,Size(op_v,1)
                  Call op_mmultr(udvr(nf)%U,op_v(n,nf),nsigma%f(n,nt),'n')
               ENDDO
            ENDDO
            CALL udvr(nf)%decompose
         ENDDO
 #endif